## 19. More Cleanup going Numeric

In [4]:
import numpy as np

In [5]:
import pandas as pd
data_url = 'https://andybek.com/pandas-nutrition'
df = pd.read_csv(data_url)
df=df.drop('Unnamed: 0', axis=1)
df.head()

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [6]:
df.loc[:,'total_fat'].sum()

'0.1g72g0.2g2.4g2g0.3g0.7g23g24g18g0g0.4g0.1g7.2g15g4.5g16g0.4g0.9g9.2g0.5g1.7g5.9g33g15g0g0g3g0.4g68g1.5g0.2g11g0.8g16g0.2g0.5g50g0.3g0.6g3g16g3.1g11g2.4g0g0.3g0.5g99g0.1g5.3g5.3g0.4g5.3g0.2g0.3g6.4g22g1g14g10g17g14g4.3g22g36g0.7g100g27g2.8g5.8g14g0.7g1.5g11g34g0.2g0.9g4.6g0g0.4g19g0.2g10g28g6.7g6.7g0.3g0.3g44g37g14g50g0.9g0.7g0.1g0.7g8g10g19g9.2g0g0.2g8.6g1.3g14g0.4g0.2g8.2g5.2g3.3g2.1g0.1g80g0.5g1.4g0.4g3.3g0.2g0.7g0.1g9.4g0.3g0.6g29g0.2g1.4g0.2g0.4g1.2g1.8g0g0.9g0.2g1.4g0.8g1.5g9.8g0g13g16g19g7.4g0.2g5.2g29g0.3g9.9g22g14g15g4.1g0.5g3.5g15g20g32g1g81g0.2g1.6g0g17g22g7.1g7.4g0.2g8.7g1.4g34g0.3g6.3g30g8.1g0.2g0.1g3.7g0.6g0.3g3.9g0.3g1.2g29g14g26g1.1g2g13g0g9g22g3.7g100g0.1g2.1g2.1g0.3g0.2g6.8g8.1g8.3g2.4g0.2g23g6.7g1g0.3g0.2g0.1g12g17g0.1g100g3.4g0.2g6.7g1.5g22g0g1g25g34g3.6g100g7.3g9g1.6g0.4g0.3g18g0.4g9.5g1.4g11g3.1g1.5g0g2.4g3.6g0g15g1.2g6.6g0.7g4.2g15g0.1g0.5g0.2g0.1g3.5g3g0.1g0.4g0.1g0.3g100g31g2.8g9.7g2.3g11g1.7g0.1g1.7g0.5g4.7g0.5g0.2g8.6g18g25g0.5g0.5g26g7.7g0.1g0.1g100g1.1g16g2.4g0.1g21g7g0.3g0.3g19g1.2g1.9g28g0.6g0g100g6.4g2.2g0.1g0.4g1.4g3.4g9.6g23g9.6g21g1.5g0g0.5g8.9g0g0g22g22g0.3g1.1g1.1g0.4g42g2g100g15g51g0.4g0.7g0.4g0.8g7.2g1.9g0.3g0g24g1.2g0.2g13g7.3g25g16g0.2g4.3g22g18g26g2.8g0.9g0g0g4.8g1.5g15g3.4g8.7g0g0.2g1.6g1.8g0.6g100g100g0.2g0.2g0.1g2.7g1.6g9.6g27g31g7.4g0g0.5g0.3g0.8g9.7g1.7g4.3g0.6g15g100g9.8g2.1g0.6g0g0.5g0.1g0.7g13g0.2g44g10g8.1g11g0g0.3g13g4.7g13g2g0.5g24g0.2g11g0.2g0.5g0.6g27g0.7g0.9g4.6g0.1g0g4g2.7g1.9g0.2g1.1g6g0.7g6.1g21g1.3g8.4g6.7g0.2g0.8g100g9.3g0.2g0.3g30g0.1g31g1.2g100g0.2g0.4g0.9g0.1g0g11g16g17g6.2g0.1g24g59g6.1g4.9g0.3g30g2.7g33g29g100g4.4g0.2g15g13g30g5.9g0g2.2g100g6.6g0.3g13g0.3g0.4g0.1g0.6g4.9g0.3g0.2g0.1g0.3g1g0.5g16g0.1g5.6g1.3g0.7g0.1g0.6g5.3g5.9g0.1g2.4g0.5g42g32g30g31g81g100g14g0.2g0.2g4.4g3.5g0.6g3.4g0g14g100g100g0.4g0g3.1g1.9g0.4g0.8g2.3g27g7.4g0.3g0.2g11g18g1g0.9g1.1g1.1g0.3g0.3g0.6g1.2g0.2g0.4g11g100g0.7g26g0.1g0.4g0.4g30g0g0.1g26g35g50g0.1g0.6g0.2g3g0.1g3.5g100g0.4g0.4g0.1g4.3g1.5g8.6g0.3g0.2g0.6g5g32g34g20g0.3g0.9g7g0.9g21g3.1g0.1g31g27g0.4g29g28g0.3g1.7g0.6g0.2g0.1g0g100g100g100g0.1g0.2g0.5g0.1g0.2g0.9g0.1g0.1g0.1g3.2g28g21g0g0.1g1.7g0.6g0.3g99g2.5g17g4.3g0.7g0.3g0.4g0.7g0.4g100g100g6g1.1g100g0.3g0.1g0.3g0.3g0g0.7g0.7g0.2g0g0.3g100g20g0.7g0.4g0.5g0.2g1.8g0.2g2.1g1.3g0.4g4.2g21g100g100g0.2g100g0g0.1g9.7g0.6g100g3.3g1.8g0.2g10g0.1g0.3g2g0.2g6g3.4g100g100g2.1g1.6g0.7g0.9g0.2g0.2g0.3g2.3g0.1g9.7g0.2g100g0g4.2g0.1g11g11g0g11g1.7g3.3g100g6.9g6g0.1g4.3g1.1g1.2g2.5g13g2g14g0.4g3.8g9.5g15g100g1.8g30g18g20g30g14g26g1.4g0.2g20g13g5.2g6.4g4.3g4.2g16g37g0.3g11g0.3g13g0g0.9g27g12g1.2g0.8g3.4g0.3g0.8g12g10g1.1g30g4.3g4.3g0.6g18g0.4g24g5.9g0.1g28g5.5g18g0g8.8g50g100g1.9g8.9g5.2g12g4.8g4.3g0.5g1.7g14g25g13g4.4g11g13g0.5g23g3g2.5g7.3g25g17g4.4g14g7.6g7.2g5.8g20g0.4g0.1g2.4g6.3g0g0.2g2.1g7.2g2.3g3.2g0.9g0.1g0.8g0.9g55g19g2.5g13g0.1g9.3g100g0.5g0.2g9g23g20g5.9g6.3g5.1g25g13g0.1g0g0.1g36g5g3.6g2g0.6g1.9g1.1g18g0.7g1.9g0.2g30g0.4g5.8g0.3g12g0.7g4g7.1g22g20g31g36g34g1.6g3.4g1.2g13g12g30g18g0.1g2.6g5.5g3.1g0.2g8.8g1.2g3.5g6.3g3.2g5.2g100g22g7.2g4.8g2.3g0g0.7g0.2g3.2g0.5g5g0.1g2.7g0.1g10g1g14g21g0g1.5g4g2.2g0.3g21g52g5.6g0.3g3g6.7g0.2g0.4g0.2g0.2g1.1g0.1g0.4g13g4g8g1.8g0.5g0.1g1.2g12g0g0.6g0.5g17g100g0.1g3.8g2.5g2.7g2.7g2.9g4.5g3.3g28g5.1g5g4.3g20g28g30g26g0.1g0.3g0g3.8g29g2.2g6.9g59g4.9g0.5g16g25g11g4.7g2.2g14g0.5g6.5g17g30g0g3g6g0.1g1g1.9g1.7g50g13g6.7g1.5g24g24g1.1g0.1g11g0.1g0.4g4.9g12g28g21g31g19g13g16g28g4.9g13g15g81g3.3g3.1g0.3g14g17g61g4.2g0g0.2g9.5g8.2g19g26g30g8.8g31g0.1g50g0.1g12g51g4.4g0.6g0.5g0.3g14g5.2g10g0.8g0.2g0g0g0.2g78g2.4g0.6g26g2.5g14g0.1g26g0.2g8.1g7.3g0.3g1.2g0.9g3.3g2.2g100g10g4.4g10g2.6g14g8.7g27g0.3g14g3.3g4.7g0g15g4.8g2.9g1.7g4.7g16g15g0.1g10g2.7g2.8g29g15g3.3g3g34g0g12g0.2g29g0.1g3.7g4g1.2g1.7g0.2g1g33g1.3g1.1g32g9.5g0.3g15g1.2g14g2.4g4.4g27g0g7.4g0.1g0.3g0.6g2.2g8.9g12g24g20g6.1g12g3.3g0.1g12g5g0.7g76g27g16g2g0.7g0.3g45g15g0.5g31g5.2g9g11g14g0.1g3.6g0.1g0g1.2g0g18g40g1.7g1.7g0g0.2g9.7g0.3g23g15g1.3g89g23g0g7.7g19g8.1g19g21g5.9g24g29g6.4g15g0g12g1.1g15g34g28g1.6g13g7.5g2.3g3.9g6.5g0.7g0g0.7g6g0.2g9.1g0.8g22g0.5g2g1.2g1.2g3.1g0.5g23g4.8g3.6g0.7g26g10g3.3g25g33g38g23g21g13g32g13g64g8.7g5.5g11g0.5g0.5g2g0.7g19g7.1g20g0.2g0g0.2g0.3g2.3g0.3g1.7g31g1.4g2.8g1.4g100g11g0.7g1.7g28g3.8g34g0.1g3.2g9.7g0g0.5g16g0.2g15g15g12g0.2g21g2.3g3.2g1.4g7g5g1.2g4.4g9.5g0.7g2g0.5g1.2g0g17g2.6g0.1g0.3g0g44g0g2g0.3g8.6g0.1g0.6g0.3g49g1.2g35g49g0.2g1.6g32g1g30g12g0g36g3.5g6.1g0.3g17g15g6g3.8g20g7g1.2g0.8g0.4g16g0.1g0.2g53g14g8.1g0.2g29g4.4g4.8g4.4g0.8g4g1.7g53g0.1g57g29g0.1g1.7g0.4g2.4g22g5.8g0.4g5.4g33g16g22g0.3g15g17g0.6g36g21g0.1g0.1g0.2g14g0.1g0.2g2.9g0.4g7.1g3.4g0.3g0.5g4.6g2.7g7.2g1.4g0.5g11g25g2g0.2g25g0g7.5g0.6g0.9g0g3.9g0.1g65g5.5g4.2g36g0.2g9.5g30g0.4g13g2.9g8.4g0.9g5.1g0.2g4.8g15g0g26g0.5g18g10g6.7g49g48g0.6g44g38g1.4g31g7.4g1.6g0.5g18g0.2g25g1.9g1.6g1.5g11g18g13g6.4g34g6.2g0.1g3.5g1.2g20g3g9.5g0.1g1.7g3.3g0.8g20g2.2g0.1g0.4g3.7g0.3g0.5g0g1.4g0.4g0.6g23g0.9g1.8g78g67g2.6g3.3g14g14g0.6g5.9g70g4.4g0g0.3g12g0.4g2.6g9.8g18g14g4.2g0.1g2.1g0.2g2g1.6g26g3.6g6.8g23g8.7g10g24g3g19g30g16g0.6g17g3.7g10g14g0g0.1g0.8g0.1g24g20g27g1.2g33g2.4g0.3g12g12g9.3g30g1.8g0.7g11g0g2g0.3g15g0.1g7g0g0.3g4.2g4g0.1g2.1g12g1.4g5g14g0.1g0.3g55g4.3g14g0.3g18g66g34g15g30g6g4.3g0.9g0.4g28g0g0.2g0.2g8.7g0.2g0.1g28g12g7.6g0.3g0.1g12g0g12g20g1.4g0.2g0.3g0g2.2g0.2g0.9g100g38g0.9g6.4g1.5g0.7g1g1g3.2g0.4g9g0.2g7.9g0.4g1.7g0.6g0.8g25g2.5g0.2g54g0.1g16g25g16g24g10g20g0.1g6.2g2.5g5.3g100g43g21g14g12g5g20g0.1g0.7g0.2g1.2g19g1.9g2.8g14g1g0.7g3.4g18g0.8g53g2.7g19g0.2g12g2.1g3.1g16g0.7g0g22g6.3g8.3g0.2g9.1g10g11g17g4.6g4.4g31g12g0g0.2g2.6g13g24g7g1g0.5g1.5g0.4g1.3g24g0.1g6.1g0g50g0g1.7g0.3g14g1g13g1.2g0.7g0g0.3g0.1g22g3.7g0.6g0.2g0.2g0.9g1g7.9g3g0.1g29g5.6g2.8g1.3g8g0.5g44g0g15g0.1g100g0.9g0g12g99g0.1g0.2g0.3g5.3g9.2g21g17g0.4g1g33g1.5g0.4g31g0g0.3g13g3.9g10g1.3g0g6.6g7.9g0.3g0g0.4g0.1g0.5g6g0.7g0.2g1.2g22g13g2.4g13g1.5g5.3g7.7g26g79g7.2g9g0.9g2.3g2.6g20g8.6g2g0.2g3.3g6.3g1.3g0.8g10g22g30g0g14g16g26g0.1g19g19g18g11g1.5g6.9g14g0.2g20g0.1g2.7g8.7g22g11g1.2g13g11g13g0g4.7g30g22g0.6g0.1g0.8g1g0.2g23g20g0.7g0.6g26g4.8g9.3g0.3g0.5g20g0.6g3.2g4.8g2.2g0g3g10g6.3g5.4g1.8g0.2g2.4g0g26g8.8g0g17g1g6.2g46g25g0g12g18g0.1g0.7g29g4.2g20g0g8.5g0g26g0.2g0.2g0.3g15g0.2g0.2g0.5g0.2g0.7g0.1g62g5g12g8.6g2g3.2g0.3g0.5g35g4.7g0.1g0g24g0.7g25g0g4.5g2.1g0.9g2.7g18g18g9.2g1.4g31g3.9g0.1g1.8g1.5g3.5g20g0.1g7.4g5.5g0.6g29g0.9g5g12g0g0g0g0g0g24g16g18g0.1g11g5.6g3.9g2.7g1.7g0.7g2.1g1.1g0.2g0.1g0g3.5g0.4g20g0g2g3.5g1.4g2.3g1g5.9g19g55g0g0g7.9g1.9g0.6g0.1g0g7.7g66g0.2g0.4g0.5g13g1g22g9.6g30g1.6g17g7.5g0.2g0.1g3.9g16g13g0.2g6.2g9.1g32g0g24g25g0.4g0.9g21g24g1.1g15g1.7g53g3.8g0.4g0.1g21g12g0.3g1.6g4.9g6.6g3.5g7.2g0.1g0.2g10g4.2g3.3g30g4.7g29g16g2.6g1.6g1g1.5g1.1g8.4g2.7g0g0g2.5g7.1g2.5g6.5g0.2g0.1g12g1.2g3.9g0g26g2.7g14g4.9g19g0g19g27g2.4g11g1.4g0.6g0.3g18g0g33g0.8g12g1g9g12g0.2g16g28g9.1g5g16g2.1g0.4g13g1.5g44g3.4g0.4g5.1g2.1g18g0.1g0.2g0.1g5.1g9.2g13g1.4g0.6g0.5g3.4g4.6g15g100g23g27g22g3.7g16g0.9g1.1g1.1g23g12g17g18g7.1g9.6g3.8g0.5g40g61g21g35g0.1g4.1g52g16g2.3g2.5g3.1g17g11g3.9g0.6g1.4g0g0.5g6.5g22g0.3g16g16g24g2.7g0g0.5g2.7g0.1g0.1g1.2g19g17g0g3.8g11g0.3g4.3g1.1g2.9g2.5g100g3.6g20g3.1g15g14g10g2.1g1.3g2.6g0.4g0.1g4g5.8g0.1g15g18g26g24g26g0.2g0.5g12g0.9g6.9g0.2g10g3.8g12g3.1g2.6g2.1g2.8g10g3.9g1.1g0.1g1.1g21g24g4.6g3.7g0g13g0.4g4.4g1.9g4.1g19g12g12g2.7g22g2.6g3.2g100g0.4g4.5g4.4g3.3g0.4g3.3g1g0.5g14g15g0g0.4g2.4g1.1g0.4g50g8g1.7g17g16g3.2g50g1.8g0g45g0g21g24g23g15g7.6g19g18g5g0.1g3.3g17g6g17g25g0.1g4.4g4.9g28g0.1g0.3g21g0g4.1g27g4.2g16g34g7.7g3g29g24g14g15g2.1g2.6g24g5.4g4.9g1.6g3.7g29g2.3g0.1g0.2g6.6g2.7g1.9g2.8g5.6g15g12g9.3g12g9.1g5g14g13g0.3g0.2g29g1.2g34g0g18g34g25g0.3g24g3.5g0.6g3.7g1.6g0.2g1g100g8.5g12g28g3.7g35g25g22g0g12g0.1g1.5g15g10g40g27g1.1g6.5g6g3.7g2.7g6.4g2.5g24g0.1g12g2.9g0.2g0g1.7g15g19g19g0g1.6g18g26g34g27g18g2.6g15g34g0.1g13g0.7g2.8g13g0.8g1.2g0g0g43g8.8g16g0.2g5.7g0.2g10g0g0.4g16g39g0.5g0.8g0.6g1.4g9.1g7.1g19g14g9g26g0.2g8.3g100g26g0.1g21g4.4g2g0.8g3.1g0.1g2.9g8g0.9g4.6g4.4g13g0.1g2.1g30g15g0g0.8g0.9g6.9g0.1g0.1g8g5.3g26g51g18g9.5g29g2.8g0g14g0.3g0.1g11g0g4.2g14g27g1.1g1g0.6g15g16g18g0g1g23g18g14g1.7g0.9g12g1.8g23g0g0.8g2.8g8.2g1.3g15g0.1g10g41g0g7g52g29g3.2g1.8g0.2g0g0.8g0.1g0.7g3.6g22g0.2g2.4g0.9g1.2g0.1g25g5.4g8.1g13g2.6g48g5.1g2g0g0.1g14g94g5g2.3g61g14g4.5g0.3g3.5g71g22g30g0.1g0.2g1.2g1.9g1.2g23g0.5g0g1.6g50g2.4g0.9g18g0g35g12g0.2g13g7g0.1g0.3g0.1g0.5g0.5g0.1g13g47g32g1.9g2.1g31g2.9g0g1.4g10g0.2g1.6g0.7g0g16g19g28g1.6g4.4g9.7g1.7g26g33g0.4g1.8g0.1g0g0.2g19g5.2g1.1g4.9g0.3g100g3g1.1g19g50g3g34g14g31g0.4g11g8.5g13g0.4g0.2g16g2.9g0g0.1g61g9g7.6g9.7g18g0.4g2.2g0.1g0.2g18g34g5.3g7.2g5.8g48g0.2g0.5g6.7g9g0.8g0.1g26g0.6g12g0.1g7.3g4.4g2.1g11g11g1.8g24g1.5g2.2g1.8g18g6g0.3g4.7g1.6g0.3g1.1g4.6g0.7g1g0g14g14g0.2g2g18g1.1g0.1g10g15g0.2g8.4g22g1.8g17g0.3g6.8g16g14g0.1g0.2g9.1g2.5g25g36g19g0.1g0.9g29g8.3g3.1g7.4g22g2.1g8.7g9.3g0.4g1.7g0g27g18g23g0g3.2g7.7g3.7g0g0.2g33g4g22g19g4.6g52g0.1g1.2g43g38g14g7.1g0g3.3g0g21g0.7g8.7g0g3.9g3.1g32g0g0.3g20g1.2g18g0g0.1g4.8g5.3g2.5g1.7g0.5g38g19g4.7g42g0.4g0.4g0g0.1g2g11g15g27g25g2.9g3.3g24g0.8g0.4g0.1g10g0g0.3g0.4g2.7g2.2g16g18g5.2g0g35g31g31g51g12g0.6g35g6.1g0g5.6g53g9.5g0.7g7.4g0.2g2.6g0.9g3.8g100g100g100g1.2g23g2.7g15g5.6g31g12g3g32g25g3g1.3g1.3g3.4g4.3g3.8g22g13g16g17g2.5g2.7g0g13g2.2g2.1g12g8.7g0.2g15g24g3.3g3.9g3.9g24g0.3g75g0.8g14g1.4g1.8g9.8g34g1.2g25g3.7g10g12g0g0.3g0g18g19g14g2.4g0.2g2.8g6.9g3.8g0.3g0.5g0.2g0.1g1g2.3g0.1g0.2g4.9g0.3g13g5.9g27g3.7g5.5g0.1g0.1g13g16g0g9.5g0.2g0g0.3g0.1g7.1g2.7g22g1.7g15g7.3g24g4.4g16g0.1g0.3g9.8g0.1g28g31g32g2.4g11g27g12g18g0.2g20g6.3g24g20g0.5g1.4g50g16g5.1g24g12g1g8.4g2.5g20g18g4.6g18g0g0g8.6g0g0g21g0.2g8.2g7.5g3.5g100g3.6g5.2g16g0.3g4g0g12g34g19g21g1.7g3.5g23g0.1g4g1.9g0.2g0.2g0.5g6.7g3.3g0.1g12g0.1g11g3.2g2.3g3.6g0.2g23g0.3g0.6g1.1g0.1g3g8.5g27g17g8.2g1.9g3.4g8.8g1.5g0.4g2.5g9.5g0g9.4g0.2g0.7g0.7g3.5g4.1g7.5g6.2g0.2g18g0g14g8.2g11g1.2g0.1g7.6g11g1.2g16g0g0g2g0.6g2.4g24g17g0.5g0.6g2.4g4.6g5.8g0g0.5g37g11g0.1g6.3g0.1g13g17g4.2g3.3g1.2g2.5g0.2g0.2g0g29g12g0.1g0.8g6g0.2g0.3g2.8g0g1.4g0.3g5.7g10g25g0.1g3.2g50g10g19g6.3g13g21g29g0.1g53g9.3g51g49g6g25g8g25g8.7g32g3.1g9.1g16g0g3.7g13g11g0.2g2.2g33g0.7g8g0.1g0.4g0.1g1.7g3.7g4.9g0.5g7.5g0.6g37g3.3g27g1.4g0.6g10g8.1g1.3g61g25g1.2g1.9g2.6g0.4g0.1g0.3g3.4g8g2.4g55g53g27g0.4g0.1g6.9g22g29g0g0.3g0.2g26g23g0.7g3.9g33g0.4g13g0g4.9g0.4g0.5g0.2g17g1.2g0.3g0g0.2g0.6g14g7.2g0.1g14g22g12g31g1.3g0.3g1g13g13g4.6g39g0.4g0.4g0.1g16g0.8g3.7g21g17g0.2g0g56g23g8.8g21g0g0g0.7g29g0.2g15g12g9.3g12g16g10g0.2g0g3.8g0.3g0.2g0.8g0.9g19g0.9g28g22g0.2g19g5.1g30g2g0.8g0.4g5.2g0.1g20g53g17g19g30g100g8.2g49g0.1g0.2g1.1g0.9g53g10g0.9g0.7g5g4g74g3.4g2.5g3.4g0.4g11g24g0.8g4.3g1.5g20g24g22g0.8g53g75g3.1g18g10g15g0.2g2.1g26g2.7g3.2g55g8.2g0.1g15g23g1.5g3g0.6g0.9g16g3.3g8.1g0.2g0g0g2.4g0.9g1.8g1.5g3.5g7.5g37g4.1g16g5.4g2.3g1.6g5.7g30g8.7g5.3g0.3g5.9g4.5g12g1.3g1.6g0.1g18g7.8g5.3g0g3.5g13g27g23g33g18g32g0.2g1.8g4.8g55g23g0.1g25g22g0.2g0.9g0.2g4.6g6.1g0g0g19g1.2g2.8g4.6g6.1g0g8.9g9.7g20g0.1g32g100g0g21g4.1g0.8g25g0.2g0.2g2.3g0.1g9.3g3.4g0.5g25g15g3.7g0.5g38g42g3.9g18g13g0.1g25g0.1g0.1g0g27g1.5g6.9g44g4.5g0.2g18g9.2g20g5.1g25g0.7g14g3g0.1g7.5g0.1g1.8g0.3g0.8g0g13g7g1.8g0g0g0.9g7.2g9.4g27g21g15g0.4g4.6g27g10g3.5g4.1g20g18g18g0g0.2g23g3.6g4.6g1.3g20g3.8g22g5.7g16g17g0.9g0.9g1.5g22g22g10g0.3g19g0.3g0.6g6.3g0g0.9g4.7g3.5g0g0.9g0.9g2.5g31g8.2g2.2g0.4g0g27g19g15g0g84g7.5g0.1g0.6g0.5g8.4g13g26g1g4.5g0.3g0.3g1.7g5g11g20g5.6g14g0.4g0.2g12g0g49g13g51g39g38g29g17g0.1g12g11g10g3.8g5.8g0g25g0.2g7g3g12g4.2g3g17g17g6g16g0.3g12g14g9.2g0.1g1.1g8.9g3.5g12g19g100g24g0g3.9g100g4.9g0.2g4.2g9.6g2.7g0.3g4.8g0.9g3.4g0.3g0.4g3.8g24g17g51g1.4g1.9g1g6.1g1g5.4g2.9g17g3.8g1.9g18g6.3g1.2g24g0.2g0.2g0.6g2.3g21g23g0g0g6.6g58g1.3g2.8g5g0.4g0g0g4g4.1g4.1g4.4g12g0g24g0.9g1.8g0.1g28g16g3.4g16g0.7g26g0.7g11g1.6g0.2g14g2.5g0.2g12g12g1.6g5g0.9g5g0.7g6.4g3.5g3.3g5g20g70g0.3g1.3g7.5g1.4g0g49g0.2g0.7g1.7g100g16g0.2g10g0.2g12g5.3g0.6g0.3g14g25g3.4g0.8g4.5g2.8g17g0.4g1.6g6.9g0.2g1.5g26g18g3.6g0g0g7g20g0g11g2.8g34g17g0.1g0.1g7.6g0.7g22g0.9g4.3g16g0.1g6.3g8.7g8.1g13g2.1g7.5g14g3.4g5g28g0.6g17g3.1g2.7g10g4.9g3.1g2.2g3.1g13g8.6g22g26g0.1g25g1.2g7.5g0.2g23g81g25g0.1g1.6g1.9g0g0.1g0.5g24g18g0g0.4g3.7g18g15g2.1g0.5g0g0.7g3.6g12g0g12g1.8g24g5.4g1.7g0g0.2g19g2.8g3.4g0.2g1.3g0.9g0.3g7.5g20g3g16g0.1g24g8.1g0.2g0.8g0.4g5.6g20g0.3g1.7g3.3g1.5g0g0.1g0.9g0.9g0.1g0.5g1.3g5.7g4.1g0g12g1.2g12g7.2g3g22g0.5g1.5g5.5g17g4.2g0g1.1g37g0.8g0.2g13g14g2.3g0.1g0.2g0.3g6.6g15g0g5.2g11g1.2g2.7g8.1g7.3g7.6g2.1g1.6g0g13g0g8.6g7.8g2g5.6g0g6.3g12g11g0.3g6.9g9.2g0.2g0.2g0.8g5.4g0.3g2.1g19g9.3g44g7g0.3g0g3.5g6.9g38g0.5g0.4g13g0.1g12g61g13g1.3g8.2g13g0.6g1.2g3.4g0.1g6.1g0g7.5g14g15g2.6g1.8g7.4g0.2g0.4g4g0.9g0.2g0g6.9g2g9.1g2.5g2.7g0g0.2g27g0.1g2.9g2.8g10g1.4g0g0.7g5.7g4g5g47g15g32g1g7.6g5.3g12g0.2g0.1g0.6g1g1.7g2.1g0.1g69g2.3g0.2g12g8.3g0.1g7.8g7.4g0.2g1.8g0.2g23g1g0.1g3.8g26g1.8g10g0.3g1.6g1.4g15g1.5g5.2g48g32g32g2.7g0.3g0.9g3.6g1.5g9.2g2.1g20g3.6g0.5g0.7g0.5g0.8g0.1g0g15g0.5g18g3.4g0.1g0g0.1g21g68g0.3g2.6g2.3g4.9g7.6g0.2g4.6g22g2.5g100g13g0.6g8.6g8.2g32g0.3g1.9g0g4g0.6g1.8g8.3g30g0g0.1g0.9g19g1.8g0g0g0g0.6g0g6.8g6.4g3.7g100g9.9g27g0g12g0.3g10g3.9g3.6g2.1g6.8g0.2g1.4g12g9.6g0.1g0.2g17g46g48g0.1g11g1g9.5g6.7g56g19g7.4g2.4g13g0.4g2.1g0.6g4.2g2.1g20g0g0.3g8.1g0g0.9g0g0.9g0.6g7.5g4.6g1.3g21g14g12g36g1g4.9g16g30g3.7g1.8g0.4g0g0.2g4.5g9.5g22g6.4g16g3.5g0.1g1.4g0.4g0.1g0g0g94g0.1g55g53g4.8g1.1g2g25g22g1g0.2g0.1g1.7g2.4g22g1.4g1.9g0.2g0.9g0.1g5.2g5g0g0g23g2.7g2.9g4.8g2.2g14g14g25g0.1g1.4g2.5g49g3.5g11g26g12g0.4g0g1.7g3.9g39g4.3g0g0.4g4.6g7.8g7.8g0g2.3g7g24g31g7.9g7.7g0.1g0.2g44g37g0.4g0.4g1.2g11g0.1g0g11g7.6g36g39g0.2g1.3g0.8g0.5g8.7g0.6g0.1g2.5g0.3g1.6g0g13g6g30g14g19g0.1g0.1g0.3g0.6g24g1.7g0.3g10g0g0.1g0.1g0.2g14g0.3g3g20g0.3g1.6g2.3g3.7g1.8g11g4.7g6.7g0.2g12g45g24g22g1.3g12g0.2g0.5g1.7g4.4g0.3g0g0g0.1g4.2g1.6g0.1g5.5g0.3g0.2g9g0.9g1.6g6.6g0.9g21g29g2.9g1.9g19g5g12g0.8g0.4g0g2.3g9.8g24g2.7g18g3.2g11g27g0g1.6g0g0g8.3g0.1g4g3.5g0g0.1g0.5g1.8g3g0g0.2g3.4g1.6g7.9g6.5g0g1.6g2.6g0.2g0.3g0g0g7.6g0.1g44g20g3.7g7.4g0.1g0.2g2.1g4.3g19g25g18g4.6g2.1g2.7g3.6g26g25g4.8g0.9g19g100g100g33g26g3g15g11g0.3g7.4g4.5g0.3g0.7g2.6g1.4g2.3g28g13g1.1g11g5.7g55g1g75g74g1.9g2g0.5g0.9g0g5.3g3.6g4.6g18g0.2g0.2g99g0.1g15g7.5g4.3g2.2g0g15g4g12g7.8g24g4.1g0.2g8.5g0g10g53g50g0.2g1g1.5g5.5g49g1.8g1.6g0.5g5g48g8.2g7.2g2.9g2.3g1.5g0.2g0.4g18g4g23g25g1.5g1.9g35g34g23g0.5g31g0.1g0.1g1.3g1.2g0g2.1g25g0.1g58g1.8g7.2g11g4g12g1.6g5.8g0.5g11g10g21g3.4g1g72g12g26g3.5g1.9g79g8g0g0.6g1.9g13g0.2g0.4g6.2g29g2.6g8g8.7g100g33g27g0.1g0.5g9.6g6.9g26g0.1g4.4g3.6g13g25g5.1g65g0.7g0.1g2g0.3g0.2g69g13g31g19g0.2g78g18g13g70g9.4g0.3g0.3g0g24g0.2g0.1g5.6g5.1g35g0.1g0g21g7.5g1.5g8.5g7.6g1.6g17g0.1g6.4g3.8g0.2g2.2g4g10g0.1g20g0.1g5.3g3.4g0g0g0.1g36g16g0.5g16g1g28g35g0.2g27g0.6g10g1g29g3.5g100g0.4g20g25g22g0.4g2.1g7.9g0g5.3g0g17g0g0g43g0g0g3.7g7.5g0.2g12g1.4g1.1g6.5g0.1g12g8.1g13g0.1g18g6.5g2.4g2.9g1.6g35g2.7g35g0.6g0.9g33g45g0.8g1.3g70g2.1g49g0.5g3.4g2.7g5.3g1.7g0g8.7g17g20g0.3g0.4g0.6g12g4.4g11g5.5g0g0.2g0.4g12g0.1g7.2g22g51g51g27g0.2g13g1.4g2.4g11g9g3g0.2g4.2g0.5g0.1g0.2g2.9g14g6.2g1.6g57g0.1g9.8g0g3.4g44g3.3g2.9g1g0.6g0.1g4.6g7.1g2.5g0.3g0.4g7.4g1.9g3.5g1.6g5.6g2.8g0.5g19g0.7g16g3.2g1.6g3g4.3g11g23g0.2g3.2g16g3g9.3g3.2g0.2g32g21g22g0.2g11g16g4.5g26g0.1g3.6g15g0g13g6.6g0.2g1g100g0.3g3.5g3.5g9.8g0.2g3.5g0g12g0.7g21g12g64g0.5g2.8g1.2g0.6g0g36g11g3.4g0.1g8.4g6.5g6.2g0.1g0.1g2.3g15g0.4g0.1g4.1g25g13g14g2.2g24g3.6g0.7g0.4g53g0.4g0.3g8.8g0.4g6.1g17g0.2g0.1g0.2g7.1g0g0.3g16g3.4g0.1g2.3g1.6g0.6g11g4.7g22g9.8g1g4.9g25g2.7g0.1g36g11g23g19g0.4g0.1g4g1.4g9.8g8.5g14g0.1g11g6.4g12g17g30g28g1g2.4g0g0g16g3.9g55g0g3.3g0.3g0.5g2g0.4g3.5g8.7g69g0g4.8g10g0.1g0g18g37g0.1g0.2g1.3g2.1g6.8g1.1g3.6g11g11g1.5g1.5g4.8g0.3g0.2g0.4g16g4.1g13g9.8g0.3g3.4g0.5g0.1g7g19g9.1g0g14g0.1g4.6g5.6g0g0.6g0.1g34g0.2g0g4.6g9.1g42g15g0.3g0g0.2g20g0.9g29g0g1.3g25g12g0g0g31g0g0.2g3.7g8.4g14g13g14g13g0.9g6.6g19g5.3g3.2g3.1g0.2g1g3g8g0.1g2.9g16g0g1.9g3.3g0g8.3g1.8g1.3g28g6g0g8.3g0.5g2.9g13g0.2g2.4g19g0g20g3.7g9.6g76g1.2g23g24g31g29g19g12g0.2g46g0.2g0.2g5.7g46g48g7.8g5.7g0.4g0.2g0.3g28g29g0g13g16g23g0g4.7g23g2.1g2.1g20g33g0g0.8g11g0g3.1g16g1.6g72g4.4g0.4g3.1g9.5g0g0g23g24g30g0.2g2g0.4g18g100g27g1.5g16g0.1g9.8g2.8g0.5g21g76g0.6g0.2g1.6g0.2g2.7g0.1g0.1g5g1.5g13g0.2g0.5g0.2g0.1g0.1g2.1g0.2g2.7g1g5.9g4.4g4.1g0.4g5.9g35g6.7g4.8g2.8g2.9g2g6.8g0.3g13g33g26g3.4g1.7g1.3g2.3g0.3g11g3.7g39g0.6g1g0.2g3g3.1g0.2g13g0.8g0.9g1.1g4.3g0g2.9g15g0g0.3g21g0.9g2.2g11g3.2g12g11g0.1g16g3.7g0.8g0.1g2.1g18g25g0.7g11g28g0g0.2g0.6g0.1g16g0.1g12g0.6g19g3.4g4.2g20g19g6g0.3g1.4g99g52g2.6g0.9g0.2g10g4.7g0g19g5.1g0.1g0g0.4g2.9g0.1g1.2g0.1g0.2g13g8.8g17g0.4g6.3g0.7g15g39g21g0g21g3.5g17g7.2g0g0.1g8.5g4.1g2.2g0g0.1g15g0.7g21g2.8g0.4g4.8g29g3.1g4.5g0.4g1.7g7.4g9g2g1.9g0.2g3.7g100g100g57g0.4g7.3g20g7.6g100g0.7g9.8g0.1g1.1g14g26g6g0.2g4.8g15g1.2g3.2g1.7g1.2g0.2g0.4g1.2g9.5g4.6g6.3g68g8.5g9.8g0.3g2g18g3.8g13g20g0.2g1.6g1.5g3.8g0.1g0g2.6g5.1g9.2g26g7.4g8g23g0.3g1.9g3.8g16g4.9g19g30g31g0.1g3.2g28g2.8g25g0.1g9.3g0.5g0.1g0.3g1.6g0.4g0.5g0g10g0g0.1g2.5g17g15g11g17g1.1g6.5g0.3g20g3.4g1.2g3.5g13g11g1.7g4.7g58g1g8.5g9.6g0.1g1g0.7g0.3g0.6g13g11g5.8g4.6g0.8g0.2g1g11g7.5g18g15g0g6.6g18g13g8g1.1g5.9g9.8g0g18g4g4.8g4g18g14g6.4g14g0.3g23g9.5g18g1.7g0.4g0.4g2g0g1.4g26g4.1g1.2g1.7g10g4.1g19g51g4.8g1.2g1.4g27g8.8g6g2.4g36g31g8.8g1.3g4.4g10g0g0.1g1.5g56g3.5g12g13g6.7g4.9g4g4.5g0.1g0.1g16g0.2g0.1g11g0.2g0.2g3g17g36g0.7g17g18g0.2g2.3g4.8g12g100g0.5g15g9.2g20g1g2.7g2.8g2.2g4.8g1.2g3.1g0.1g26g13g0.2g12g0.7g53g8.2g3.6g28g20g0.1g0.2g4.1g0g8.4g28g1.7g1.7g13g10g94g0.2g0.8g5.8g5.3g9.5g0g18g2.8g1.9g11g0.8g0.1g8.4g11g0.8g80g4.8g16g1.9g61g20g2g3.5g2.6g25g0g100g17g0.2g3.5g11g0.5g9.8g1.1g23g18g0g1g1.5g4.5g2.4g1.2g0.4g15g2.3g8.3g0.8g3.6g1.4g0g0.2g25g0.4g6.5g0.4g1.6g21g11g26g17g1.6g19g3.1g0.1g0.2g10g3g0.7g0.9g1.4g1.5g8.5g0g1.5g1.5g0.1g5.1g4.8g16g24g4.2g3.7g0.4g0.8g0.1g3.8g0.3g0.5g16g0g13g5.9g5.7g25g2.9g9g3.1g1g0.7g16g100g8g2.3g0.3g24g25g21g27g21g0.4g5.8g19g0g0.1g66g5.8g27g8.8g16g3.3g0.7g0.4g0.3g81g4g7.3g1.7g11g7.9g30g5g50g51g2.7g0.1g3.4g1.9g0.4g31g41g0.4g0.5g1.5g0.5g0.2g0g5g2.7g15g20g6.5g10g2.7g0g9.3g0.6g0.4g1.4g5.4g0.5g1.1g2g21g9.4g22g0.5g6.3g0g13g8g15g11g9g1.8g5.7g2.6g0.8g52g0.1g0.5g16g14g0.1g0.1g2g0.2g0.2g0.1g0.2g0.1g0.6g2.6g24g0.2g5.6g0.1g0g5.7g0.1g1.7g6.2g8g0.2g3.1g6.3g0.6g5.6g12g2.2g13g0.3g4.7g1.4g7.7g6.7g22g5.1g4.9g18g0.4g9.3g1.6g10g2.4g4g25g24g6.8g0.6g14g0.1g9.9g7.7g0.1g4.3g0.1g0.8g11g17g6.4g5.7g30g0.9g10g12g13g0.5g0.3g0.7g25g0.6g7.6g0g0.4g3.9g0.5g0.3g12g0.1g31g0.1g3.1g0g17g1.7g11g23g24g3.2g33g0.4g0.5g5.5g17g32g4.8g7.1g22g5.8g0.4g0.6g17g3.4g19g17g0.1g0.5g0.4g1.4g11g29g1.6g0.1g1.7g4.4g3.5g15g5.7g9.2g6.3g15g0.2g19g0g10g17g7.6g3.7g2.7g0g15g17g4.2g1.1g10g13g3.3g2.4g6.3g3g11g28g15g0g4.5g2.1g11g100g19g0.1g24g3.7g0.2g1.8g4.1g0g0g9.1g0g4.5g5.1g0.3g4.3g13g4.1g0.8g1.4g0.2g5.4g2.2g11g4.7g4.6g1g9.7g0.5g3.9g28g0.2g0.8g0.4g0g1.1g1.5g1.3g0.2g3.3g1.2g0g0g8.3g0g0g0.1g44g43g15g4.4g15g27g7.8g57g28g5.7g6.4g1g1g0.3g1.2g0.2g2.2g0g0.7g24g0.1g13g0.7g62g2.1g10g5.7g0.2g4.8g1.8g80g12g2.1g1.1g33g9.1g0.3g2.8g0.5g0.6g0.2g0.8g0g0g5.4g10g0.1g1.9g24g0.5g0.1g0.1g2.1g5.8g2g0.5g0.4g1.6g16g34g0.4g0.3g4.5g4.3g1.1g11g0g18g4.7g5.5g76g6g0.6g21g46g22g5.9g12g5.6g1.7g1.8g81g8.1g35g0.8g3.4g0.4g3g3.2g10g5.5g4.7g1.3g6.4g0.9g0.8g0.5g1.4g1.4g6.5g17g13g16g18g8.5g7g9.7g5.4g1.3g3.5g2.3g3.2g3.1g11g5.5g2.8g2.6g0.5g22g0.1g22g4.5g0g9.9g0.7g7.6g11g3.5g5.9g0.1g25g13g48g5.7g5.9g30g1.1g11g0.2g12g5.3g12g12g0.3g7.1g0.7g4.6g0.1g0g0.4g3.7g54g54g4.2g34g2.1g1g9.8g6.1g2.1g6.2g31g2g3.3g7.3g15g3.1g3.2g1.2g3g2.3g5.8g5.7g4.8g2.1g22g29g9.5g13g2g0.4g3.5g16g38g0.4g12g11g8.4g11g3.6g56g1.4g19g1.8g2.9g68g3.5g0.4g2.2g3.5g5.6g7g1.8g0g30g29g4.3g3.7g8g27g3.4g3.3g8.9g10g13g3.2g3.6g7.9g2.4g0.8g0.4g1.5g0.4g17g9.8g6.2g4.4g28g26g31g3.9g60g0.2g9.4g2g0g0.8g37g0.1g0.4g27g9.7g0.3g2.1g13g15g15g5.9g0.5g0.2g2.6g9.9g11g0.6g8.2g8.2g3.9g7.7g0g0g18g11g100g13g25g0.7g0.6g1.2g13g0.1g0.8g4.1g1.3g7.6g0.8g0.1g11g1.2g2.6g17g8.7g4.7g6.3g0.5g22g1.4g3.7g3.5g3.3g0.5g20g10g9.8g3g7.1g5.2g0.1g8.2g8.1g7.1g14g0.5g50g9.1g9.6g9.8g1.9g0.2g1.9g12g3.5g3.6g26g0.7g14g16g0.2g61g10g3g23g10g18g2.2g2.4g2.9g0.8g0.6g4.5g0.5g8.2g10g2.2g80g0.1g0.2g0g13g5g4g0.4g32g7.2g0.1g0.2g0.1g0.7g4.8g29g0.2g12g0.1g4.5g2.6g0g4.1g52g16g13g8.2g1.9g12g15g0.2g4.7g1.7g1.6g20g4.1g9.8g6.5g1.2g11g17g3.6g5.7g1g0.1g17g3.4g10g0.1g0.3g19g6.1g5g11g0.6g0.6g3.5g

In [7]:
df.loc[:,'total_fat'].max()

'9g'

In [8]:
df.loc[8786,'total_fat']

'23g'

In [9]:
df.info(False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 76 entries, name to water
dtypes: int64(2), object(74)
memory usage: 5.1+ MB

## 20. The astype() method

In [10]:
df2 = pd.DataFrame({
    'age':[12,13,14,16],
    'weight':[41.1, 34.5, 55.6, 47.3],
    'height':['1.72','1.78','1.52','1.79'],
})
df2

   age  weight height
0   12    41.1   1.72
1   13    34.5   1.78
2   14    55.6   1.52
3   16    47.3   1.79

In [11]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   weight  4 non-null      float64
 2   height  4 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes

In [12]:
df2=df2.astype(float)

In [13]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      float64
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
dtypes: float64(3)
memory usage: 228.0 bytes

In [14]:
df2=df2.astype({'age':int})

In [15]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     4 non-null      int64
 1   weight  4 non-null      float64
 2   height  4 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 228.0 bytes

## 21. DataFrame replace() + A Glimpse at Regex

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Data columns (total 76 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   name                         8789 non-null   object
 1   serving_size                 8789 non-null   object
 2   calories                     8789 non-null   int64
 3   total_fat                    8789 non-null   object
 4   saturated_fat                7199 non-null   object
 5   cholesterol                  8789 non-null   object
 6   sodium                       8789 non-null   object
 7   choline                      8789 non-null   object
 8   folate                       8789 non-null   object
 9   folic_acid                   8789 non-null   object
 10  niacin                       8789 non-null   object
 11  pantothenic_acid             8789 non-null   object
 12  riboflavin                   8789 non-null   object
 13  thiamin                      8789 non-null   object
 14  vitamin_a                    8789 non-null   object
 15  vitamin_a_rae                8789 non-null   object
 16  carotene_alpha               8789 non-null   object
 17  carotene_beta                8789 non-null   object
 18  cryptoxanthin_beta           8789 non-null   object
 19  lutein_zeaxanthin            8789 non-null   object
 20  lucopene                     8789 non-null   int64
 21  vitamin_b12                  8789 non-null   object
 22  vitamin_b6                   8789 non-null   object
 23  vitamin_c                    8789 non-null   object
 24  vitamin_d                    8789 non-null   object
 25  vitamin_e                    8789 non-null   object
 26  tocopherol_alpha             8789 non-null   object
 27  vitamin_k                    8789 non-null   object
 28  calcium                      8789 non-null   object
 29  copper                       8789 non-null   object
 30  irom                         8789 non-null   object
 31  magnesium                    8789 non-null   object
 32  manganese                    8789 non-null   object
 33  phosphorous                  8789 non-null   object
 34  potassium                    8789 non-null   object
 35  selenium                     8789 non-null   object
 36  zink                         8789 non-null   object
 37  protein                      8789 non-null   object
 38  alanine                      8789 non-null   object
 39  arginine                     8789 non-null   object
 40  aspartic_acid                8789 non-null   object
 41  cystine                      8789 non-null   object
 42  glutamic_acid                8789 non-null   object
 43  glycine                      8789 non-null   object
 44  histidine                    8789 non-null   object
 45  hydroxyproline               8789 non-null   object
 46  isoleucine                   8789 non-null   object
 47  leucine                      8789 non-null   object
 48  lysine                       8789 non-null   object
 49  methionine                   8789 non-null   object
 50  phenylalanine                8789 non-null   object
 51  proline                      8789 non-null   object
 52  serine                       8789 non-null   object
 53  threonine                    8789 non-null   object
 54  tryptophan                   8789 non-null   object
 55  tyrosine                     8789 non-null   object
 56  valine                       8789 non-null   object
 57  carbohydrate                 8789 non-null   object
 58  fiber                        8789 non-null   object
 59  sugars                       8789 non-null   object
 60  fructose                     8789 non-null   object
 61  galactose                    8789 non-null   object
 62  glucose                      8789 non-null   object
 63  lactose                      8789 non-null   object
 64  maltose                      8789 non-null   object
 65  sucrose                      8789 non-null   object
 66  fat                          8789 non-null   object
 67  saturated_fatty_acids        8789 non-null   object
 68  monounsaturated_fatty_acids  8789 non-null   object
 69  polyunsaturated_fatty_acids  8789 non-null   object
 70  fatty_acids_total_trans      8789 non-null   object
 71  alcohol                      8789 non-null   object
 72  ash                          8789 non-null   object
 73  caffeine                     8789 non-null   object
 74  theobromine                  8789 non-null   object
 75  water                        8789 non-null   object
dtypes: int64(2), object(74)
memory usage: 5.1+ MB

In [17]:
dfm=df.iloc[:6, 1]
dfm

0    100 g
1    100 g
2    100 g
3    100 g
4    100 g
5    100 g
Name: serving_size, dtype: object

In [18]:
dfm.info(False)

<class 'pandas.core.series.Series'>
RangeIndex: 6 entries, 0 to 5
dtypes: object(1)
memory usage: 180.0+ bytes

In [19]:
dfm.replace('\sg','',regex=True).astype(int)

0    100
1    100
2    100
3    100
4    100
5    100
Name: serving_size, dtype: int64

In [20]:
df.head(10)

,name,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g
5,"Cauliflower, raw",100 g,25,0.3g,0.1g,0,30.00 mg,44.3 mg,57.00 mcg,0.00 mcg,...,0.28 g,0.130 g,0.034 g,0.031 g,0.00 mg,0.0 g,0.76 g,0.00 mg,0.00 mg,92.07 g
6,"Taro leaves, raw",100 g,42,0.7g,0.2g,0,3.00 mg,12.8 mg,126.00 mcg,0.00 mcg,...,0.74 g,0.151 g,0.060 g,0.307 g,0.00 mg,0.0 g,1.92 g,0.00 mg,0.00 mg,85.66 g
7,"Lamb, raw, ground",100 g,282,23g,10g,73mg,59.00 mg,69.3 mg,18.00 mcg,0.00 mcg,...,23.41 g,10.190 g,9.600 g,1.850 g,73.00 mg,0.0 g,0.87 g,0.00 mg,0.00 mg,59.47 g
8,"Cheese, camembert",100 g,300,24g,15g,72mg,842.00 mg,15.4 mg,62.00 mcg,0.00 mcg,...,24.26 g,15.259 g,7.023 g,0.724 g,72.00 mg,0.0 g,3.68 g,0.00 mg,0.00 mg,51.80 g
9,Vegetarian fillets,100 g,290,18g,2.8g,0,490.00 mg,82.0 mg,102.00 mcg,0.00 mcg,...,18.00 g,2.849 g,4.376 g,9.332 g,0.00 mg,0.0 g,5.00 g,0.00 mg,0.00 mg,45.00 g

In [21]:
df.loc[0:10, 'serving_size']

0     100 g
1     100 g
2     100 g
3     100 g
4     100 g
5     100 g
6     100 g
7     100 g
8     100 g
9     100 g
10    100 g
Name: serving_size, dtype: object

In [22]:
df.loc[:, 'serving_size'].replace('\sg','',regex=True).astype(float)

0       100.0
1       100.0
2       100.0
3       100.0
4       100.0
        ...
8784    100.0
8785    100.0
8786    100.0
8787    100.0
8788    100.0
Name: serving_size, Length: 8789, dtype: float64

## 22. Part I Collecting the Units

In [23]:
df.iloc[:,1:].replace('[^a-zA-Z]','', regex=True)

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,g,381,g,NaN,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
1,g,691,g,g,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
2,g,25,g,NaN,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
3,g,367,g,g,,mg,mg,,,mg,...,g,g,g,g,,,g,,,g
4,g,144,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,g,125,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8785,g,206,g,g,mg,mg,,mcg,mcg,mg,...,g,g,g,g,mg,,g,,,g
8786,g,277,g,g,mg,mg,,mcg,mcg,mg,...,g,g,g,g,mg,,g,,,g
8787,g,121,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8788,g,121,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [24]:
units = df.iloc[:,1:].replace('[^a-zA-Z]','', regex=True)
units['saturated_fat'].value_counts()

saturated_fat
g    7199
Name: count, dtype: int64

In [25]:
units['serving_size'].value_counts()

serving_size
g    8789
Name: count, dtype: int64

In [26]:
units['serving_size'].value_counts()

serving_size
g    8789
Name: count, dtype: int64

## 24. Df dropna()

In [27]:
df2

   age  weight  height
0   12    41.1    1.72
1   13    34.5    1.78
2   14    55.6    1.52
3   16    47.3    1.79

In [28]:
np.nan

nan

In [29]:
df2[1:3] = np.nan
df2 = df2.iloc[:,:3]

In [30]:
df2.iloc[2,0] = 15

In [31]:
df2

    age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  15.0     NaN     NaN
3  16.0    47.3    1.79

In [32]:
df2.iloc[2,2] = 1.15

In [33]:
df2

    age  weight  height
0  12.0    41.1    1.72
1   NaN     NaN     NaN
2  15.0     NaN    1.15
3  16.0    47.3    1.79

In [34]:
df2.dropna()

    age  weight  height
0  12.0    41.1    1.72
3  16.0    47.3    1.79

In [35]:
df2.dropna(how='all')

    age  weight  height
0  12.0    41.1    1.72
2  15.0     NaN    1.15
3  16.0    47.3    1.79

In [36]:
df2.dropna(how='any',axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

## 26. Part II Merging Units with colums Names

In [37]:
units

,serving_size,calories,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
0,g,381,g,NaN,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
1,g,691,g,g,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
2,g,25,g,NaN,,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
3,g,367,g,g,,mg,mg,,,mg,...,g,g,g,g,,,g,,,g
4,g,144,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8784,g,125,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8785,g,206,g,g,mg,mg,,mcg,mcg,mg,...,g,g,g,g,mg,,g,,,g
8786,g,277,g,g,mg,mg,,mcg,mcg,mg,...,g,g,g,g,mg,,g,,,g
8787,g,121,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8788,g,121,g,g,mg,mg,mg,mcg,mcg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [38]:
units.info(False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 75 entries, serving_size to water
dtypes: int64(2), object(73)
memory usage: 5.0+ MB

In [39]:
units = units.replace('',np.nan).dropna()

In [40]:
units.info()

<class 'pandas.core.frame.DataFrame'>
Index: 113 entries, 24 to 8737
Data columns (total 75 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   serving_size                 113 non-null    object
 1   calories                     113 non-null    int64
 2   total_fat                    113 non-null    object
 3   saturated_fat                113 non-null    object
 4   cholesterol                  113 non-null    object
 5   sodium                       113 non-null    object
 6   choline                      113 non-null    object
 7   folate                       113 non-null    object
 8   folic_acid                   113 non-null    object
 9   niacin                       113 non-null    object
 10  pantothenic_acid             113 non-null    object
 11  riboflavin                   113 non-null    object
 12  thiamin                      113 non-null    object
 13  vitamin_a                    113 non-null    object
 14  vitamin_a_rae                113 non-null    object
 15  carotene_alpha               113 non-null    object
 16  carotene_beta                113 non-null    object
 17  cryptoxanthin_beta           113 non-null    object
 18  lutein_zeaxanthin            113 non-null    object
 19  lucopene                     113 non-null    int64
 20  vitamin_b12                  113 non-null    object
 21  vitamin_b6                   113 non-null    object
 22  vitamin_c                    113 non-null    object
 23  vitamin_d                    113 non-null    object
 24  vitamin_e                    113 non-null    object
 25  tocopherol_alpha             113 non-null    object
 26  vitamin_k                    113 non-null    object
 27  calcium                      113 non-null    object
 28  copper                       113 non-null    object
 29  irom                         113 non-null    object
 30  magnesium                    113 non-null    object
 31  manganese                    113 non-null    object
 32  phosphorous                  113 non-null    object
 33  potassium                    113 non-null    object
 34  selenium                     113 non-null    object
 35  zink                         113 non-null    object
 36  protein                      113 non-null    object
 37  alanine                      113 non-null    object
 38  arginine                     113 non-null    object
 39  aspartic_acid                113 non-null    object
 40  cystine                      113 non-null    object
 41  glutamic_acid                113 non-null    object
 42  glycine                      113 non-null    object
 43  histidine                    113 non-null    object
 44  hydroxyproline               113 non-null    object
 45  isoleucine                   113 non-null    object
 46  leucine                      113 non-null    object
 47  lysine                       113 non-null    object
 48  methionine                   113 non-null    object
 49  phenylalanine                113 non-null    object
 50  proline                      113 non-null    object
 51  serine                       113 non-null    object
 52  threonine                    113 non-null    object
 53  tryptophan                   113 non-null    object
 54  tyrosine                     113 non-null    object
 55  valine                       113 non-null    object
 56  carbohydrate                 113 non-null    object
 57  fiber                        113 non-null    object
 58  sugars                       113 non-null    object
 59  fructose                     113 non-null    object
 60  galactose                    113 non-null    object
 61  glucose                      113 non-null    object
 62  lactose                      113 non-null    object
 63  maltose                      113 non-null    object
 64  sucrose                      113 non-null    object
 65  fat                          113 non-null    object
 66  saturated_fatty_acids        113 non-null    object
 67  monounsaturated_fatty_acids  113 non-null    object
 68  polyunsaturated_fatty_acids  113 non-null    object
 69  fatty_acids_total_trans      113 non-null    object
 70  alcohol                      113 non-null    object
 71  ash                          113 non-null    object
 72  caffeine                     113 non-null    object
 73  theobromine                  113 non-null    object
 74  water                        113 non-null    object
dtypes: int64(2), object(73)
memory usage: 67.1+ KB

In [41]:
# Drop type(int) colms
units = units.drop(['calories','lucopene'],axis=1)
units

,serving_size,total_fat,saturated_fat,cholesterol,sodium,choline,folate,folic_acid,niacin,pantothenic_acid,...,fat,saturated_fatty_acids,monounsaturated_fatty_acids,polyunsaturated_fatty_acids,fatty_acids_total_trans,alcohol,ash,caffeine,theobromine,water
24,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
70,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
165,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
210,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
536,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8079,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8100,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8399,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8651,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g
8737,g,g,g,mg,mg,mg,mcg,mcg,mg,mg,...,g,g,g,g,mg,g,g,mg,mg,g

In [42]:
units=units.iloc[0,:]

In [43]:
units

serving_size      g
total_fat         g
saturated_fat     g
cholesterol      mg
sodium           mg
                 ..
alcohol           g
ash               g
caffeine         mg
theobromine      mg
water             g
Name: 24, Length: 73, dtype: object

In [44]:
col_with_units= {}
for i in units.index:
    # print(i,": ",units[i])
    col_with_units[i]=i+'_'+units[i]
col_with_units

{'serving_size': 'serving_size_g',
 'total_fat': 'total_fat_g',
 'saturated_fat': 'saturated_fat_g',
 'cholesterol': 'cholesterol_mg',
 'sodium': 'sodium_mg',
 'choline': 'choline_mg',
 'folate': 'folate_mcg',
 'folic_acid': 'folic_acid_mcg',
 'niacin': 'niacin_mg',
 'pantothenic_acid': 'pantothenic_acid_mg',
 'riboflavin': 'riboflavin_mg',
 'thiamin': 'thiamin_mg',
 'vitamin_a': 'vitamin_a_IU',
 'vitamin_a_rae': 'vitamin_a_rae_mcg',
 'carotene_alpha': 'carotene_alpha_mcg',
 'carotene_beta': 'carotene_beta_mcg',
 'cryptoxanthin_beta': 'cryptoxanthin_beta_mcg',
 'lutein_zeaxanthin': 'lutein_zeaxanthin_mcg',
 'vitamin_b12': 'vitamin_b12_mcg',
 'vitamin_b6': 'vitamin_b6_mg',
 'vitamin_c': 'vitamin_c_mg',
 'vitamin_d': 'vitamin_d_IU',
 'vitamin_e': 'vitamin_e_mg',
 'tocopherol_alpha': 'tocopherol_alpha_mg',
 'vitamin_k': 'vitamin_k_mcg',
 'calcium': 'calcium_mg',
 'copper': 'copper_mg',
 'irom': 'irom_mg',
 'magnesium': 'magnesium_mg',
 'manganese': 'manganese_mg',
 'phosphorous': 'phosphorous_mg',
 'potassium': 'potassium_mg',
 'selenium': 'selenium_mcg',
 'zink': 'zink_mg',
 'protein': 'protein_g',
 'alanine': 'alanine_g',
 'arginine': 'arginine_g',
 'aspartic_acid': 'aspartic_acid_g',
 'cystine': 'cystine_g',
 'glutamic_acid': 'glutamic_acid_g',
 'glycine': 'glycine_g',
 'histidine': 'histidine_g',
 'hydroxyproline': 'hydroxyproline_g',
 'isoleucine': 'isoleucine_g',
 'leucine': 'leucine_g',
 'lysine': 'lysine_g',
 'methionine': 'methionine_g',
 'phenylalanine': 'phenylalanine_g',
 'proline': 'proline_g',
 'serine': 'serine_g',
 'threonine': 'threonine_g',
 'tryptophan': 'tryptophan_g',
 'tyrosine': 'tyrosine_g',
 'valine': 'valine_g',
 'carbohydrate': 'carbohydrate_g',
 'fiber': 'fiber_g',
 'sugars': 'sugars_g',
 'fructose': 'fructose_g',
 'galactose': 'galactose_g',
 'glucose': 'glucose_g',
 'lactose': 'lactose_g',
 'maltose': 'maltose_g',
 'sucrose': 'sucrose_g',
 'fat': 'fat_g',
 'saturated_fatty_acids': 'saturated_fatty_acids_g',
 'monounsaturated_fatty_acids': 'monounsaturated_fatty_acids_g',
 'polyunsaturated_fatty_acids': 'polyunsaturated_fatty_acids_g',
 'fatty_acids_total_trans': 'fatty_acids_total_trans_mg',
 'alcohol': 'alcohol_g',
 'ash': 'ash_g',
 'caffeine': 'caffeine_mg',
 'theobromine': 'theobromine_mg',
 'water': 'water_g'}

In [45]:
df_nu = df.rename(columns=col_with_units)

In [46]:
df_nu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Data columns (total 76 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           8789 non-null   object
 1   serving_size_g                 8789 non-null   object
 2   calories                       8789 non-null   int64
 3   total_fat_g                    8789 non-null   object
 4   saturated_fat_g                7199 non-null   object
 5   cholesterol_mg                 8789 non-null   object
 6   sodium_mg                      8789 non-null   object
 7   choline_mg                     8789 non-null   object
 8   folate_mcg                     8789 non-null   object
 9   folic_acid_mcg                 8789 non-null   object
 10  niacin_mg                      8789 non-null   object
 11  pantothenic_acid_mg            8789 non-null   object
 12  riboflavin_mg                  8789 non-null   object
 13  thiamin_mg                     8789 non-null   object
 14  vitamin_a_IU                   8789 non-null   object
 15  vitamin_a_rae_mcg              8789 non-null   object
 16  carotene_alpha_mcg             8789 non-null   object
 17  carotene_beta_mcg              8789 non-null   object
 18  cryptoxanthin_beta_mcg         8789 non-null   object
 19  lutein_zeaxanthin_mcg          8789 non-null   object
 20  lucopene                       8789 non-null   int64
 21  vitamin_b12_mcg                8789 non-null   object
 22  vitamin_b6_mg                  8789 non-null   object
 23  vitamin_c_mg                   8789 non-null   object
 24  vitamin_d_IU                   8789 non-null   object
 25  vitamin_e_mg                   8789 non-null   object
 26  tocopherol_alpha_mg            8789 non-null   object
 27  vitamin_k_mcg                  8789 non-null   object
 28  calcium_mg                     8789 non-null   object
 29  copper_mg                      8789 non-null   object
 30  irom_mg                        8789 non-null   object
 31  magnesium_mg                   8789 non-null   object
 32  manganese_mg                   8789 non-null   object
 33  phosphorous_mg                 8789 non-null   object
 34  potassium_mg                   8789 non-null   object
 35  selenium_mcg                   8789 non-null   object
 36  zink_mg                        8789 non-null   object
 37  protein_g                      8789 non-null   object
 38  alanine_g                      8789 non-null   object
 39  arginine_g                     8789 non-null   object
 40  aspartic_acid_g                8789 non-null   object
 41  cystine_g                      8789 non-null   object
 42  glutamic_acid_g                8789 non-null   object
 43  glycine_g                      8789 non-null   object
 44  histidine_g                    8789 non-null   object
 45  hydroxyproline_g               8789 non-null   object
 46  isoleucine_g                   8789 non-null   object
 47  leucine_g                      8789 non-null   object
 48  lysine_g                       8789 non-null   object
 49  methionine_g                   8789 non-null   object
 50  phenylalanine_g                8789 non-null   object
 51  proline_g                      8789 non-null   object
 52  serine_g                       8789 non-null   object
 53  threonine_g                    8789 non-null   object
 54  tryptophan_g                   8789 non-null   object
 55  tyrosine_g                     8789 non-null   object
 56  valine_g                       8789 non-null   object
 57  carbohydrate_g                 8789 non-null   object
 58  fiber_g                        8789 non-null   object
 59  sugars_g                       8789 non-null   object
 60  fructose_g                     8789 non-null   object
 61  galactose_g                    8789 non-null   object
 62  glucose_g                      8789 non-null   object
 63  lactose_g                      8789 non-null   object
 64  maltose_g                      8789 non-null   object
 65  sucrose_g                      8789 non-null   object
 66  fat_g                          8789 non-null   object
 67  saturated_fatty_acids_g        8789 non-null   object
 68  monounsaturated_fatty_acids_g  8789 non-null   object
 69  polyunsaturated_fatty_acids_g  8789 non-null   object
 70  fatty_acids_total_trans_mg     8789 non-null   object
 71  alcohol_g                      8789 non-null   object
 72  ash_g                          8789 non-null   object
 73  caffeine_mg                    8789 non-null   object
 74  theobromine_mg                 8789 non-null   object
 75  water_g                        8789 non-null   object
dtypes: int64(2), object(74)
memory usage: 5.1+ MB

In [47]:
len(df_nu.columns)

76

In [48]:
len(df.columns)

76

## 27. Part III Removing Units From the Values

In [49]:
df_nu.head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
0,Cornstarch,100 g,381,0.1g,NaN,0,9.00 mg,0.4 mg,0.00 mcg,0.00 mcg,...,0.05 g,0.009 g,0.016 g,0.025 g,0.00 mg,0.0 g,0.09 g,0.00 mg,0.00 mg,8.32 g
1,"Nuts, pecans",100 g,691,72g,6.2g,0,0.00 mg,40.5 mg,22.00 mcg,0.00 mcg,...,71.97 g,6.180 g,40.801 g,21.614 g,0.00 mg,0.0 g,1.49 g,0.00 mg,0.00 mg,3.52 g
2,"Eggplant, raw",100 g,25,0.2g,NaN,0,2.00 mg,6.9 mg,22.00 mcg,0.00 mcg,...,0.18 g,0.034 g,0.016 g,0.076 g,0.00 mg,0.0 g,0.66 g,0.00 mg,0.00 mg,92.30 g
3,"Teff, uncooked",100 g,367,2.4g,0.4g,0,12.00 mg,13.1 mg,0,0,...,2.38 g,0.449 g,0.589 g,1.071 g,0,0,2.37 g,0,0,8.82 g
4,"Sherbet, orange",100 g,144,2g,1.2g,1mg,46.00 mg,7.7 mg,4.00 mcg,0.00 mcg,...,2.00 g,1.160 g,0.530 g,0.080 g,1.00 mg,0.0 g,0.40 g,0.00 mg,0.00 mg,66.10 g

In [50]:
first_col = df_nu.iloc[:,1:].replace('[a-zA-Z\s]','',regex=True).head().iloc[0,:]
for i in first_col.index:
    print(first_col[i])

100
381
0.1
nan
0
9.00
0.4
0.00
0.00
0.000
0.000
0.000
0.000
0.00
0.00
0.00
0.00
0.00
0.00
0
0.00
0.000
0.0
0.00
0.00
0.00
0.0
2.00
0.050
0.47
3.00
0.053
13.00
3.00
2.8
0.06
0.26
0.019
0.012
0.020
0.006
0.053
0.009
0.008
0
0.010
0.036
0.006
0.006
0.013
0.024
0.012
0.009
0.001
0.010
0.014
91.27
0.9
0.00
0
0
0
0
0
0
0.05
0.009
0.016
0.025
0.00
0.0
0.09
0.00
0.00
8.32

In [51]:
df_nu.iloc[:,1:]=df_nu.iloc[:,1:].replace('[a-zA-Z\s]','',regex=True)
df_nu.head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
0,Cornstarch,100,381,0.1,NaN,0,9.00,0.4,0.00,0.00,...,0.05,0.009,0.016,0.025,0.00,0.0,0.09,0.00,0.00,8.32
1,"Nuts, pecans",100,691,72,6.2,0,0.00,40.5,22.00,0.00,...,71.97,6.180,40.801,21.614,0.00,0.0,1.49,0.00,0.00,3.52
2,"Eggplant, raw",100,25,0.2,NaN,0,2.00,6.9,22.00,0.00,...,0.18,0.034,0.016,0.076,0.00,0.0,0.66,0.00,0.00,92.30
3,"Teff, uncooked",100,367,2.4,0.4,0,12.00,13.1,0,0,...,2.38,0.449,0.589,1.071,0,0,2.37,0,0,8.82
4,"Sherbet, orange",100,144,2,1.2,1,46.00,7.7,4.00,0.00,...,2.00,1.160,0.530,0.080,1.00,0.0,0.40,0.00,0.00,66.10

In [52]:
df_nu.info(False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 76 entries, name to water_g
dtypes: int64(2), object(74)
memory usage: 5.1+ MB

In [53]:
temp = df_nu.iloc[:,1:].astype(float)
temp.info(False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Columns: 75 entries, serving_size_g to water_g
dtypes: float64(75)
memory usage: 5.0 MB

In [54]:
df_nu = pd.concat([df_nu.iloc[:,0],temp],axis=1)

In [55]:
df_nu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8789 entries, 0 to 8788
Data columns (total 76 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   name                           8789 non-null   object
 1   serving_size_g                 8789 non-null   float64
 2   calories                       8789 non-null   float64
 3   total_fat_g                    8789 non-null   float64
 4   saturated_fat_g                7199 non-null   float64
 5   cholesterol_mg                 8789 non-null   float64
 6   sodium_mg                      8789 non-null   float64
 7   choline_mg                     8789 non-null   float64
 8   folate_mcg                     8789 non-null   float64
 9   folic_acid_mcg                 8789 non-null   float64
 10  niacin_mg                      8789 non-null   float64
 11  pantothenic_acid_mg            8789 non-null   float64
 12  riboflavin_mg                  8789 non-null   float64
 13  thiamin_mg                     8789 non-null   float64
 14  vitamin_a_IU                   8789 non-null   float64
 15  vitamin_a_rae_mcg              8789 non-null   float64
 16  carotene_alpha_mcg             8789 non-null   float64
 17  carotene_beta_mcg              8789 non-null   float64
 18  cryptoxanthin_beta_mcg         8789 non-null   float64
 19  lutein_zeaxanthin_mcg          8789 non-null   float64
 20  lucopene                       8789 non-null   float64
 21  vitamin_b12_mcg                8789 non-null   float64
 22  vitamin_b6_mg                  8789 non-null   float64
 23  vitamin_c_mg                   8789 non-null   float64
 24  vitamin_d_IU                   8789 non-null   float64
 25  vitamin_e_mg                   8789 non-null   float64
 26  tocopherol_alpha_mg            8789 non-null   float64
 27  vitamin_k_mcg                  8789 non-null   float64
 28  calcium_mg                     8789 non-null   float64
 29  copper_mg                      8789 non-null   float64
 30  irom_mg                        8789 non-null   float64
 31  magnesium_mg                   8789 non-null   float64
 32  manganese_mg                   8789 non-null   float64
 33  phosphorous_mg                 8789 non-null   float64
 34  potassium_mg                   8789 non-null   float64
 35  selenium_mcg                   8789 non-null   float64
 36  zink_mg                        8789 non-null   float64
 37  protein_g                      8789 non-null   float64
 38  alanine_g                      8789 non-null   float64
 39  arginine_g                     8789 non-null   float64
 40  aspartic_acid_g                8789 non-null   float64
 41  cystine_g                      8789 non-null   float64
 42  glutamic_acid_g                8789 non-null   float64
 43  glycine_g                      8789 non-null   float64
 44  histidine_g                    8789 non-null   float64
 45  hydroxyproline_g               8789 non-null   float64
 46  isoleucine_g                   8789 non-null   float64
 47  leucine_g                      8789 non-null   float64
 48  lysine_g                       8789 non-null   float64
 49  methionine_g                   8789 non-null   float64
 50  phenylalanine_g                8789 non-null   float64
 51  proline_g                      8789 non-null   float64
 52  serine_g                       8789 non-null   float64
 53  threonine_g                    8789 non-null   float64
 54  tryptophan_g                   8789 non-null   float64
 55  tyrosine_g                     8789 non-null   float64
 56  valine_g                       8789 non-null   float64
 57  carbohydrate_g                 8789 non-null   float64
 58  fiber_g                        8789 non-null   float64
 59  sugars_g                       8789 non-null   float64
 60  fructose_g                     8789 non-null   float64
 61  galactose_g                    8789 non-null   float64
 62  glucose_g                      8789 non-null   float64
 63  lactose_g                      8789 non-null   float64
 64  maltose_g                      8789 non-null   float64
 65  sucrose_g                      8789 non-null   float64
 66  fat_g                          8789 non-null   float64
 67  saturated_fatty_acids_g        8789 non-null   float64
 68  monounsaturated_fatty_acids_g  8789 non-null   float64
 69  polyunsaturated_fatty_acids_g  8789 non-null   float64
 70  fatty_acids_total_trans_mg     8789 non-null   float64
 71  alcohol_g                      8789 non-null   float64
 72  ash_g                          8789 non-null   float64
 73  caffeine_mg                    8789 non-null   float64
 74  theobromine_mg                 8789 non-null   float64
 75  water_g                        8789 non-null   float64
dtypes: float64(75), object(1)
memory usage: 5.1+ MB

## 28. Filtering in 2D --> Apply only in labels

In [82]:
df_nu.head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
0,Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,...,0.05,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32
1,"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,...,71.97,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52
2,"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30
3,"Teff, uncooked",100.0,367.0,2.4,0.4,0.0,12.0,13.1,0.0,0.0,...,2.38,0.449,0.589,1.071,0.0,0.0,2.37,0.0,0.0,8.82
4,"Sherbet, orange",100.0,144.0,2.0,1.2,1.0,46.0,7.7,4.0,0.0,...,2.00,1.160,0.530,0.080,1.0,0.0,0.40,0.0,0.0,66.10

In [83]:
df_nu.filter(items=['name','calories','cholesterol_mg','total_fat_g','choline_mg',], axis=1)\
    .filter(items=[0,9,1,8], axis=0)

                 name  calories  cholesterol_mg  total_fat_g  choline_mg
0          Cornstarch     381.0             0.0          0.1         0.4
9  Vegetarian fillets     290.0             0.0         18.0        82.0
1        Nuts, pecans     691.0             0.0         72.0        40.5
8   Cheese, camembert     300.0            72.0         24.0        15.4

#### You can apply this filter method on lables only not in data

In [84]:
    df_nu.filter(like="Octopus", axis=0)

Empty DataFrame
Columns: [name, serving_size_g, calories, total_fat_g, saturated_fat_g, cholesterol_mg, sodium_mg, choline_mg, folate_mcg, folic_acid_mcg, niacin_mg, pantothenic_acid_mg, riboflavin_mg, thiamin_mg, vitamin_a_IU, vitamin_a_rae_mcg, carotene_alpha_mcg, carotene_beta_mcg, cryptoxanthin_beta_mcg, lutein_zeaxanthin_mcg, lucopene, vitamin_b12_mcg, vitamin_b6_mg, vitamin_c_mg, vitamin_d_IU, vitamin_e_mg, tocopherol_alpha_mg, vitamin_k_mcg, calcium_mg, copper_mg, irom_mg, magnesium_mg, manganese_mg, phosphorous_mg, potassium_mg, selenium_mcg, zink_mg, protein_g, alanine_g, arginine_g, aspartic_acid_g, cystine_g, glutamic_acid_g, glycine_g, histidine_g, hydroxyproline_g, isoleucine_g, leucine_g, lysine_g, methionine_g, phenylalanine_g, proline_g, serine_g, threonine_g, tryptophan_g, tyrosine_g, valine_g, carbohydrate_g, fiber_g, sugars_g, fructose_g, galactose_g, glucose_g, lactose_g, maltose_g, sucrose_g, fat_g, saturated_fatty_acids_g, monounsaturated_fatty_acids_g, polyunsaturated_fatty_acids_g, fatty_acids_total_trans_mg, alcohol_g, ash_g, caffeine_mg, theobromine_mg, water_g]
Index: []

[0 rows x 76 columns]

In [85]:
df.filter(like="Octopus",axis=0)

Empty DataFrame
Columns: [name, serving_size, calories, total_fat, saturated_fat, cholesterol, sodium, choline, folate, folic_acid, niacin, pantothenic_acid, riboflavin, thiamin, vitamin_a, vitamin_a_rae, carotene_alpha, carotene_beta, cryptoxanthin_beta, lutein_zeaxanthin, lucopene, vitamin_b12, vitamin_b6, vitamin_c, vitamin_d, vitamin_e, tocopherol_alpha, vitamin_k, calcium, copper, irom, magnesium, manganese, phosphorous, potassium, selenium, zink, protein, alanine, arginine, aspartic_acid, cystine, glutamic_acid, glycine, histidine, hydroxyproline, isoleucine, leucine, lysine, methionine, phenylalanine, proline, serine, threonine, tryptophan, tyrosine, valine, carbohydrate, fiber, sugars, fructose, galactose, glucose, lactose, maltose, sucrose, fat, saturated_fatty_acids, monounsaturated_fatty_acids, polyunsaturated_fatty_acids, fatty_acids_total_trans, alcohol, ash, caffeine, theobromine, water]
Index: []

[0 rows x 76 columns]

In [86]:
df_nu[df_nu.name == "Octopus (Alaska Native)"]

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
1265,Octopus (Alaska Native),100.0,56.0,0.8,0.2,41.0,0.0,0.0,0.0,0.0,...,0.8,0.2,0.0,0.2,41.0,0.0,1.5,0.0,0.0,84.0

## 29. DF Sorting

In [98]:
df_nu.head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
0,Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,...,0.05,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32
1,"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,...,71.97,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52
2,"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30
3,"Teff, uncooked",100.0,367.0,2.4,0.4,0.0,12.0,13.1,0.0,0.0,...,2.38,0.449,0.589,1.071,0.0,0.0,2.37,0.0,0.0,8.82
4,"Sherbet, orange",100.0,144.0,2.0,1.2,1.0,46.0,7.7,4.0,0.0,...,2.00,1.160,0.530,0.080,1.0,0.0,0.40,0.0,0.0,66.10

In [99]:
df_nu.sort_values(by=['serving_size_g'], ascending = False).head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
0,Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,...,0.05,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32
5863,"Wheat flour, calcium-fortified, enriched, all-...",100.0,364.0,1.0,0.2,0.0,2.0,0.0,183.0,154.0,...,0.98,0.155,0.087,0.413,0.0,0.0,0.47,0.0,0.0,11.92
5857,"Rice, dry, enriched, precooked or instant, lon...",100.0,380.0,0.9,0.2,0.0,10.0,6.1,275.0,273.0,...,0.94,0.152,0.144,0.219,0.0,0.0,0.53,0.0,0.0,8.38
5858,"Grapefruit, solids and liquids, water pack, ca...",100.0,36.0,0.1,NaN,0.0,2.0,5.1,9.0,0.0,...,0.10,0.014,0.014,0.024,0.0,0.0,0.32,0.0,0.0,89.85
5859,"Nuts, raw (liquid expressed from grated meat),...",100.0,330.0,35.0,31.0,0.0,4.0,0.0,23.0,0.0,...,34.68,30.753,1.475,0.379,0.0,0.0,1.15,0.0,0.0,53.90

In [100]:
df_nu.filter(items=['name','serving_size_g','total_fat_g'],axis=1)\
    .sort_values(by=['serving_size_g','total_fat_g'], ascending = [True,False])

,name,serving_size_g,total_fat_g
67,"Oil, soybean lecithin",100.0,100.0
192,"Oil, corn and canola",100.0,100.0
212,"Oil, ucuhuba butter",100.0,100.0
223,"Oil, apricot kernel",100.0,100.0
256,"Fish oil, cod liver",100.0,100.0
...,...,...,...
8491,"Gelatin desserts, vitamin C, sodium, potassium...",100.0,0.0
8549,"Beverages, added vitamin C, with low-calorie s...",100.0,0.0
8558,"Beverages, mineral bottled water, naturally sp...",100.0,0.0
8655,"Beverages, prepared with water, frozen concent...",100.0,0.0
8694,"Carbonated beverage, without caffeine, with so...",100.0,0.0

## 30. Using Series between() with DF

In [101]:
df_nu.head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
0,Cornstarch,100.0,381.0,0.1,NaN,0.0,9.0,0.4,0.0,0.0,...,0.05,0.009,0.016,0.025,0.0,0.0,0.09,0.0,0.0,8.32
1,"Nuts, pecans",100.0,691.0,72.0,6.2,0.0,0.0,40.5,22.0,0.0,...,71.97,6.180,40.801,21.614,0.0,0.0,1.49,0.0,0.0,3.52
2,"Eggplant, raw",100.0,25.0,0.2,NaN,0.0,2.0,6.9,22.0,0.0,...,0.18,0.034,0.016,0.076,0.0,0.0,0.66,0.0,0.0,92.30
3,"Teff, uncooked",100.0,367.0,2.4,0.4,0.0,12.0,13.1,0.0,0.0,...,2.38,0.449,0.589,1.071,0.0,0.0,2.37,0.0,0.0,8.82
4,"Sherbet, orange",100.0,144.0,2.0,1.2,1.0,46.0,7.7,4.0,0.0,...,2.00,1.160,0.530,0.080,1.0,0.0,0.40,0.0,0.0,66.10

In [106]:
df_nu.loc[:,'calories'].between(100,200)

0       False
1       False
2       False
3       False
4        True
        ...
8784     True
8785    False
8786    False
8787     True
8788     True
Name: calories, Length: 8789, dtype: bool

In [118]:
df_nu[df_nu.loc[:,'calories'].between(100,200)].head()

,name,serving_size_g,calories,total_fat_g,saturated_fat_g,cholesterol_mg,sodium_mg,choline_mg,folate_mcg,folic_acid_mcg,...,fat_g,saturated_fatty_acids_g,monounsaturated_fatty_acids_g,polyunsaturated_fatty_acids_g,fatty_acids_total_trans_mg,alcohol_g,ash_g,caffeine_mg,theobromine_mg,water_g
4,"Sherbet, orange",100.0,144.0,2.0,1.2,1.0,46.0,7.7,4.0,0.0,...,2.00,1.160,0.530,0.080,1.0,0.0,0.40,0.0,0.0,66.10
15,"Quail, raw, meat only",100.0,134.0,4.5,1.3,70.0,51.0,0.0,7.0,0.0,...,4.53,1.320,1.280,1.170,70.0,0.0,1.32,0.0,0.0,70.03
18,"Winged bean tuber, raw",100.0,148.0,0.9,0.2,0.0,35.0,0.0,19.0,0.0,...,0.90,0.222,0.234,0.174,0.0,0.0,2.00,0.0,0.0,57.40
19,"Salami, turkey, cooked",100.0,172.0,9.2,2.8,76.0,1107.0,53.1,10.0,0.0,...,9.21,2.783,3.172,2.466,76.0,0.0,1.68,0.0,0.0,68.80
21,"Nuts, raw, ginkgo nuts",100.0,182.0,1.7,0.3,0.0,7.0,0.0,54.0,0.0,...,1.68,0.319,0.619,0.618,0.0,0.0,1.20,0.0,0.0,55.20

In [116]:
df_nu[df_nu.loc[:,'calories'].between(100,200)]\
    .filter(items=['name','calories'],axis=1)\
    .sort_values(by=['calories','name'])\
    .head(50)

                                                   name  calories
4036      Babyfood, strained, without vitamin c, prunes     100.0
2527               Chili with beans, microwavable bowls     100.0
2725         Crustaceans, canned, mixed species, shrimp     100.0
1582                  Fish, raw, mixed species, snapper     100.0
4649  Ham, packaged (96% fat free, water added), sliced     100.0
2775       KASHI, Frozen Entree, Chicken Pasta Pomodoro     100.0
932                         Pie fillings, canned, apple     100.0
5104  Pork, raw, kidneys, variety meats and by-produ...     100.0
5160  Pork, raw, spleen, variety meats and by-produc...     100.0
5379  Potatoes, with salt, flesh, cooked in skin, mi...     100.0
4974  Potatoes, without salt, flesh, cooked in skin,...     100.0
85                                SILK Original Creamer     100.0
3300          Soup, condensed, canned, chicken mushroom     100.0
4742  Spaghetti, canned, with meatballs in tomato sauce     100.0
3877     Sweet potato, with salt, baked, cooked, frozen     100.0
4721  Sweet potato, without salt, baked, cooked, frozen     100.0
1435                 Turkey breast, prepackaged, sliced     100.0
4777  Whipped cream substitute, made from powdered m...     100.0
7387  Beverages, fortified, ready to drink, milk and...     101.0
5188  Beverages, peanut flavor, canned, Meal supplem...     101.0
669                                              Catsup     101.0
282                                  Catsup, low sodium     101.0
5580  Crustaceans, made from surimi, imitation, mixe...     101.0
2459              Custard-apple, raw, (bullock's-heart)     101.0
3654    KASHI Pesto Pasta Primavera, unprepared, frozen     101.0
3444   Lamb, raw, spleen, variety meats and by-products     101.0
4743  Lasagna with meat & sauce, frozen entree, low-fat     101.0
3462   Lentils, with salt, stir-fried, cooked, sprouted     101.0
4441  Lentils, without salt, stir-fried, cooked, spr...     101.0
6627  Plums, solids and liquids, extra heavy syrup p...     101.0
4895  Puddings, prepared with 2% milk, regular, dry ...     101.0
4783  Puddings, prepared with 2% milk, regular, dry ...     101.0
2629                Stew, dumpling with mutton (Navajo)     101.0
837                        Sweet potato, mashed, canned     101.0
604                                        Teff, cooked     101.0
572                                        Thyme, fresh     101.0
6612  Turkey from whole, raw, with added solution, m...     101.0
3699    Turkey, smoked, low fat, and beef sausage, pork     101.0
3442   Veal, raw, thymus, variety meats and by-products     101.0
390                                   Wild rice, cooked     101.0
1348                             Amaranth grain, cooked     102.0
6459  Cherries, solids and liquids, extra heavy syru...     102.0
72                                Emu, raw, flat fillet     102.0
2614                Fish, dry heat, cooked, ocean, pout     102.0
94                                Game meat, raw, moose     102.0
4365  Mollusks, moist heat, cooked, wild, eastern, o...     102.0
2910        OLIVE GARDEN, spaghetti with pomodoro sauce     102.0
4929  Salad dressing, reduced fat, commercial, itali...     102.0
3371           Sea lion, heart (Alaska Native), Steller     102.0
6376  Turkey, raw, with added solution, meat only, f...     102.0