In [1]:
import pandas as pd
import numpy as np

In [2]:
brent = pd.read_csv(r'https://andybek.com/pandas-oil')
brent.head()

        Date  Price
0  04-Jan-00  23.95
1  05-Jan-00  23.72
2  06-Jan-00  23.55
3  07-Jan-00  23.35
4  10-Jan-00  22.77

In [3]:
pd.to_datetime(brent.Date,format='%d-%b-%y')

0      2000-01-04
1      2000-01-05
2      2000-01-06
3      2000-01-07
4      2000-01-10
          ...
5011   2019-09-24
5012   2019-09-25
5013   2019-09-26
5014   2019-09-27
5015   2019-09-30
Name: Date, Length: 5016, dtype: datetime64[ns]

In [6]:
brent.Date=pd.to_datetime(brent.Date,format='%d-%b-%y')
brent.set_index('Date',inplace=True)

In [7]:
brent.head()

            Price
Date
2000-01-04  23.95
2000-01-05  23.72
2000-01-06  23.55
2000-01-07  23.35
2000-01-10  22.77

### 14. DateTimeIndex Attribute Accessors

In [8]:
brent.index

DatetimeIndex(['2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07',
               '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13',
               '2000-01-14', '2000-01-17',
               ...
               '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20',
               '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26',
               '2019-09-27', '2019-09-30'],
              dtype='datetime64[ns]', name='Date', length=5016, freq=None)

In [9]:
brent.index.month

Index([1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       ...
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
      dtype='int32', name='Date', length=5016)

In [10]:
brent.index.year

Index([2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
       ...
       2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019],
      dtype='int32', name='Date', length=5016)

In [13]:
brent.index.day

Index([ 4,  5,  6,  7, 10, 11, 12, 13, 14, 17,
       ...
       17, 18, 19, 20, 23, 24, 25, 26, 27, 30],
      dtype='int32', name='Date', length=5016)

In [15]:
brent.index.day_name()

Index(['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Monday',
       ...
       'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday', 'Tuesday',
       'Wednesday', 'Thursday', 'Friday', 'Monday'],
      dtype='object', name='Date', length=5016)

##### Q: Which day has registered the lowest brent prince, on average, in last 19 years?

In [17]:
temp = brent
temp['Dayname'] = temp.index.day_name()
temp.head()

            Price    Dayname
Date
2000-01-04  23.95    Tuesday
2000-01-05  23.72  Wednesday
2000-01-06  23.55   Thursday
2000-01-07  23.35     Friday
2000-01-10  22.77     Monday

In [22]:
temp.loc['2011':]

            Price    Dayname
Date
2011-01-03  95.82     Monday
2011-01-04  93.52    Tuesday
2011-01-05  95.07  Wednesday
2011-01-06  94.95   Thursday
2011-01-07  94.25     Friday
...           ...        ...
2019-09-24  64.13    Tuesday
2019-09-25  62.41  Wednesday
2019-09-26  62.08   Thursday
2019-09-27  62.48     Friday
2019-09-30  60.99     Monday

[2213 rows x 2 columns]

In [23]:
temp.Dayname.unique()

Index(['Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Monday'], dtype='object', name='Date')

In [27]:
temp.groupby('Dayname').mean().sort_values(by='Price')

               Price
Dayname
Monday     63.875348
Friday     64.317988
Tuesday    64.493895
Wednesday  64.495593
Thursday   64.581943

##### Q: Find the avg brent price in all leap year feb's.

In [28]:
brent.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5016 entries, 2000-01-04 to 2019-09-30
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Price    5016 non-null   float64
 1   Dayname  5016 non-null   object
dtypes: float64(1), object(1)
memory usage: 246.6+ KB

In [30]:
brent = brent.drop(columns='Dayname')
brent.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5016 entries, 2000-01-04 to 2019-09-30
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   5016 non-null   float64
dtypes: float64(1)
memory usage: 207.4 KB

In [31]:
brent.index.year

Index([2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000, 2000,
       ...
       2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019],
      dtype='int32', name='Date', length=5016)

##### soln --> worked not ;-(

In [32]:
brent['year'] = brent.index.year
brent.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5016 entries, 2000-01-04 to 2019-09-30
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   5016 non-null   float64
 1   year    5016 non-null   int32
dtypes: float64(1), int32(1)
memory usage: 227.0 KB

In [34]:
brent.groupby('year').count()

      Price
year
2000    253
2001    257
2002    255
2003    258
2004    261
2005    257
2006    255
2007    250
2008    253
2009    252
2010    252
2011    248
2012    249
2013    252
2014    254
2015    255
2016    255
2017    256
2018    252
2019    192

In [37]:
brent = brent.drop(columns='year')
brent.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 5016 entries, 2000-01-04 to 2019-09-30
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   5016 non-null   float64
dtypes: float64(1)
memory usage: 207.4 KB

##### soln --> which worked !!!

In [39]:
leap_year = brent.index.is_leap_year
feb_month = brent.index.month == 2
brent[leap_year & feb_month].mean()

Price    60.696634
dtype: float64

### 15. Creating Date Ranges

In [45]:
pd.date_range(start='10 may 2020', end='20 june 2021')

DatetimeIndex(['2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13',
               '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17',
               '2020-05-18', '2020-05-19',
               ...
               '2021-06-11', '2021-06-12', '2021-06-13', '2021-06-14',
               '2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18',
               '2021-06-19', '2021-06-20'],
              dtype='datetime64[ns]', length=407, freq='D')

In [47]:
pd.date_range('05/10/2020', '06/20/2021')

DatetimeIndex(['2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13',
               '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17',
               '2020-05-18', '2020-05-19',
               ...
               '2021-06-11', '2021-06-12', '2021-06-13', '2021-06-14',
               '2021-06-15', '2021-06-16', '2021-06-17', '2021-06-18',
               '2021-06-19', '2021-06-20'],
              dtype='datetime64[ns]', length=407, freq='D')

In [48]:
pd.date_range('05/10/2020', periods=10)

DatetimeIndex(['2020-05-10', '2020-05-11', '2020-05-12', '2020-05-13',
               '2020-05-14', '2020-05-15', '2020-05-16', '2020-05-17',
               '2020-05-18', '2020-05-19'],
              dtype='datetime64[ns]', freq='D')

In [50]:
# 10 weeks
pd.date_range('05/10/2020', periods=10, freq='W')

DatetimeIndex(['2020-05-10', '2020-05-17', '2020-05-24', '2020-05-31',
               '2020-06-07', '2020-06-14', '2020-06-21', '2020-06-28',
               '2020-07-05', '2020-07-12'],
              dtype='datetime64[ns]', freq='W-SUN')

In [51]:
# 10 weeks -- skip 1 week
pd.date_range('05/10/2020', periods=10, freq='2W')

DatetimeIndex(['2020-05-10', '2020-05-24', '2020-06-07', '2020-06-21',
               '2020-07-05', '2020-07-19', '2020-08-02', '2020-08-16',
               '2020-08-30', '2020-09-13'],
              dtype='datetime64[ns]', freq='2W-SUN')