### 3. Parse dates from the text

In [9]:
from datetime import datetime as dt
temp = dt.strptime('2020-04-10','%Y-%m-%d') # '%Y-%m-%d' this excat alphabetical case going to work
temp

datetime.datetime(2020, 4, 10, 0, 0)

In [10]:
temp.isoformat()

'2020-04-10T00:00:00'

In [11]:
temp.year

2020

In [12]:
temp.day

10

##### refer this '%Y-%m-%d' formate from here 
https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

In [13]:
# another ex.

In [16]:
try_this = 'feb 14 2052 6pm'
dt.strptime(try_this, '%b %d %Y %I%p')

datetime.datetime(2052, 2, 14, 18, 0)

### 4. Even Better dateutil

In [17]:
!pip show python-dateutil

Name: python-dateutil
Version: 2.9.0.post0
Summary: Extensions to the standard Python datetime module
Home-page: https://github.com/dateutil/dateutil
Author: Gustavo Niemeyer
Author-email: gustavo@niemeyer.net
License: Dual License
Location: C:\Users\Sultan Ali\anaconda3\Lib\site-packages
Requires: six
Required-by: aiobotocore, anaconda-client, arrow, botocore, holoviews, jupyter_client, matplotlib, pandas

In [18]:
!pip install python-dateutil

Requirement already satisfied: python-dateutil in C:\Users\Sultan Ali\anaconda3\Lib\site-packages (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\Sultan Ali\anaconda3\Lib\site-packages (from python-dateutil) (1.17.0)

In [19]:
from dateutil import parser

In [20]:
parser.parse('jan 21st 2000')

datetime.datetime(2000, 1, 21, 0, 0)

In [22]:
parser.parse('2006 june 5 at 5:30 am')

datetime.datetime(2006, 6, 5, 5, 30)

In [44]:
parser.parse('2006 jun 5 at 5pm and 30minutes')

datetime.datetime(2006, 6, 5, 17, 30)

In [45]:
parser.parse('12/04/25 4:30:10')

datetime.datetime(2025, 12, 4, 4, 30, 10)

### 5. From Datetime To String

In [47]:
temp2 = dt.now()
temp2

datetime.datetime(2026, 8, 29, 11, 34, 47, 463531)

In [50]:
temp2.strftime('%d/%m/%Y')

'29/08/2026'

### 7. The Pandas Timestamp

In [52]:
import pandas as pd
import numpy as np

In [53]:
pd.Timestamp('4th july of 2026')

Timestamp('2026-07-04 00:00:00')

In [55]:
pd.Timestamp('5/4/26')

Timestamp('2026-05-04 00:00:00')

In [56]:
pd.to_datetime('5/4/26', dayfirst=True) # dayfirst atribute make '5' as day

Timestamp('2026-04-05 00:00:00')

In [57]:
temp3 = pd.to_datetime('5/4/26', dayfirst=True) # dayfirst atribute make '5' as day

In [65]:
temp3.day

5

In [66]:
type(temp3)

pandas.Timestamp

In [67]:
temp3.days_in_month

30

In [63]:
pd.Timestamp('5/4/26').days_in_month

31

In [69]:
temp3.isoformat()

'2026-04-05T00:00:00'

In [70]:
temp3.isocalendar()

datetime.IsoCalendarDate(year=2026, week=14, weekday=7)

### 8. Our Dataset Brent Prices

https://andybek.com/pandas-oil

In [71]:
brent = pd.read_csv(r'https://andybek.com/pandas-oil')
brent.head()

        Date  Price
0  04-Jan-00  23.95
1  05-Jan-00  23.72
2  06-Jan-00  23.55
3  07-Jan-00  23.35
4  10-Jan-00  22.77

In [72]:
brent.info()

<class 'pandas.DataFrame'>
RangeIndex: 5016 entries, 0 to 5015
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    5016 non-null   str
 1   Price   5016 non-null   float64
dtypes: float64(1), str(1)
memory usage: 122.6 KB

### 9. Date Parsing And DatetimeIndex

In [77]:
brent.Date.astype(pd.Timestamp) # not going to work

TypeError: dtype '<class 'pandas.Timestamp'>' not understood

In [80]:
pd.to_datetime(brent.Date, format="%d-%b-%y")

0      2000-01-04
1      2000-01-05
2      2000-01-06
3      2000-01-07
4      2000-01-10
          ...
5011   2019-09-24
5012   2019-09-25
5013   2019-09-26
5014   2019-09-27
5015   2019-09-30
Name: Date, Length: 5016, dtype: datetime64[us]

In [91]:
brent.Date = pd.to_datetime(brent.Date, format="%d-%b-%y")
brent.info()

<class 'pandas.DataFrame'>
RangeIndex: 5016 entries, 0 to 5015
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    5016 non-null   datetime64[us]
 1   Price   5016 non-null   float64
dtypes: datetime64[us](1), float64(1)
memory usage: 78.5 KB

In [92]:
# set dates as index

In [93]:
brent.set_index('Date', inplace=True)

In [94]:
brent.head()

            Price
Date
2000-01-04  23.95
2000-01-05  23.72
2000-01-06  23.55
2000-01-07  23.35
2000-01-10  22.77

In [96]:
brent.index # This DatetimeIndex is diffent than Index

DatetimeIndex(['2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07',
               '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13',
               '2000-01-14', '2000-01-17',
               ...
               '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20',
               '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26',
               '2019-09-27', '2019-09-30'],
              dtype='datetime64[us]', name='Date', length=5016, freq=None)

In [98]:
pd.to_datetime(
    ['13/4/26','4/5/26'],
    format='%d/%m/%y',
    dayfirst=True
)

DatetimeIndex(['2026-04-13', '2026-05-04'], dtype='datetime64[us]', freq=None)

### 10. A Cool Shorcut read_csv() With parse_dates

In [99]:
pd.read_csv(r'https://andybek.com/pandas-oil',index_col=0)

           Price
Date
04-Jan-00  23.95
05-Jan-00  23.72
06-Jan-00  23.55
07-Jan-00  23.35
10-Jan-00  22.77
...          ...
24-Sep-19  64.13
25-Sep-19  62.41
26-Sep-19  62.08
27-Sep-19  62.48
30-Sep-19  60.99

[5016 rows x 1 columns]

In [100]:
pd.read_csv(r'https://andybek.com/pandas-oil',index_col=0)\
    .index

Index(['04-Jan-00', '05-Jan-00', '06-Jan-00', '07-Jan-00', '10-Jan-00',
       '11-Jan-00', '12-Jan-00', '13-Jan-00', '14-Jan-00', '17-Jan-00',
       ...
       '17-Sep-19', '18-Sep-19', '19-Sep-19', '20-Sep-19', '23-Sep-19',
       '24-Sep-19', '25-Sep-19', '26-Sep-19', '27-Sep-19', '30-Sep-19'],
      dtype='str', name='Date', length=5016)

In [102]:
pd.read_csv(
    r'https://andybek.com/pandas-oil',
    parse_dates=True,
    index_col=0
)\
    .index

C:\Users\Sultan Ali\AppData\Local\Temp\ipykernel_23036\2499632496.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  pd.read_csv(

DatetimeIndex(['2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07',
               '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13',
               '2000-01-14', '2000-01-17',
               ...
               '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20',
               '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26',
               '2019-09-27', '2019-09-30'],
              dtype='datetime64[us]', name='Date', length=5016, freq=None)

In [103]:
brent2 = pd.read_csv(
    r'https://andybek.com/pandas-oil',
    parse_dates=True,
    index_col=0
)
brent2.info()

C:\Users\Sultan Ali\AppData\Local\Temp\ipykernel_23036\3608517424.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  brent2 = pd.read_csv(

<class 'pandas.DataFrame'>
DatetimeIndex: 5016 entries, 2000-01-04 to 2019-09-30
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   5016 non-null   float64
dtypes: float64(1)
memory usage: 78.4 KB

### 11. Indexing Dates

In [104]:
brent.head()

            Price
Date
2000-01-04  23.95
2000-01-05  23.72
2000-01-06  23.55
2000-01-07  23.35
2000-01-10  22.77

In [105]:
brent.index

DatetimeIndex(['2000-01-04', '2000-01-05', '2000-01-06', '2000-01-07',
               '2000-01-10', '2000-01-11', '2000-01-12', '2000-01-13',
               '2000-01-14', '2000-01-17',
               ...
               '2019-09-17', '2019-09-18', '2019-09-19', '2019-09-20',
               '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26',
               '2019-09-27', '2019-09-30'],
              dtype='datetime64[us]', name='Date', length=5016, freq=None)

##### Q: select the brent  prince on 5-jan-2016

In [114]:
brent.loc['2016-01-05']

Price    35.56
Name: 2016-01-05 00:00:00, dtype: float64

In [115]:
brent.loc['2016-01-05':'2016-01-15']

            Price
Date
2016-01-05  35.56
2016-01-06  33.89
2016-01-07  33.57
2016-01-08  31.67
2016-01-11  30.14
2016-01-12  29.14
2016-01-13  28.58
2016-01-14  28.84
2016-01-15  28.80

##### Q: select the brent  prince on feb 2018

In [116]:
brent.loc['2018-02']

            Price
Date
2018-02-01  68.60
2018-02-02  67.45
2018-02-05  67.69
2018-02-06  66.75
2018-02-07  65.74
2018-02-08  64.26
2018-02-09  63.04
2018-02-12  62.20
2018-02-13  61.94
2018-02-14  62.29
2018-02-15  62.86
2018-02-16  64.30
2018-02-19  64.95
2018-02-20  64.68
2018-02-21  64.81
2018-02-22  66.12
2018-02-23  67.04
2018-02-26  67.96
2018-02-27  67.59
2018-02-28  66.08

##### Q: select the brent  prince from feb 2018 to mid apr 2018

In [118]:
brent.loc['2018-02':'2018-04-15']

            Price
Date
2018-02-01  68.60
2018-02-02  67.45
2018-02-05  67.69
2018-02-06  66.75
2018-02-07  65.74
2018-02-08  64.26
2018-02-09  63.04
2018-02-12  62.20
2018-02-13  61.94
2018-02-14  62.29
2018-02-15  62.86
2018-02-16  64.30
2018-02-19  64.95
2018-02-20  64.68
2018-02-21  64.81
2018-02-22  66.12
2018-02-23  67.04
2018-02-26  67.96
2018-02-27  67.59
2018-02-28  66.08
2018-03-01  64.23
2018-03-02  64.26
2018-03-05  65.78
2018-03-06  65.67
2018-03-07  65.09
2018-03-08  63.87
2018-03-09  65.19
2018-03-12  64.53
2018-03-13  64.20
2018-03-14  63.61
2018-03-15  63.67
2018-03-16  64.68
2018-03-19  64.82
2018-03-20  66.00
2018-03-21  68.15
2018-03-22  68.98
2018-03-23  69.03
2018-03-26  68.81
2018-03-27  68.63
2018-03-28  68.13
2018-03-29  69.02
2018-04-03  69.02
2018-04-04  66.04
2018-04-05  66.54
2018-04-06  66.51
2018-04-09  68.19
2018-04-10  70.67
2018-04-11  72.74
2018-04-12  71.44
2018-04-13  73.18

### 12. Skill Challenges

#### 1. Using the brent time series, create a shorter df that only contains the dates from 1 Dec 2015 to 31 Mar 2016

In [119]:
brent.head()

            Price
Date
2000-01-04  23.95
2000-01-05  23.72
2000-01-06  23.55
2000-01-07  23.35
2000-01-10  22.77

In [120]:
brent.loc['2015-12-1':'2016-03']

            Price
Date
2015-12-01  42.97
2015-12-02  41.92
2015-12-03  42.00
2015-12-04  41.44
2015-12-07  39.69
...           ...
2016-03-24  38.33
2016-03-28  38.33
2016-03-29  36.75
2016-03-30  36.75
2016-03-31  36.75

[84 rows x 1 columns]

#### 2. Repeat the above, but this time using string indexing instead of specifying full dates. What was the standard deviation of prices during this period ?

In [121]:
brent.loc['2015-12':'2016-03']

            Price
Date
2015-12-01  42.97
2015-12-02  41.92
2015-12-03  42.00
2015-12-04  41.44
2015-12-07  39.69
...           ...
2016-03-24  38.33
2016-03-28  38.33
2016-03-29  36.75
2016-03-30  36.75
2016-03-31  36.75

[84 rows x 1 columns]

In [122]:
brent.loc['2015-12':'2016-03'].std()

Price    3.990123
dtype: float64

#### 3. Was the means price from feb 2018 greater or less than the median price from mar 2017?

In [123]:
brent.loc['2018-02']

            Price
Date
2018-02-01  68.60
2018-02-02  67.45
2018-02-05  67.69
2018-02-06  66.75
2018-02-07  65.74
2018-02-08  64.26
2018-02-09  63.04
2018-02-12  62.20
2018-02-13  61.94
2018-02-14  62.29
2018-02-15  62.86
2018-02-16  64.30
2018-02-19  64.95
2018-02-20  64.68
2018-02-21  64.81
2018-02-22  66.12
2018-02-23  67.04
2018-02-26  67.96
2018-02-27  67.59
2018-02-28  66.08

In [124]:
brent.loc['2018-02'].mean()

Price    65.3175
dtype: float64

In [128]:
brent.loc['2017-03'].median()

Price    50.65
dtype: float64