### 2. Introducing New Datasets

In [2]:
eng_url = 'https://andybek.com/pandas-eng'
state_url = 'https://andybek.com/pandas-state'
party_url = 'https://andybek.com/pandas-party'
liberal_url = 'https://andybek.com/pandas-liberal'
ivies_url = 'https://andybek.com/pandas-ivies'

In [4]:
import pandas as pd
import numpy as np
eng = pd.read_csv(eng_url)
state = pd.read_csv(state_url)
party = pd.read_csv(party_url)
liberal = pd.read_csv(liberal_url)
ivies = pd.read_csv(ivies_url)

### 3. Concatenating DataFrames

In [5]:
df_arr = [eng, state, party, liberal, ivies]
for i in df_arr:
    print(i.shape)

(19, 4)
(175, 4)
(20, 4)
(47, 4)
(8, 4)

In [7]:
##
pd.concat([ivies, eng])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Dartmouth College,Ivy League,"$58,000.00","$134,000.00"
1,Princeton University,Ivy League,"$66,500.00","$131,000.00"
2,Yale University,Ivy League,"$59,100.00","$126,000.00"
3,Harvard University,Ivy League,"$63,400.00","$124,000.00"
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
5,Cornell University,Ivy League,"$60,300.00","$110,000.00"
6,Brown University,Ivy League,"$56,200.00","$109,000.00"
7,Columbia University,Ivy League,"$59,400.00","$107,000.00"
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
5,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00"
6,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00"
7,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00"
8,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00"
9,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00"
10,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00"
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00"
12,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00"
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00"
14,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00"
15,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00"
16,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00"
17,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00"
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00"

In [8]:
##
pd.concat([ivies, eng]).shape

(27, 4)

In [9]:
ivies.shape[0] + eng.shape[0]

27

In [11]:
pd.concat(df_arr) # But there is so many duplicates

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
3,Harvard University,Ivy League,"$63,400.00","$124,000.00"
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
5,Cornell University,Ivy League,"$60,300.00","$110,000.00"
6,Brown University,Ivy League,"$56,200.00","$109,000.00"
7,Columbia University,Ivy League,"$59,400.00","$107,000.00"

In [22]:
temp = pd.concat(df_arr).duplicated(subset=['School Name'], keep=False)

In [24]:
pd.concat(df_arr)[temp].sort_values(by=['School Name'])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
48,Arizona State University (ASU),State,"$47,400.00","$84,100.00"
9,Arizona State University (ASU),Party,"$47,400.00","$84,100.00"
120,Florida State University (FSU),State,"$42,100.00","$73,000.00"
19,Florida State University (FSU),Party,"$42,100.00","$73,000.00"
50,"Indiana University (IU), Bloomington",State,"$46,300.00","$84,000.00"
10,"Indiana University (IU), Bloomington",Party,"$46,300.00","$84,000.00"
26,Louisiana State University (LSU),State,"$46,900.00","$87,800.00"
6,Louisiana State University (LSU),Party,"$46,900.00","$87,800.00"
117,Ohio University,State,"$42,200.00","$73,400.00"
18,Ohio University,Party,"$42,200.00","$73,400.00"
34,Pennsylvania State University (PSU),State,"$49,900.00","$85,700.00"
8,Pennsylvania State University (PSU),Party,"$49,900.00","$85,700.00"
12,Randolph-Macon College,Party,"$42,600.00","$83,600.00"
28,Randolph-Macon College,Liberal Arts,"$42,600.00","$83,600.00"
18,State University of New York (SUNY) at Albany,State,"$44,500.00","$92,200.00"
4,State University of New York (SUNY) at Albany,Party,"$44,500.00","$92,200.00"
68,"University of Alabama, Tuscaloosa",State,"$41,300.00","$81,400.00"
13,"University of Alabama, Tuscaloosa",Party,"$41,300.00","$81,400.00"
14,"University of California, Santa Barbara (UCSB)",State,"$50,500.00","$95,000.00"
2,"University of California, Santa Barbara (UCSB)",Party,"$50,500.00","$95,000.00"
24,University of Florida (UF),State,"$47,100.00","$87,900.00"
5,University of Florida (UF),Party,"$47,100.00","$87,900.00"
33,University of Georgia (UGA),State,"$44,100.00","$86,000.00"
7,University of Georgia (UGA),Party,"$44,100.00","$86,000.00"
8,University of Illinois at Urbana-Champaign (UIUC),State,"$52,900.00","$96,100.00"
0,University of Illinois at Urbana-Champaign (UIUC),Party,"$52,900.00","$96,100.00"
51,University of Iowa (UI),State,"$44,700.00","$83,900.00"
11,University of Iowa (UI),Party,"$44,700.00","$83,900.00"
13,"University of Maryland, College Park",State,"$52,000.00","$95,000.00"
1,"University of Maryland, College Park",Party,"$52,000.00","$95,000.00"
79,University of Mississippi,State,"$41,400.00","$79,700.00"
14,University of Mississippi,Party,"$41,400.00","$79,700.00"
90,University of New Hampshire (UNH),State,"$41,800.00","$78,300.00"
15,University of New Hampshire (UNH),Party,"$41,800.00","$78,300.00"
108,University of Tennessee,State,"$43,800.00","$74,600.00"
17,University of Tennessee,Party,"$43,800.00","$74,600.00"
15,University of Texas (UT) - Austin,State,"$49,700.00","$93,900.00"
3,University of Texas (UT) - Austin,Party,"$49,700.00","$93,900.00"
92,West Virginia University (WVU),State,"$43,100.00","$78,100.00"
16,West Virginia University (WVU),Party,"$43,100.00","$78,100.00"

In [26]:
schools = pd.concat(df_arr).drop_duplicates(subset=['School Name'])
schools.info()

<class 'pandas.DataFrame'>
Index: 249 entries, 0 to 7
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               249 non-null    str
 1   School Type               249 non-null    str
 2   Starting Median Salary    249 non-null    str
 3   Mid-Career Median Salary  249 non-null    str
dtypes: str(4)
memory usage: 24.2 KB

### 4. The Duplicated Index Issue

In [29]:
schools.loc[0] 
# 4 rows for single index

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
0,"University of California, Berkeley",State,"$59,900.00","$112,000.00"
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
0,Dartmouth College,Ivy League,"$58,000.00","$134,000.00"

In [30]:
# in pandas, we could have duplicated indices!!

##### **First way**

In [31]:
schools.reset_index()

,index,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...,...
244,3,Harvard University,Ivy League,"$63,400.00","$124,000.00"
245,4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
246,5,Cornell University,Ivy League,"$60,300.00","$110,000.00"
247,6,Brown University,Ivy League,"$56,200.00","$109,000.00"
248,7,Columbia University,Ivy League,"$59,400.00","$107,000.00"

In [33]:
schools.reset_index(drop=True) # drop index true =>

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
244,Harvard University,Ivy League,"$63,400.00","$124,000.00"
245,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
246,Cornell University,Ivy League,"$60,300.00","$110,000.00"
247,Brown University,Ivy League,"$56,200.00","$109,000.00"
248,Columbia University,Ivy League,"$59,400.00","$107,000.00"

In [36]:
schools\
    .reset_index(drop=True)\
    .index\
    .duplicated()\
    .sum()

np.int64(0)

##### **Second way** Best method

In [39]:
pd.concat(df_arr).drop_duplicates(subset=['School Name'])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
3,Harvard University,Ivy League,"$63,400.00","$124,000.00"
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
5,Cornell University,Ivy League,"$60,300.00","$110,000.00"
6,Brown University,Ivy League,"$56,200.00","$109,000.00"
7,Columbia University,Ivy League,"$59,400.00","$107,000.00"

In [40]:
pd.concat(df_arr, ignore_index=True).drop_duplicates(subset=['School Name'])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
...,...,...,...,...
264,Harvard University,Ivy League,"$63,400.00","$124,000.00"
265,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
266,Cornell University,Ivy League,"$60,300.00","$110,000.00"
267,Brown University,Ivy League,"$56,200.00","$109,000.00"
268,Columbia University,Ivy League,"$59,400.00","$107,000.00"

### 7. Column Axis Concatenation

In [46]:
ivies2 = ivies.sort_values(by=['Starting Median Salary'], ascending=False).reset_index(drop=True)
eng2 = eng.sort_values(by=['Starting Median Salary'], ascending=False).reset_index(drop=True)

In [47]:
ivies2

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Princeton University,Ivy League,"$66,500.00","$131,000.00"
1,Harvard University,Ivy League,"$63,400.00","$124,000.00"
2,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
3,Cornell University,Ivy League,"$60,300.00","$110,000.00"
4,Columbia University,Ivy League,"$59,400.00","$107,000.00"
5,Yale University,Ivy League,"$59,100.00","$126,000.00"
6,Dartmouth College,Ivy League,"$58,000.00","$134,000.00"
7,Brown University,Ivy League,"$56,200.00","$109,000.00"

In [48]:
eng2

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
1,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"
5,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00"
6,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00"
7,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00"
8,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00"
9,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00"
10,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00"
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00"
12,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00"
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00"
14,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00"
15,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00"
16,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00"
17,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00"
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00"

In [50]:
pd.concat([eng2, ivies2], axis=1)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",Princeton University,Ivy League,"$66,500.00","$131,000.00"
1,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Harvard University,Ivy League,"$63,400.00","$124,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",Cornell University,Ivy League,"$60,300.00","$110,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Columbia University,Ivy League,"$59,400.00","$107,000.00"
5,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00",Yale University,Ivy League,"$59,100.00","$126,000.00"
6,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00",Dartmouth College,Ivy League,"$58,000.00","$134,000.00"
7,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00",Brown University,Ivy League,"$56,200.00","$109,000.00"
8,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00",NaN,NaN,NaN,NaN
9,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00",NaN,NaN,NaN,NaN
10,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00",NaN,NaN,NaN,NaN
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00",NaN,NaN,NaN,NaN
12,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00",NaN,NaN,NaN,NaN
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00",NaN,NaN,NaN,NaN
14,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00",NaN,NaN,NaN,NaN
15,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00",NaN,NaN,NaN,NaN
16,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00",NaN,NaN,NaN,NaN
17,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00",NaN,NaN,NaN,NaN
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00",NaN,NaN,NaN,NaN

### 9. Concat On Different Columns

In [51]:
eng3 = eng.sort_values(by=['Starting Median Salary'], ascending=False).reset_index(drop=True)
eng3['stem']=True

In [52]:
eng3

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,stem
0,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",True
1,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",True
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",True
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",True
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",True
5,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00",True
6,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00",True
7,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00",True
8,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00",True
9,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00",True
10,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00",True
11,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00",True
12,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00",True
13,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00",True
14,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00",True
15,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00",True
16,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00",True
17,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00",True
18,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00",True

In [57]:
pd.concat([ivies2,eng3], ignore_index=True)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,stem
0,Princeton University,Ivy League,"$66,500.00","$131,000.00",NaN
1,Harvard University,Ivy League,"$63,400.00","$124,000.00",NaN
2,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",NaN
3,Cornell University,Ivy League,"$60,300.00","$110,000.00",NaN
4,Columbia University,Ivy League,"$59,400.00","$107,000.00",NaN
5,Yale University,Ivy League,"$59,100.00","$126,000.00",NaN
6,Dartmouth College,Ivy League,"$58,000.00","$134,000.00",NaN
7,Brown University,Ivy League,"$56,200.00","$109,000.00",NaN
8,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",True
9,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",True
10,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",True
11,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",True
12,Cooper Union,Engineering,"$62,200.00","$114,000.00",True
13,Carnegie Mellon University (CMU),Engineering,"$61,800.00","$111,000.00",True
14,Rensselaer Polytechnic Institute (RPI),Engineering,"$61,100.00","$110,000.00",True
15,Worcester Polytechnic Institute (WPI),Engineering,"$61,000.00","$114,000.00",True
16,Stevens Institute of Technology,Engineering,"$60,600.00","$105,000.00",True
17,Georgia Institute of Technology,Engineering,"$58,300.00","$106,000.00",True
18,Colorado School of Mines,Engineering,"$58,100.00","$106,000.00",True
19,Illinois Institute of Technology (IIT),Engineering,"$56,000.00","$97,800.00",True
20,South Dakota School of Mines & Technology,Engineering,"$55,800.00","$93,400.00",True
21,Virginia Polytechnic Institute and State Unive...,Engineering,"$53,500.00","$95,400.00",True
22,Wentworth Institute of Technology,Engineering,"$53,000.00","$96,700.00",True
23,Embry-Riddle Aeronautical University (ERAU),Engineering,"$52,700.00","$80,700.00",True
24,New Mexico Institute of Mining and Technology ...,Engineering,"$51,000.00","$93,400.00",True
25,Rochester Institute of Technology (RIT),Engineering,"$48,900.00","$84,600.00",True
26,Tennessee Technological University,Engineering,"$46,200.00","$80,000.00",True

In [59]:
pd.concat([ivies2,eng3], ignore_index=True, join='inner').head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Princeton University,Ivy League,"$66,500.00","$131,000.00"
1,Harvard University,Ivy League,"$63,400.00","$124,000.00"
2,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00"
3,Cornell University,Ivy League,"$60,300.00","$110,000.00"
4,Columbia University,Ivy League,"$59,400.00","$107,000.00"

### 10. Skill Challenge

#### 1. Concat the liberal and state schools. How many unique schools in new df?

In [85]:
temp = pd.concat([liberal, state], ignore_index=True)
temp.drop_duplicates(subset='School Name')

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"
...,...,...,...,...
217,Austin Peay State University,State,"$37,700.00","$59,200.00"
218,Pittsburg State University,State,"$40,400.00","$58,200.00"
219,Southern Utah University,State,"$41,900.00","$56,500.00"
220,Montana State University - Billings,State,"$37,900.00","$50,600.00"
221,Black Hills State University,State,"$35,300.00","$43,900.00"

In [86]:
temp\
    .duplicated(subset="School Name")\
    .sum()

np.int64(0)

#### 2. What is the average median starting salary in the dataframe created above?

In [87]:
temp.info()

<class 'pandas.DataFrame'>
RangeIndex: 222 entries, 0 to 221
Data columns (total 4 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   School Name               222 non-null    str
 1   School Type               222 non-null    str
 2   Starting Median Salary    222 non-null    str
 3   Mid-Career Median Salary  222 non-null    str
dtypes: str(4)
memory usage: 19.7 KB

In [89]:
temp\
    .loc[:,'Starting Median Salary']\
    .replace('[^0-9]','', regex=True)\
    .astype(int)\
    .mean()\
    .round()

np.float64(4446937.0)

In [90]:
temp.head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00"
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00"
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00"
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00"
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00"

### 12. The merge() Method

In [91]:
regions_url = "https://andybek.com/pandas-regions"
regions = pd.read_csv(regions_url)
regions.info(False)

<class 'pandas.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Columns: 2 entries, School Name to Region
dtypes: str(2)
memory usage: 14.7 KB

In [92]:
regions.head()

                                    School Name        Region
0   Massachusetts Institute of Technology (MIT)  Northeastern
1      California Institute of Technology (CIT)    California
2                           Harvey Mudd College    California
3  Polytechnic University of New York, Brooklyn  Northeastern
4                                  Cooper Union  Northeastern

In [93]:
pd.merge(schools, regions, on='School Name')

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Northeastern
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",California
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",California
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00",Northeastern
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Northeastern
...,...,...,...,...,...
264,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
265,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",Northeastern
266,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
267,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
268,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern

### 13. The left_on And right_on Params

In [96]:
income_url = "https://andybek.com/pandas-mid"
mid_career = pd.read_csv(income_url)

In [97]:
mid_career.info(False)

<class 'pandas.DataFrame'>
RangeIndex: 269 entries, 0 to 268
Columns: 5 entries, school_name to Mid-Career 90th Percentile Salary
dtypes: str(5)
memory usage: 29.7 KB

In [98]:
mid_career.head()

,school_name,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,NaN,"$80,200.00","$142,000.00",NaN

In [99]:
schools.head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00"
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00"
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00"

In [103]:
# key colm has different name
pd.merge(schools,mid_career,left_on='School Name', right_on='school_name')\
    .head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,school_name,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00",Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00","Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",Cooper Union,NaN,"$80,200.00","$142,000.00",NaN

In [105]:
# key colm has different name
pd.merge(schools,mid_career,left_on='School Name', right_on='school_name')\
    .head()\
    .drop('school_name', axis=1)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),Engineering,"$72,200.00","$126,000.00","$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),Engineering,"$75,500.00","$123,000.00",NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,Engineering,"$71,800.00","$122,000.00",NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn",Engineering,"$62,400.00","$114,000.00","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,Engineering,"$62,200.00","$114,000.00",NaN,"$80,200.00","$142,000.00",NaN

### 14. Inner vs Outer Joins

In [106]:
pd.merge(ivies, regions, on='School Name')

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Dartmouth College,Ivy League,"$58,000.00","$134,000.00",Northeastern
1,Princeton University,Ivy League,"$66,500.00","$131,000.00",Northeastern
2,Yale University,Ivy League,"$59,100.00","$126,000.00",Northeastern
3,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",Northeastern
5,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
6,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
7,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern

In [110]:
pd.merge(
    ivies, 
    regions, 
    on='School Name',
    how="outer"
).sort_values(by=['School Type'])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
14,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
36,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern
38,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
39,Dartmouth College,Ivy League,"$58,000.00","$134,000.00",Northeastern
62,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
...,...,...,...,...,...
263,Western Washington University,NaN,NaN,NaN,Western
264,Whitman College,NaN,NaN,NaN,Western
265,Williams College,NaN,NaN,NaN,Northeastern
266,Wittenberg University,NaN,NaN,NaN,Midwestern
267,Worcester Polytechnic Institute (WPI),NaN,NaN,NaN,Northeastern

### 15. Left vs Right Joins

In [111]:
pd.merge(
    ivies, 
    regions, 
    on='School Name',
    how="left"
).sort_values(by=['School Type'])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Dartmouth College,Ivy League,"$58,000.00","$134,000.00",Northeastern
1,Princeton University,Ivy League,"$66,500.00","$131,000.00",Northeastern
2,Yale University,Ivy League,"$59,100.00","$126,000.00",Northeastern
3,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",Northeastern
5,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
6,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
7,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern

In [113]:
pd.merge(
    ivies, 
    regions, 
    on='School Name',
    how="right"
).sort_values(by=['Starting Median Salary'])

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
92,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
86,Dartmouth College,Ivy League,"$58,000.00","$134,000.00",Northeastern
88,Yale University,Ivy League,"$59,100.00","$126,000.00",Northeastern
93,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern
91,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
...,...,...,...,...,...
264,Austin Peay State University,NaN,NaN,NaN,Southern
265,Pittsburg State University,NaN,NaN,NaN,Midwestern
266,Southern Utah University,NaN,NaN,NaN,Western
267,Montana State University - Billings,NaN,NaN,NaN,Western
268,Black Hills State University,NaN,NaN,NaN,Midwestern

### 16. One-to-One and One-to-Many Joins

##### **One to One**

In [130]:
check_one_to_one = regions.loc[:,'School Name']\
    .isin(ivies.loc[:,'School Name'])
regions[check_one_to_one].loc[:,'School Name']\
    .is_unique

True

In [126]:
pd.merge(
    ivies,
    regions,
    on='School Name'
)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Dartmouth College,Ivy League,"$58,000.00","$134,000.00",Northeastern
1,Princeton University,Ivy League,"$66,500.00","$131,000.00",Northeastern
2,Yale University,Ivy League,"$59,100.00","$126,000.00",Northeastern
3,Harvard University,Ivy League,"$63,400.00","$124,000.00",Northeastern
4,University of Pennsylvania,Ivy League,"$60,900.00","$120,000.00",Northeastern
5,Cornell University,Ivy League,"$60,300.00","$110,000.00",Northeastern
6,Brown University,Ivy League,"$56,200.00","$109,000.00",Northeastern
7,Columbia University,Ivy League,"$59,400.00","$107,000.00",Northeastern

##### **One to Many**

In [131]:
check_one_to_many = regions.loc[:,'School Name']\
    .isin(state.loc[:,'School Name'])
regions[check_one_to_many].loc[:,'School Name']\
    .is_unique

False

In [132]:
pd.merge(
    state,
    regions,
    on='School Name'
)

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,"University of California, Berkeley",State,"$59,900.00","$112,000.00",California
1,University of Virginia (UVA),State,"$52,700.00","$103,000.00",Southern
2,Cal Poly San Luis Obispo,State,"$57,200.00","$101,000.00",California
3,University of California at Los Angeles (UCLA),State,"$52,600.00","$101,000.00",California
4,"University of California, San Diego (UCSD)",State,"$51,100.00","$101,000.00",California
...,...,...,...,...,...
189,Austin Peay State University,State,"$37,700.00","$59,200.00",Southern
190,Pittsburg State University,State,"$40,400.00","$58,200.00",Midwestern
191,Southern Utah University,State,"$41,900.00","$56,500.00",Western
192,Montana State University - Billings,State,"$37,900.00","$50,600.00",Western
193,Black Hills State University,State,"$35,300.00","$43,900.00",Midwestern

In [141]:
temp2 = pd.merge(
    state,
    regions,
    on='School Name'
)

In [148]:
temp2.loc[:,'School Name'].value_counts()

School Name
University of Illinois at Urbana-Champaign (UIUC)    2
University of Maryland, College Park                 2
University of California, Santa Barbara (UCSB)       2
University of Texas (UT) - Austin                    2
State University of New York (SUNY) at Albany        2
                                                    ..
Austin Peay State University                         1
Pittsburg State University                           1
Southern Utah University                             1
Montana State University - Billings                  1
Black Hills State University                         1
Name: count, Length: 175, dtype: int64

In [149]:
temp2.loc[:,'School Name'].is_unique()

TypeError: 'bool' object is not callable

### 20. Skill Challenge

#### 1. Merge liberal and regions and assign it in dfm var. What region has the highest no. of liberal arts schools ?

In [150]:
dfm = pd.merge(
    liberal,
    regions,
    on = "School Name"
)
dfm.head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00",Northeastern
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00",Northeastern
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00",Northeastern
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00",Northeastern
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00",Northeastern

In [151]:
dfm.Region.value_counts()

Region
Northeastern    25
Midwestern       8
Western          7
Southern         5
California       3
Name: count, dtype: int64

#### 2. Set school_name as the index of the mid_career df. Do the operation inplace.

In [152]:
mid_career.head()

,school_name,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
0,Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
1,California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
2,Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
3,"Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
4,Cooper Union,NaN,"$80,200.00","$142,000.00",NaN

In [153]:
mid_career.set_index(mid_career.school_name, inplace=True)

In [154]:
mid_career.head()

,school_name,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
school_name,,,,,
Massachusetts Institute of Technology (MIT),Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
California Institute of Technology (CIT),California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
Harvey Mudd College,Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
"Polytechnic University of New York, Brooklyn","Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
Cooper Union,Cooper Union,NaN,"$80,200.00","$142,000.00",NaN

#### 3. Merge the dfm and mid_career df. Is the join operation one to one?

In [155]:
dfm.head()

,School Name,School Type,Starting Median Salary,Mid-Career Median Salary,Region
0,Bucknell University,Liberal Arts,"$54,100.00","$110,000.00",Northeastern
1,Colgate University,Liberal Arts,"$52,800.00","$108,000.00",Northeastern
2,Amherst College,Liberal Arts,"$54,500.00","$107,000.00",Northeastern
3,Lafayette College,Liberal Arts,"$53,900.00","$107,000.00",Northeastern
4,Bowdoin College,Liberal Arts,"$48,100.00","$107,000.00",Northeastern

In [158]:
mid_career = mid_career.drop('school_name',axis=1)
mid_career.head()

,Mid-Career 10th Percentile Salary,Mid-Career 25th Percentile Salary,Mid-Career 75th Percentile Salary,Mid-Career 90th Percentile Salary
school_name,,,,
Massachusetts Institute of Technology (MIT),"$76,800.00","$99,200.00","$168,000.00","$220,000.00"
California Institute of Technology (CIT),NaN,"$104,000.00","$161,000.00",NaN
Harvey Mudd College,NaN,"$96,000.00","$180,000.00",NaN
"Polytechnic University of New York, Brooklyn","$66,800.00","$94,300.00","$143,000.00","$190,000.00"
Cooper Union,NaN,"$80,200.00","$142,000.00",NaN

In [162]:
pd.merge(
    dfm,
    mid_career,
    left_on = "School Name",
    right_index=True
).loc[:,'School Name'].value_counts()

School Name
Randolph-Macon College                           4
Bucknell University                              1
Colgate University                               1
Amherst College                                  1
Lafayette College                                1
Bowdoin College                                  1
College of the Holy Cross                        1
Occidental College                               1
Washington and Lee University                    1
Swarthmore College                               1
Davidson College                                 1
Carleton College                                 1
Williams College                                 1
Pomona College                                   1
Wesleyan University (Middletown, Connecticut)    1
Bates College                                    1
Union College                                    1
University of Richmond                           1
Vassar College                                   1
Middlebury College                               1
Mount Holyoke College                            1
Franklin and Marshall College                    1
DePauw University                                1
St. Olaf College                                 1
Colby College                                    1
Gettysburg College                               1
Siena College                                    1
Smith College                                    1
Hamilton College                                 1
Wellesley College                                1
Denison University                               1
Oberlin College                                  1
University of Puget Sound                        1
Colorado College (CC)                            1
Reed College                                     1
Gustavus Adolphus College                        1
Whitman College                                  1
Ursinus College                                  1
Juniata College                                  1
Wittenberg University                            1
Grinnell College                                 1
Skidmore College                                 1
Moravian College                                 1
Lewis & Clark College                            1
Fort Lewis College                               1
Thomas Aquinas College                           1
Evergreen State College                          1
Name: count, dtype: int64