In [1]:
import pandas as pd
import numpy as np

In [2]:
games_url = 'https://andybek.com/pandas-games'
games = pd.read_csv(games_url)
games.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
1,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
2,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
3,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
4,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64

In [3]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3143 non-null   object
 1   Platform      3143 non-null   object
 2   Year          3088 non-null   float64
 3   Genre         3143 non-null   object
 4   Publisher     3136 non-null   object
 5   NA_Sales      3143 non-null   float64
 6   EU_Sales      3143 non-null   float64
 7   JP_Sales      3143 non-null   float64
 8   Other_Sales   3143 non-null   float64
 9   Global_Sales  3143 non-null   float64
dtypes: float64(6), object(4)
memory usage: 245.7+ KB

### 3. Simple Aggregations Review

In [4]:
games.iloc[:,5:].sum(axis=0)

NA_Sales        1173.30
EU_Sales         793.64
JP_Sales         107.06
Other_Sales      282.75
Global_Sales    2356.96
dtype: float64

In [5]:
games.iloc[:,5:].sum(axis=1)

0       43.64
1       42.79
2       32.76
3       29.52
4       29.28
        ...
3138     0.02
3139     0.02
3140     0.02
3141     0.02
3142     0.02
Length: 3143, dtype: float64

### 4. Conditional Aggregations

In [6]:
temp = games.iloc[:,[1,5,6,7,8,9]]
temp.Platform.unique()

array(['X360', 'PS3', 'PS4', 'XOne'], dtype=object)

In [7]:
## show total sales of xbox 360 platform

In [8]:
temp[temp.Platform == 'X360'].select_dtypes(np.number).sum()

NA_Sales        601.05
EU_Sales        280.58
JP_Sales         12.43
Other_Sales      85.54
Global_Sales    979.96
dtype: float64

In [9]:
temp[temp.Platform == 'X360'].sum(numeric_only=True)

NA_Sales        601.05
EU_Sales        280.58
JP_Sales         12.43
Other_Sales      85.54
Global_Sales    979.96
dtype: float64

### 6. groupby() Method

In [10]:
temp.groupby('Platform').sum()

          NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
PS3         392.26    343.71     79.99       141.93        957.84
PS4          96.80    123.70     14.30        43.36        278.10
X360        601.05    280.58     12.43        85.54        979.96
XOne         83.19     45.65      0.34        11.92        141.06

In [11]:
temp.groupby('Platform').mean()

          NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
PS3       0.295154  0.258623  0.060188     0.106795      0.720722
PS4       0.288095  0.368155  0.042560     0.129048      0.827679
X360      0.475138  0.221802  0.009826     0.067621      0.774672
XOne      0.390563  0.214319  0.001596     0.055962      0.662254

### 8. Customizing Index To Group Mapppings

In [12]:
temp.Platform.unique()

array(['X360', 'PS3', 'PS4', 'XOne'], dtype=object)

In [13]:
platform_names={
    'X360': 'Xbox',
    'XOne': 'Xbox',
    'PS3': 'Playstation',
    'PS4': 'Playstation'
}

In [14]:
temp.set_index('Platform')\
    .groupby(platform_names)\
    .sum(numeric_only=True)

             NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
Platform
Playstation    489.06    467.41     94.29       185.29       1235.94
Xbox           684.24    326.23     12.77        97.46       1121.02

### 10. Skill Challenge

#### 1. Create a smaller df from games, by selecting publisher, gener, platform, and NA_sales. Assign it to publisher

In [15]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3143 non-null   object
 1   Platform      3143 non-null   object
 2   Year          3088 non-null   float64
 3   Genre         3143 non-null   object
 4   Publisher     3136 non-null   object
 5   NA_Sales      3143 non-null   float64
 6   EU_Sales      3143 non-null   float64
 7   JP_Sales      3143 non-null   float64
 8   Other_Sales   3143 non-null   float64
 9   Global_Sales  3143 non-null   float64
dtypes: float64(6), object(4)
memory usage: 245.7+ KB

In [16]:
publisher = games.iloc[:,[4,3,1,5]]
publisher.head()

                Publisher    Genre Platform  NA_Sales
0  Microsoft Game Studios     Misc     X360     14.97
1    Take-Two Interactive   Action      PS3      7.01
2    Take-Two Interactive   Action     X360      9.63
3              Activision  Shooter     X360      9.03
4              Activision  Shooter     X360      9.67

#### 2. From the publisher df, find the top 10 game publish in North America by total sales

In [17]:
publisher\
    .groupby('Publisher')\
    .sum(numeric_only=True)\
    .sort_values(
        by=['NA_Sales'], 
        ascending=False
    )\
    .head(10)

                                        NA_Sales
Publisher
Electronic Arts                           213.38
Activision                                193.16
Take-Two Interactive                      120.99
Microsoft Game Studios                    116.77
Ubisoft                                    98.65
Sony Computer Entertainment                76.35
Warner Bros. Interactive Entertainment     45.24
THQ                                        36.44
Bethesda Softworks                         33.88
Capcom                                     24.74

#### 3. Similarly, what the gaming platform that has attracted the most sales in North America?

In [19]:
publisher\
    .groupby('Platform')\
    .sum(numeric_only=True)\
    .sort_values(
        by=['NA_Sales'], 
        ascending=False
    )

          NA_Sales
Platform
X360        601.05
PS3         392.26
PS4          96.80
XOne         83.19

### 15. Fine-tuned Aggregates

In [20]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3143 non-null   object
 1   Platform      3143 non-null   object
 2   Year          3088 non-null   float64
 3   Genre         3143 non-null   object
 4   Publisher     3136 non-null   object
 5   NA_Sales      3143 non-null   float64
 6   EU_Sales      3143 non-null   float64
 7   JP_Sales      3143 non-null   float64
 8   Other_Sales   3143 non-null   float64
 9   Global_Sales  3143 non-null   float64
dtypes: float64(6), object(4)
memory usage: 245.7+ KB

In [21]:
studios = games.iloc[:,[4,3,9]]
studios.head()

                Publisher    Genre  Global_Sales
0  Microsoft Game Studios     Misc         21.82
1    Take-Two Interactive   Action         21.40
2    Take-Two Interactive   Action         16.38
3              Activision  Shooter         14.76
4              Activision  Shooter         14.64

In [22]:
studios.groupby(['Genre','Publisher']).sum()

                               Global_Sales
Genre    Publisher
Action   505 Games                     2.25
         Abylight                      0.08
         Ackkstudios                   0.33
         Acquire                       0.11
         Activision                   42.84
...                                     ...
Strategy Square Enix                   0.35
         Takara Tomy                   0.09
         Take-Two Interactive          2.92
         Tecmo Koei                    0.58
         Ubisoft                       2.34

[422 rows x 1 columns]

In [23]:
studios.groupby(['Genre','Publisher']).agg('sum')

                               Global_Sales
Genre    Publisher
Action   505 Games                     2.25
         Abylight                      0.08
         Ackkstudios                   0.33
         Acquire                       0.11
         Activision                   42.84
...                                     ...
Strategy Square Enix                   0.35
         Takara Tomy                   0.09
         Take-Two Interactive          2.92
         Tecmo Koei                    0.58
         Ubisoft                       2.34

[422 rows x 1 columns]

In [24]:
# Q: Summarize the sum and count of sales as well as the no. of games published by each publisher witin each genre

In [25]:
studios.groupby(['Genre','Publisher'])\
    .agg(['sum','count'])\
    .sort_values(by=('Global_Sales','sum'),ascending=False)

                                        Global_Sales
                                                 sum count
Genre        Publisher
Shooter      Activision                       245.46    72
Sports       Electronic Arts                  203.50   170
Action       Take-Two Interactive             106.04    23
             Ubisoft                           96.44    67
Shooter      Electronic Arts                   92.58    50
...                                              ...   ...
Adventure    Cave                               0.01     1
Role-Playing TopWare Interactive                0.01     1
Sports       Interworks Unlimited, Inc.         0.01     1
Strategy     Ackkstudios                        0.01     1
Adventure    Views                              0.01     1

[422 rows x 2 columns]

In [26]:
games[games.Publisher == 'Activision'].sort_values(by='Global_Sales', ascending=False).head(8)

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
3,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
4,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
5,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
6,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
7,Call of Duty: Black Ops II,X360,2012.0,Shooter,Activision,8.25,4.30,0.07,1.12,13.73
8,Call of Duty: Modern Warfare 2,X360,2009.0,Shooter,Activision,8.52,3.63,0.08,1.29,13.51
9,Call of Duty: Modern Warfare 3,PS3,2011.0,Shooter,Activision,5.54,5.82,0.49,1.62,13.46
10,Call of Duty: Black Ops,PS3,2010.0,Shooter,Activision,5.98,4.44,0.48,1.83,12.73

### 16. Named Aggregations

In [32]:
studios.groupby(['Genre','Publisher'])\
    .agg(['sum','count'])\
    .sort_values(by=('Global_Sales','sum'),ascending=False)\
    .rename({'sum':'total_sasles','count':'num_of_sales'},axis=1)

                                        Global_Sales
                                        total_sasles num_of_sales
Genre        Publisher
Shooter      Activision                       245.46           72
Sports       Electronic Arts                  203.50          170
Action       Take-Two Interactive             106.04           23
             Ubisoft                           96.44           67
Shooter      Electronic Arts                   92.58           50
...                                              ...          ...
Adventure    Cave                               0.01            1
Role-Playing TopWare Interactive                0.01            1
Sports       Interworks Unlimited, Inc.         0.01            1
Strategy     Ackkstudios                        0.01            1
Adventure    Views                              0.01            1

[422 rows x 2 columns]

In [33]:
# Name Aggregation

In [34]:
studios.groupby(['Genre','Publisher'])\
    .agg(
        total_sales=('Global_Sales','sum'),
        num_of_sales=('Global_Sales','count')
    )

                               total_sales  num_of_sales
Genre    Publisher
Action   505 Games                    2.25             8
         Abylight                     0.08             1
         Ackkstudios                  0.33             1
         Acquire                      0.11             1
         Activision                  42.84            95
...                                    ...           ...
Strategy Square Enix                  0.35             1
         Takara Tomy                  0.09             1
         Take-Two Interactive         2.92             6
         Tecmo Koei                   0.58             6
         Ubisoft                      2.34             4

[422 rows x 2 columns]

In [35]:
# we can hand pick the desire columns

In [36]:
games.groupby(['Genre','Publisher'])\
    .agg(
        total_global_sales=('Global_Sales','sum'),
        total_EU_sales=('EU_Sales','sum')
    )

                               total_global_sales  total_EU_sales
Genre    Publisher
Action   505 Games                           2.25            1.05
         Abylight                            0.08            0.00
         Ackkstudios                         0.33            0.00
         Acquire                             0.11            0.00
         Activision                         42.84           13.59
...                                           ...             ...
Strategy Square Enix                         0.35            0.10
         Takara Tomy                         0.09            0.00
         Take-Two Interactive                2.92            0.87
         Tecmo Koei                          0.58            0.00
         Ubisoft                             2.34            0.80

[422 rows x 2 columns]

### 20. Skill Challenge

#### 1. Starting with the games df, calculate the total global across for each year(Year) across all records. What are the top 3 years by aggregate global sales?

In [37]:
games.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
1,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
2,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
3,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
4,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64

#### Find duplicates and remove it.

In [46]:
null_year = games.Year.isnull()
games[null_year]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
202,Rock Band,X360,NaN,Misc,Electronic Arts,1.93,0.34,0.00,0.21,2.48
349,Rock Band,PS3,NaN,Misc,Electronic Arts,0.99,0.41,0.00,0.22,1.62
600,LEGO Harry Potter: Years 5-7,X360,NaN,Action,Warner Bros. Interactive Entertainment,0.51,0.39,0.00,0.09,0.99
619,Yakuza 4,PS3,NaN,Action,Sega,0.15,0.14,0.63,0.05,0.97
622,LEGO Harry Potter: Years 5-7,PS3,NaN,Action,Warner Bros. Interactive Entertainment,0.36,0.45,0.00,0.16,0.97
707,The Lord of the Rings: War in the North,PS3,NaN,Action,Warner Bros. Interactive Entertainment,0.25,0.45,0.01,0.15,0.86
709,The Lord of the Rings: War in the North,X360,NaN,Action,Warner Bros. Interactive Entertainment,0.52,0.26,0.00,0.08,0.86
745,Shaun White Snowboarding,X360,NaN,Sports,Ubisoft,0.48,0.26,0.00,0.08,0.82
866,Test Drive Unlimited 2,X360,NaN,Racing,Atari,0.30,0.32,0.00,0.07,0.69
912,Test Drive Unlimited 2,PS3,NaN,Racing,Atari,0.16,0.35,0.01,0.12,0.64
992,Madden NFL 06,X360,NaN,Sports,Electronic Arts,0.54,0.00,0.01,0.03,0.59
1106,Wet,X360,NaN,Shooter,Bethesda Softworks,0.23,0.21,0.01,0.05,0.50
1149,Sonic the Hedgehog,PS3,NaN,Platform,NaN,0.00,0.48,0.00,0.00,0.48
1202,Silent Hill: Homecoming,X360,NaN,Action,Konami Digital Entertainment,0.25,0.16,0.00,0.04,0.45
1218,Robert Ludlum's The Bourne Conspiracy,X360,NaN,Action,Vivendi Games,0.26,0.14,0.00,0.04,0.44
1286,Silent Hill: Homecoming,PS3,NaN,Action,Konami Digital Entertainment,0.18,0.15,0.00,0.06,0.40
1303,Robert Ludlum's The Bourne Conspiracy,PS3,NaN,Action,Vivendi Games,0.18,0.14,0.00,0.06,0.39
1349,Tropico 4,X360,NaN,Strategy,Kalypso Media,0.20,0.13,0.00,0.03,0.36
1450,Singularity,X360,NaN,Shooter,Unknown,0.24,0.05,0.00,0.02,0.32
1571,Gun,X360,NaN,Shooter,Activision,0.24,0.01,0.00,0.02,0.27
1593,Rock Revolution,PS3,NaN,Misc,Unknown,0.25,0.00,0.00,0.02,0.27
1612,Jonah Lomu Rugby Challenge,PS3,NaN,Sports,Home Entertainment Suppliers,0.00,0.20,0.00,0.06,0.26
1683,Singularity,PS3,NaN,Shooter,Unknown,0.17,0.04,0.01,0.03,0.24
1747,Move Fitness,PS3,NaN,Sports,Sony Computer Entertainment,0.00,0.17,0.00,0.05,0.22
1798,WRC: FIA World Rally Championship,PS3,NaN,Racing,Black Bean Games,0.00,0.15,0.01,0.05,0.21
1903,Star Trek: Legacy,X360,NaN,Simulation,Ubisoft,0.14,0.03,0.00,0.02,0.19
1929,Backbreaker,X360,NaN,Sports,Unknown,0.17,0.00,0.00,0.01,0.18
1944,Otomedius Excellent,X360,NaN,Shooter,Unknown,0.13,0.00,0.04,0.01,0.18
1973,Backbreaker,PS3,NaN,Sports,Unknown,0.16,0.00,0.00,0.01,0.17
1999,Splatterhouse,PS3,NaN,Action,Namco Bandai Games,0.13,0.02,0.00,0.02,0.17
2053,Jurassic Park: The Game,X360,NaN,Action,Unknown,0.15,0.00,0.00,0.01,0.16
2117,Bejeweled 3,PS3,NaN,Puzzle,Unknown,0.13,0.00,0.00,0.01,0.14
2132,Bejeweled 3,X360,NaN,Puzzle,Unknown,0.13,0.00,0.00,0.01,0.14
2210,WRC: FIA World Rally Championship,X360,NaN,Racing,Black Bean Games,0.00,0.10,0.00,0.02,0.12
2218,Record of Agarest War Zero,PS3,NaN,Strategy,Ghostlight,0.09,0.00,0.03,0.01,0.12
2336,Happy Feet Two,PS3,NaN,Action,Warner Bros. Interactive Entertainment,0.09,0.01,0.00,0.01,0.10
2379,Happy Feet Two,X360,NaN,Action,Warner Bros. Interactive Entertainment,0.08,0.01,0.00,0.01,0.10
2481,Get Fit with Mel B,X360,NaN,Sports,Black Bean Games,0.00,0.07,0.00,0.01,0.08
2572,Port Royale 3,PS3,NaN,Simulation,Kalypso Media,0.06,0.00,0.00,0.01,0.07
2585,Yoostar on MTV,X360,NaN,Misc,Unknown,0.06,0.00,0.00,0.00,0.07
2594,National Geographic Challenge!,X360,NaN,Misc,Unknown,0.06,0.00,0.00,0.00,0.07
2599,Port Royale 3,X360,NaN,Simulation,Kalypso Media,0.06,0.00,0.00,0.00,0.07
2651,Mobile Ops: The One Year War,X360,NaN,Simulation,Namco Bandai Games,0.00,0.00,0.06,0.00,0.06
2669,Tour de France 2011,X360,NaN,Racing,Focus Home Interactive,0.00,0.05,0.00,0.01,0.05
2688,Battle vs. Chess,PS3,NaN,Misc,TopWare Interactive,0.00,0.04,0.00,0.01,0.05
2701,The History Channel: Great Battles - Medieval,PS3,NaN,Strategy,Slitherine Software,0.00,0.04,0.00,0.01,0.05
2713,Monster Hunter Frontier Online,PS3,NaN,Role-Playing,NaN,0.00,0.00,0.05,0.00,0.05
2808,World of Tanks,X360,NaN,Shooter,NaN,0.00,0.03,0.00,0.00,0.04
2852,Majesty 2: The Fantasy Kingdom Sim,X360,NaN,Simulation,Unknown,0.03,0.00,0.00,0.00,0.03
2926,Umineko no Naku Koro ni San: Shinjitsu to Gens...,PS3,NaN,Adventure,NaN,0.00,0.00,0.02,0.00,0.02
3029,Football Manager 2007,X360,NaN,Sports,Sega,0.00,0.01,0.00,0.00,0.02
3087,AKB1/48: Idol to Guam de Koishitara...,X360,NaN,Misc,NaN,0.00,0.00,0.01,0.00,0.01
3093,Brothers in Arms: Furious 4,X360,NaN,Shooter,NaN,0.01,0.00,0.00,0.00,0.01
3097,Agarest Senki: Re-appearance,PS3,NaN,Role-Playing,Idea Factory,0.00,0.00,0.01,0.00,0.01
3108,Hakuouki: Shinsengumi Kitan,PS3,NaN,Adventure,Unknown,0.01,0.00,0.00,0.00,0.01

In [48]:
games.Year.median()

2011.0

In [49]:
games.Year.mean()

np.float64(2011.1742227979275)

In [50]:
games.Year.unique()

array([2010., 2013., 2011., 2015., 2012., 2009., 2007., 2014., 2008.,
       2006., 2016.,   nan, 2005., 2017.])

In [54]:
games.Year.fillna(games.Year.median())

0       2010.0
1       2013.0
2       2013.0
3       2011.0
4       2010.0
         ...
3138    2014.0
3139    2016.0
3140    2016.0
3141    2016.0
3142    2016.0
Name: Year, Length: 3143, dtype: float64

In [55]:
games.Year = games.Year.fillna(games.Year.median())

In [56]:
null_year = games.Year.isnull()
games[null_year]

Empty DataFrame
Columns: [Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

#### Solution:

In [61]:
games\
    .iloc[:,[2,9]]\
    .groupby('Year')\
    .sum()\
    .sort_values(by='Global_Sales',ascending=False)\
    .head(3)

        Global_Sales
Year
2011.0        323.33
2010.0        315.47
2008.0        255.45

#### 2. In the games df, what Genre, in what Year, in what Platform sold the most in Europe?

In [63]:
games.head()

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Kinect Adventures!,X360,2010.0,Misc,Microsoft Game Studios,14.97,4.94,0.24,1.67,21.82
1,Grand Theft Auto V,PS3,2013.0,Action,Take-Two Interactive,7.01,9.27,0.97,4.14,21.40
2,Grand Theft Auto V,X360,2013.0,Action,Take-Two Interactive,9.63,5.31,0.06,1.38,16.38
3,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
4,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64

In [64]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3143 non-null   object
 1   Platform      3143 non-null   object
 2   Year          3143 non-null   float64
 3   Genre         3143 non-null   object
 4   Publisher     3136 non-null   object
 5   NA_Sales      3143 non-null   float64
 6   EU_Sales      3143 non-null   float64
 7   JP_Sales      3143 non-null   float64
 8   Other_Sales   3143 non-null   float64
 9   Global_Sales  3143 non-null   float64
dtypes: float64(6), object(4)
memory usage: 245.7+ KB

In [69]:
games\
    .iloc[:,[3,2,1,7]]\
    .groupby(['Genre', 'Year', 'Platform'])\
    .sum()\
    .sort_values('JP_Sales',ascending=False)\
    .head()

                              JP_Sales
Genre        Year   Platform
Action       2011.0 PS3           5.69
             2013.0 PS3           4.95
             2012.0 PS3           4.35
Role-Playing 2011.0 PS3           3.74
Action       2009.0 PS3           3.46

#### 3. Find all the Names in the games dataset whose Genre in their respective Platform sold more in Japan than in Europe

In [70]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3143 entries, 0 to 3142
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          3143 non-null   object
 1   Platform      3143 non-null   object
 2   Year          3143 non-null   float64
 3   Genre         3143 non-null   object
 4   Publisher     3136 non-null   object
 5   NA_Sales      3143 non-null   float64
 6   EU_Sales      3143 non-null   float64
 7   JP_Sales      3143 non-null   float64
 8   Other_Sales   3143 non-null   float64
 9   Global_Sales  3143 non-null   float64
dtypes: float64(6), object(4)
memory usage: 245.7+ KB

#### Find Genre and Platform sold more in Japan than in Europe

In [74]:
temp = games\
    .iloc[:,[3,1,7,6]]\
    .groupby(['Genre','Platform'])\
    .sum()
temp.head(9)

                    JP_Sales  EU_Sales
Genre     Platform
Action    PS3          29.59    110.62
          PS4           5.41     38.19
          X360          2.77     76.81
          XOne          0.05     11.47
Adventure PS3           2.68      8.13
          PS4           0.38      2.19
          X360          0.61      4.86
          XOne          0.03      1.08
Fighting  PS3           6.54     14.69

In [76]:
temp[temp.JP_Sales > temp.EU_Sales]

                 JP_Sales  EU_Sales
Genre  Platform
Puzzle PS3           0.10      0.05
       X360          0.15      0.04

#### Find all game with above respective Genre and Platform with the that condition

In [86]:
puzzle_ps3_x360 = (games.Genre == 'Puzzle') & ((games.Platform == 'PS3') | (games.Platform == 'X360')) & (games.JP_Sales>games.EU_Sales)
puzzle_ps3_x360

0       False
1       False
2       False
3       False
4       False
        ...
3138    False
3139    False
3140    False
3141    False
3142    False
Length: 3143, dtype: bool

In [87]:
games[puzzle_ps3_x360]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
1246,Katamari Forever,PS3,2009.0,Puzzle,Namco Bandai Games,0.26,0.05,0.06,0.04,0.42
1440,Beautiful Katamari,X360,2007.0,Puzzle,Namco Bandai Games,0.14,0.02,0.15,0.02,0.32
2744,Puyo Puyo Tetris,PS3,2014.0,Puzzle,Sega,0.00,0.00,0.04,0.00,0.04