## 2. Reading In Data With read_csv()

In [4]:
import pandas as pd

In [5]:
pd.read_csv('https://www.andybek.com/pandas-drinks')

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
0,Afghanistan,NaN,NaN,NaN,NaN
1,Albania,89.0,132.0,54.0,4.9
2,Algeria,25.0,NaN,14.0,0.7
3,Andorra,245.0,138.0,312.0,12.4
4,Angola,217.0,57.0,45.0,5.9
...,...,...,...,...,...
188,Venezuela,333.0,1.0,3.0,7.7
189,Vietnam,111.0,2.0,1.0,2.0
190,Yemen,6.0,NaN,NaN,0.1
191,Zambia,32.0,19.0,4.0,2.5
192,Zimbabwe,64.0,18.0,4.0,4.7

In [6]:
pd.read_csv('https://www.andybek.com/pandas-drinks', usecols=['country', 'wine_servings'])

         country  wine_servings
0    Afghanistan            NaN
1        Albania           54.0
2        Algeria           14.0
3        Andorra          312.0
4         Angola           45.0
..           ...            ...
188    Venezuela            3.0
189      Vietnam            1.0
190        Yemen            NaN
191       Zambia            4.0
192     Zimbabwe            4.0

[193 rows x 2 columns]

In [7]:
alcohol = pd.read_csv('https://www.andybek.com/pandas-drinks', usecols=['country', 'wine_servings'], index_col='country')

In [6]:
alcohol.head()

             wine_servings
country
Afghanistan            NaN
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0

In [7]:
type(alcohol)

pandas.core.frame.DataFrame

In [9]:
alcohol = pd.read_csv('https://www.andybek.com/pandas-drinks', usecols=['country', 'wine_servings'], index_col='country').squeeze("columns")
type(alcohol)

pandas.core.series.Series

In [9]:
alcohol.head()

country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
Name: wine_servings, dtype: float64

## 3. Series Sizing

In [10]:
alcohol.size

193

In [11]:
alcohol.values

array([ nan,  54.,  14., 312.,  45.,  45., 221.,  11., 212., 191.,   5.,
        51.,   7.,  nan,  36.,  42., 212.,   8.,  13.,  nan,   8.,   8.,
        35.,  16.,   1.,  94.,   7.,  nan,   7.,  16.,   1.,   4.,   1.,
         1.,   1., 172.,   8.,   3.,   1.,   9.,  74.,  11., 254.,   5.,
       113., 134.,  nan,   1., 278.,   3.,  26.,   9.,   3.,   1.,   2.,
       233.,  nan,  59.,  nan,   1.,  97.,  37.,  59.,   1., 149., 175.,
         1., 218.,  28.,   2.,   2.,  21.,   1.,   1.,   2., 185.,  78.,
        nan,  nan,  nan,  nan, 165.,   9., 237.,   9.,  16.,   1.,  12.,
         2.,   1.,  nan,   6., 123.,  62.,  31.,  nan,   2.,  nan,  56.,
       271.,   4.,   1.,  nan,  nan,   1.,  12.,  nan,  nan,  18.,   5.,
        18.,  nan,   8., 128.,   1.,   5.,  nan,   1.,   8.,  nan,  19.,
       175.,   1.,   1.,   2.,   7., 129.,   1.,  nan,  23.,  18.,   1.,
        74.,  21.,   1.,  56., 339.,   7.,   9.,  18., 167.,  73.,  nan,
        32.,  71.,  11.,  24.,  nan,  14.,  nan,   7., 127.,  51.,   2.,
        11., 116., 276.,   1.,  nan,  81., 112.,  nan,  nan,   7.,   2.,
       186.,  28.,  16.,  nan,   1.,  86.,   4.,  19.,   5.,   7.,   2.,
         7.,  32.,   9.,  nan,  45.,   5., 195.,   1.,  84.,  22.,   8.,
        11.,   3.,   1.,  nan,   4.,   4.])

In [12]:
alcohol.index

Index(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua & Barbuda', 'Argentina', 'Armenia', 'Australia', 'Austria',
       ...
       'Tanzania', 'USA', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela',
       'Vietnam', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype='object', name='country', length=193)

In [13]:
alcohol.shape

(193,)

In [14]:
alcohol.info

<bound method Series.info of country
Afghanistan      NaN
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            NaN
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64>

In [15]:
len(alcohol)

193

## 5. The count() Method

In [16]:
alcohol.count()

np.int64(162)

In [17]:
alcohol.hasnans

True

## 6. Accessing And Counting NAs

### Count No. of NaN: Way 1

In [18]:
alcohol.count()

np.int64(162)

In [19]:
alcohol.isnull()

country
Afghanistan     True
Albania        False
Algeria        False
Andorra        False
Angola         False
               ...
Venezuela      False
Vietnam        False
Yemen           True
Zambia         False
Zimbabwe       False
Name: wine_servings, Length: 193, dtype: bool

In [20]:
alcohol[alcohol.isnull()]

country
Afghanistan        NaN
Bangladesh         NaN
Bhutan             NaN
Burundi            NaN
North Korea        NaN
Eritrea            NaN
Ethiopia           NaN
India              NaN
Indonesia          NaN
Iran               NaN
Iraq               NaN
Kuwait             NaN
Lesotho            NaN
Libya              NaN
Malaysia           NaN
Maldives           NaN
Marshall Islands   NaN
Mauritania         NaN
Monaco             NaN
Myanmar            NaN
Nepal              NaN
Pakistan           NaN
Rwanda             NaN
San Marino         NaN
Saudi Arabia       NaN
Somalia            NaN
Sri Lanka          NaN
Sudan              NaN
Tajikistan         NaN
Uganda             NaN
Yemen              NaN
Name: wine_servings, dtype: float64

In [21]:
alcohol[alcohol.isnull()].value_counts(dropna=False)

wine_servings
NaN    31
Name: count, dtype: int64

### Count No. of NaN: Way 2

In [22]:
alcohol[alcohol.isnull()].size + alcohol.count()

np.int64(193)

In [23]:
alcohol.size

193

In [24]:
alcohol[alcohol.isnull()].index

Index(['Afghanistan', 'Bangladesh', 'Bhutan', 'Burundi', 'North Korea',
       'Eritrea', 'Ethiopia', 'India', 'Indonesia', 'Iran', 'Iraq', 'Kuwait',
       'Lesotho', 'Libya', 'Malaysia', 'Maldives', 'Marshall Islands',
       'Mauritania', 'Monaco', 'Myanmar', 'Nepal', 'Pakistan', 'Rwanda',
       'San Marino', 'Saudi Arabia', 'Somalia', 'Sri Lanka', 'Sudan',
       'Tajikistan', 'Uganda', 'Yemen'],
      dtype='object', name='country')

In [29]:
list(alcohol[alcohol.isnull()].index)

['Afghanistan',
 'Bangladesh',
 'Bhutan',
 'Burundi',
 'North Korea',
 'Eritrea',
 'Ethiopia',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Kuwait',
 'Lesotho',
 'Libya',
 'Malaysia',
 'Maldives',
 'Marshall Islands',
 'Mauritania',
 'Monaco',
 'Myanmar',
 'Nepal',
 'Pakistan',
 'Rwanda',
 'San Marino',
 'Saudi Arabia',
 'Somalia',
 'Sri Lanka',
 'Sudan',
 'Tajikistan',
 'Uganda',
 'Yemen']

In [28]:
len(list(alcohol[alcohol.isnull()].index))

31

### Count No. of NaN: Way 3

In [35]:
pd.Series([False,True,True]).sum()

np.int64(2)

In [34]:
alcohol.isnull().sum()

np.int64(31)

## 8. The Other Side notnull() And notna()

In [43]:
alcohol.notna().sum()

np.int64(162)

In [39]:
alcohol.notna().sum()+ alcohol.isnull().sum()

np.int64(193)

In [42]:
alcohol.size

193

## 10. Skill Challenge

### 1. Isolate the non-nulls in the **alcohol** series

In [48]:
wine_serving = alcohol[alcohol.notnull()]

### 2. What is the total wine consume by each contries in wine_serving

In [47]:
wine_serving

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [53]:
wine_serving.sum()

np.float64(8221.0)

### 3. Show total less than wine consume by contries

In [52]:
wine_serving < 100

country
Albania               True
Algeria               True
Andorra              False
Angola                True
Antigua & Barbuda     True
                     ...
Vanuatu               True
Venezuela             True
Vietnam               True
Zambia                True
Zimbabwe              True
Name: wine_servings, Length: 162, dtype: bool

In [51]:
wine_serving[wine_serving < 100]

country
Albania              54.0
Algeria              14.0
Angola               45.0
Antigua & Barbuda    45.0
Armenia              11.0
                     ...
Vanuatu              11.0
Venezuela             3.0
Vietnam               1.0
Zambia                4.0
Zimbabwe              4.0
Name: wine_servings, Length: 132, dtype: float64

In [54]:
wine_serving[wine_serving < 100].sum()

np.float64(2416.0)

## 12. Dropping and Filling NAs

In [56]:
alcohol.dropna()

country
Albania               54.0
Algeria               14.0
Andorra              312.0
Angola                45.0
Antigua & Barbuda     45.0
                     ...
Vanuatu               11.0
Venezuela              3.0
Vietnam                1.0
Zambia                 4.0
Zimbabwe               4.0
Name: wine_servings, Length: 162, dtype: float64

In [60]:
temp = alcohol.fillna(0)
temp

country
Afghanistan      0.0
Albania         54.0
Algeria         14.0
Andorra        312.0
Angola          45.0
               ...
Venezuela        3.0
Vietnam          1.0
Yemen            0.0
Zambia           4.0
Zimbabwe         4.0
Name: wine_servings, Length: 193, dtype: float64

In [62]:
temp[temp == 0].size

31

In [63]:
temp[temp != 0].size

162

## 13.Descriptive statistics

In [66]:
alcohol.mean()

np.float64(50.74691358024691)

In [67]:
# return middle ELEMENT AFTER SORTED VALUE
alcohol.median()

11.5

In [72]:
# return most repeated value
alcohol.mode()

0    1.0
Name: wine_servings, dtype: float64

In [68]:
alcohol.min()

1.0

In [69]:
alcohol.max()

339.0

In [70]:
alcohol.describe()

count    162.000000
mean      50.746914
std       76.134917
min        1.000000
25%        3.000000
50%       11.500000
75%       61.250000
max      339.000000
Name: wine_servings, dtype: float64

## 14. mode() and count that value

In [73]:
alcohol.mode()

0    1.0
Name: wine_servings, dtype: float64

In [74]:
alcohol == 1

country
Afghanistan    False
Albania        False
Algeria        False
Andorra        False
Angola         False
               ...
Venezuela      False
Vietnam         True
Yemen          False
Zambia         False
Zimbabwe       False
Name: wine_servings, Length: 193, dtype: bool

In [77]:
# count of that mode value
alcohol[alcohol==1].size

28

In [80]:
alcohol.value_counts()

wine_servings
1.0      28
2.0      10
7.0       9
8.0       7
5.0       6
         ..
218.0     1
185.0     1
78.0      1
165.0     1
22.0      1
Name: count, Length: 71, dtype: int64

## 16. idxmax() And idxmin()

### way 1

In [82]:
alcohol.max()

339.0

In [81]:
alcohol == alcohol.max()

country
Afghanistan    False
Albania        False
Algeria        False
Andorra        False
Angola         False
               ...
Venezuela      False
Vietnam        False
Yemen          False
Zambia         False
Zimbabwe       False
Name: wine_servings, Length: 193, dtype: bool

In [83]:
alcohol[alcohol == alcohol.max()]

country
Portugal    339.0
Name: wine_servings, dtype: float64

In [84]:
alcohol[alcohol == alcohol.max()].index[0]

'Portugal'

### way 2

In [86]:
alcohol.idxmax()

'Portugal'

In [87]:
alcohol.idxmin()

'Brunei'

### but

In [88]:
alcohol[alcohol==alcohol.min()].value_counts()

wine_servings
1.0    28
Name: count, dtype: int64

In [89]:
alcohol[alcohol==alcohol.min()]

country
Brunei                      1.0
Cambodia                    1.0
Canada                      1.0
Central African Republic    1.0
Chad                        1.0
Comoros                     1.0
DR Congo                    1.0
Egypt                       1.0
Fiji                        1.0
Gambia                      1.0
Ghana                       1.0
Guyana                      1.0
Haiti                       1.0
Jordan                      1.0
Kiribati                    1.0
Malawi                      1.0
Mali                        1.0
Morocco                     1.0
Namibia                     1.0
Nicaragua                   1.0
Niger                       1.0
Oman                        1.0
Papua New Guinea            1.0
Philippines                 1.0
Solomon Islands             1.0
Thailand                    1.0
Tanzania                    1.0
Vietnam                     1.0
Name: wine_servings, dtype: float64

## 17. Sorting

In [93]:
alcohol.sort_values()

country
Thailand           1.0
Solomon Islands    1.0
Brunei             1.0
Haiti              1.0
Cambodia           1.0
                  ...
Sri Lanka          NaN
Sudan              NaN
Tajikistan         NaN
Uganda             NaN
Yemen              NaN
Name: wine_servings, Length: 193, dtype: float64

In [10]:
alcohol[alcohol.notnull()].sort_values()

country
Thailand             1.0
Solomon Islands      1.0
Brunei               1.0
Haiti                1.0
Cambodia             1.0
                   ...
Luxembourg         271.0
Slovenia           276.0
Denmark            278.0
Andorra            312.0
Portugal           339.0
Name: wine_servings, Length: 162, dtype: float64

In [95]:
alcohol[alcohol.notnull()].sort_values().head(30)

country
Thailand                    1.0
Solomon Islands             1.0
Brunei                      1.0
Haiti                       1.0
Cambodia                    1.0
Guyana                      1.0
Canada                      1.0
Jordan                      1.0
Central African Republic    1.0
Comoros                     1.0
Ghana                       1.0
Gambia                      1.0
Fiji                        1.0
Egypt                       1.0
DR Congo                    1.0
Chad                        1.0
Kiribati                    1.0
Tanzania                    1.0
Philippines                 1.0
Vietnam                     1.0
Papua New Guinea            1.0
Oman                        1.0
Malawi                      1.0
Mali                        1.0
Morocco                     1.0
Namibia                     1.0
Nicaragua                   1.0
Niger                       1.0
Kenya                       2.0
El Salvador                 2.0
Name: wine_servings, dtype: float64