### 2. Our Data

In [1]:
import pandas as pd
import numpy as np

url: https://andybek.com/pandas-marathon

In [2]:
boston = pd.read_csv('https://andybek.com/pandas-marathon')
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           1000 non-null   object
 1   Age            1000 non-null   int64
 2   M/F            1000 non-null   object
 3   City           1000 non-null   object
 4   State          807 non-null    object
 5   Country        1000 non-null   object
 6   Official Time  1000 non-null   object
 7   Overall        1000 non-null   int64
 8   Gender         1000 non-null   int64
 9   Years Ran      315 non-null    object
dtypes: int64(3), object(7)
memory usage: 78.3+ KB

### 3. String manupulation in py

#### **Agenda**:
    - len
    - center
    - startswith, endswith
    - the 'in' operator
    - list comprehensions

In [3]:
s = 'Hellow my self sultan'

In [4]:
len(s)

21

In [13]:
s.center(50, '*')

'**************Hellow my self sultan***************'

In [14]:
s.center(23, '*')

'*Hellow my self sultan*'

In [15]:
s.center(20, '*')

'Hellow my self sultan'

In [17]:



s

'Hellow my self sultan'

In [19]:
s.startswith('H')

True

In [20]:
s.startswith('Hellow ')

True

In [21]:
s.endswith('n')

True

In [22]:
s.endswith('tan')

True

In [23]:
# 'in' operator for check includes

In [24]:



s

'Hellow my self sultan'

In [26]:
'my' in s

True

In [27]:
'Tultan' in s

False

#### - list comprehensions 

##### but it throws error if NA values present in list or array

In [28]:
names = ["Sultan", "Rahul", "Amit", "Priya", "Neha"]

In [29]:
[len(n) for n in names]

[6, 5, 4, 5, 4]

In [30]:
['t' in n for n in names]

[True, False, True, False, False]

In [32]:
[n.center(10,'_') for n in names]

['__Sultan__', '__Rahul___', '___Amit___', '__Priya___', '___Neha___']

### 4. Vectorized String Operation In pd

In [33]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
0,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,2:09:37,1,1,NaN
1,"Rupp, Galen",30,M,Portland,OR,USA,2:09:58,2,2,NaN
2,"Osako, Suguru",25,M,Machida-City,NaN,JPN,2:10:28,3,3,NaN
3,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,2:12:08,4,4,NaN
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,2015

In [35]:
boston.Name.iloc[0]

' Kirui, Geoffrey '

In [36]:
len(boston.Name.iloc[0])

17

In [38]:
boston.Name

0         Kirui, Geoffrey
1           Rupp, Galen
2          Osako, Suguru
3         Biwott, Shadrack
4           Chebet, Wilson
              ...
995           Larosa, Mark
996    Williamson, Jerry A
997        Mccue, Daniel T
998           Larosa, John
999         Sanchez, Sam R
Name: Name, Length: 1000, dtype: object

In [39]:
len(boston.Name)

1000

In [40]:
boston.Name.str.len()

0      17
1      14
2      15
3      16
4      14
       ..
995    12
996    19
997    15
998    12
999    14
Name: Name, Length: 1000, dtype: int64

In [41]:
boston.Name.str.startswith("A")

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Name: Name, Length: 1000, dtype: bool

In [42]:
boston.Name.str.endswith("A")

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996     True
997    False
998    False
999    False
Name: Name, Length: 1000, dtype: bool

In [43]:
boston.Name.str.center(20, "_")

0      _ Kirui, Geoffrey __
1      ___Rupp, Galen   ___
2      __Osako, Suguru  ___
3      __Biwott, Shadrack__
4      ___Chebet, Wilson___
               ...
995    ____Larosa, Mark____
996    Williamson, Jerry A_
997    __Mccue, Daniel T___
998    ____Larosa, John____
999    ___Sanchez, Sam R___
Name: Name, Length: 1000, dtype: object

### 5. Cas Operation

In [44]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
0,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,2:09:37,1,1,NaN
1,"Rupp, Galen",30,M,Portland,OR,USA,2:09:58,2,2,NaN
2,"Osako, Suguru",25,M,Machida-City,NaN,JPN,2:10:28,3,3,NaN
3,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,2:12:08,4,4,NaN
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,2015

In [45]:
boston.City

0           Keringet
1           Portland
2       Machida-City
3      Mammoth Lakes
4           Marakwet
           ...
995    North Andover
996          Raleigh
997        Arlington
998          Danbury
999         Santa Fe
Name: City, Length: 1000, dtype: object

In [46]:
boston.City.str.lower()

0           keringet
1           portland
2       machida-city
3      mammoth lakes
4           marakwet
           ...
995    north andover
996          raleigh
997        arlington
998          danbury
999         santa fe
Name: City, Length: 1000, dtype: object

In [47]:
boston.City.str.upper()

0           KERINGET
1           PORTLAND
2       MACHIDA-CITY
3      MAMMOTH LAKES
4           MARAKWET
           ...
995    NORTH ANDOVER
996          RALEIGH
997        ARLINGTON
998          DANBURY
999         SANTA FE
Name: City, Length: 1000, dtype: object

In [48]:
boston.City.str.title()

0           Keringet
1           Portland
2       Machida-City
3      Mammoth Lakes
4           Marakwet
           ...
995    North Andover
996          Raleigh
997        Arlington
998          Danbury
999         Santa Fe
Name: City, Length: 1000, dtype: object

### 6. Finding Characters and Words

#### **Agenda**:
    - find()
    - rfind() in py and pd

In [51]:
s

'Hellow my self sultan'

In [53]:
s.find('w')

5

In [54]:
s.find('self')

10

In [55]:
s.find('z')

-1

In [56]:
boston.head()

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
0,"Kirui, Geoffrey",24,M,Keringet,NaN,KEN,2:09:37,1,1,NaN
1,"Rupp, Galen",30,M,Portland,OR,USA,2:09:58,2,2,NaN
2,"Osako, Suguru",25,M,Machida-City,NaN,JPN,2:10:28,3,3,NaN
3,"Biwott, Shadrack",32,M,Mammoth Lakes,CA,USA,2:12:08,4,4,NaN
4,"Chebet, Wilson",31,M,Marakwet,NaN,KEN,2:12:35,5,5,2015

In [57]:
boston.Name

0         Kirui, Geoffrey
1           Rupp, Galen
2          Osako, Suguru
3         Biwott, Shadrack
4           Chebet, Wilson
              ...
995           Larosa, Mark
996    Williamson, Jerry A
997        Mccue, Daniel T
998           Larosa, John
999         Sanchez, Sam R
Name: Name, Length: 1000, dtype: object

##### Find '**Mark**' in all name

In [58]:
boston.Name.str.find('Mark')

0     -1
1     -1
2     -1
3     -1
4     -1
      ..
995    8
996   -1
997   -1
998   -1
999   -1
Name: Name, Length: 1000, dtype: int64

In [59]:
condition = boston.Name.str.find('Mark') != -1
boston[condition]

,Name,Age,M/F,City,State,Country,Official Time,Overall,Gender,Years Ran
88,"Jones, Mark T",30,M,Boulder,CO,USA,2:33:56,89,79,NaN
296,"Puleo, Mark",21,M,Woburn,MA,USA,2:44:02,297,271,NaN
531,"Rabasco, Mark T.",22,M,Pittsfield,MA,USA,2:49:17,532,495,NaN
609,"Heerensperger, Mark E",38,M,Austin,TX,USA,2:50:30,610,570,2016
758,"Angus, Mark E",37,M,Toronto,ON,CAN,2:52:56,759,715,NaN
759,"Buckner, Mark L.",33,M,Salt Lake City,UT,USA,2:52:57,760,716,2016
880,"Egge, Mark",30,M,Cheyenne,WY,USA,2:54:46,881,832,NaN
987,"Cucuzzella, Mark",50,M,Shepherdstown,WV,USA,2:56:03,988,932,2016
995,"Larosa, Mark",38,M,North Andover,MA,USA,2:56:06,996,940,2015:2016

In [60]:
s

'Hellow my self sultan'

In [63]:
s.find('w')

5

In [62]:
s.rfind('w')

5

In [64]:
s.find('s')

10

In [65]:
s.rfind('s')

15

### 7. Strips And Whitespace

#### **Agenda**:
    - isspace()
    - lstrip()
    - rstrip()
    - strip()

In [66]:
' '.isspace()

True

In [67]:
'\n'.isspace()

True

In [68]:
'\t'.isspace()

True

In [69]:
l_space = '     this is a pandas course'

In [70]:
r_space = 'we cover plenty of python tools     '

In [71]:
both_space = ' the name is: BOND \t JAMES BOND \n\n     '

In [74]:
both_space

' the name is: BOND \t JAMES BOND \n\n     '

In [75]:
print(both_space)

 the name is: BOND 	 JAMES BOND

##### Now time to clean up the spaces

In [76]:
l_space.lstrip()

'this is a pandas course'

In [77]:
r_space.rstrip()

'we cover plenty of python tools'

In [79]:
both_space.strip()

'the name is: BOND \t JAMES BOND'

In [81]:
both_space.strip() ## '\t' not get remove, we will cover in future fuck's

'the name is: BOND \t JAMES BOND'

##### Now time to clean up the spaces from name of boston df

In [82]:
boston.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           1000 non-null   object
 1   Age            1000 non-null   int64
 2   M/F            1000 non-null   object
 3   City           1000 non-null   object
 4   State          807 non-null    object
 5   Country        1000 non-null   object
 6   Official Time  1000 non-null   object
 7   Overall        1000 non-null   int64
 8   Gender         1000 non-null   int64
 9   Years Ran      315 non-null    object
dtypes: int64(3), object(7)
memory usage: 78.3+ KB

In [83]:
boston.Name

0         Kirui, Geoffrey
1           Rupp, Galen
2          Osako, Suguru
3         Biwott, Shadrack
4           Chebet, Wilson
              ...
995           Larosa, Mark
996    Williamson, Jerry A
997        Mccue, Daniel T
998           Larosa, John
999         Sanchez, Sam R
Name: Name, Length: 1000, dtype: object

In [84]:
boston.Name.iloc[0]

' Kirui, Geoffrey '

In [85]:
boston.Name.str.strip()

0          Kirui, Geoffrey
1              Rupp, Galen
2            Osako, Suguru
3         Biwott, Shadrack
4           Chebet, Wilson
              ...
995           Larosa, Mark
996    Williamson, Jerry A
997        Mccue, Daniel T
998           Larosa, John
999         Sanchez, Sam R
Name: Name, Length: 1000, dtype: object

In [86]:
boston.Name.str.strip().iloc[0]

'Kirui, Geoffrey'

In [87]:
boston.Name = boston.Name.str.strip()

In [88]:
boston.Name.iloc[0]

'Kirui, Geoffrey'

### 7. Strips And Whitespace