### 2. New Data

In [9]:
import pandas as pd
import numpy as np

sat_df = pd.read_csv(r"https://andybek.com/pandas-sat")
sat_df.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.00%,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.00%,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.00%,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.90%,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.90%,Reading,422

In [10]:
sat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Name         1125 non-null   object
 1   Borough             1125 non-null   object
 2   Student Enrollment  1125 non-null   int64
 3   Percent Tested      1125 non-null   object
 4   SAT Section         1125 non-null   object
 5   Score               1125 non-null   int64
dtypes: int64(2), object(4)
memory usage: 52.9+ KB

In [11]:
# remove % from Percent Tested column
sat_df.loc[:,'Percent Tested'].replace('%','',regex=True).astype(float)

0        74.0
1        74.0
2        74.0
3        54.9
4        54.9
        ...
1120    100.0
1121    100.0
1122     90.4
1123     90.4
1124     90.4
Name: Percent Tested, Length: 1125, dtype: float64

In [12]:
# remove % from Percent Tested column
sat_df.loc[:,'Percent Tested'] = sat_df.loc[:,'Percent Tested'].str.replace('%','',regex=True).astype(float)
sat_df.loc[:,'Percent Tested']

0        74.0
1        74.0
2        74.0
3        54.9
4        54.9
        ...
1120    100.0
1121    100.0
1122     90.4
1123     90.4
1124     90.4
Name: Percent Tested, Length: 1125, dtype: object

In [13]:
sat_df['Percent Tested'].map(type).value_counts()

Percent Tested
<class 'float'>    1125
Name: count, dtype: int64

In [16]:
sat_df['Percent Tested'] = pd.to_numeric(
    sat_df['Percent Tested']
)

In [17]:
sat_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   School Name         1125 non-null   object
 1   Borough             1125 non-null   object
 2   Student Enrollment  1125 non-null   int64
 3   Percent Tested      1125 non-null   float64
 4   SAT Section         1125 non-null   object
 5   Score               1125 non-null   int64
dtypes: float64(1), int64(2), object(3)
memory usage: 52.9+ KB

### 3. Pivoting Data

In [18]:
sat = sat_df
sat.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422

In [21]:
sat.pivot(index='School Name',columns=['SAT Section'], values='Score')

SAT Section                                         Math  Reading  Writing
School Name
A. Philip Randolph Campus High School                459      453      447
ACORN Community High School                          379      395      385
Abraham Lincoln High School                          441      422      422
Academy for Careers in Television and Film           444      458      444
Academy for College Preparation and Career Expl...   386      397      393
...                                                  ...      ...      ...
World Journalism Preparatory (College Board)         484      491      487
York Early College Academy                           496      481      473
Young Women's Leadership School                      478      465      472
Young Women's Leadership School in Astoria           483      464      477
Young Women's Leadership School in Queens            415      420      433

[375 rows x 3 columns]

#### try to do without pivot

In [24]:
sat = sat.set_index(['School Name','SAT Section'])
sat.head()

                                                     Borough  \
School Name                           SAT Section
A. Philip Randolph Campus High School Math         Manhattan
                                      Reading      Manhattan
                                      Writing      Manhattan
Abraham Lincoln High School           Math          Brooklyn
                                      Reading       Brooklyn

                                                   Student Enrollment  \
School Name                           SAT Section
A. Philip Randolph Campus High School Math                       1354
                                      Reading                    1354
                                      Writing                    1354
Abraham Lincoln High School           Math                       2341
                                      Reading                    2341

                                                   Percent Tested  Score
School Name                           SAT Section
A. Philip Randolph Campus High School Math                   74.0    459
                                      Reading                74.0    453
                                      Writing                74.0    447
Abraham Lincoln High School           Math                   54.9    441
                                      Reading                54.9    422

In [25]:
sat.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 1125 entries, ('A. Philip Randolph Campus High School', 'Math') to ("Young Women's Leadership School in Queens", 'Writing')
Data columns (total 4 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Borough             1125 non-null   object
 1   Student Enrollment  1125 non-null   int64
 2   Percent Tested      1125 non-null   float64
 3   Score               1125 non-null   int64
dtypes: float64(1), int64(2), object(1)
memory usage: 49.7+ KB

In [28]:
sat.iloc[:,[3]].unstack(level=1)
# unsatack use for coverst index into col
# level=(0, 1)=('School Name', 'SAT Section')

                                                   Score
SAT Section                                         Math Reading Writing
School Name
A. Philip Randolph Campus High School                459     453     447
ACORN Community High School                          379     395     385
Abraham Lincoln High School                          441     422     422
Academy for Careers in Television and Film           444     458     444
Academy for College Preparation and Career Expl...   386     397     393
...                                                  ...     ...     ...
World Journalism Preparatory (College Board)         484     491     487
York Early College Academy                           496     481     473
Young Women's Leadership School                      478     465     472
Young Women's Leadership School in Astoria           483     464     477
Young Women's Leadership School in Queens            415     420     433

[375 rows x 3 columns]

### 4. Undoing Pivots

In [33]:
pivoted = sat_df.pivot(index='School Name',columns=['SAT Section'], values='Score')
pivoted.head()

SAT Section                                         Math  Reading  Writing
School Name
A. Philip Randolph Campus High School                459      453      447
ACORN Community High School                          379      395      385
Abraham Lincoln High School                          441      422      422
Academy for Careers in Television and Film           444      458      444
Academy for College Preparation and Career Expl...   386      397      393

In [42]:
# melt use for undo pviot
# but we lost index school name
pivoted.melt()

     SAT Section  value
0           Math    459
1           Math    379
2           Math    441
3           Math    444
4           Math    386
...          ...    ...
1120     Writing    487
1121     Writing    473
1122     Writing    472
1123     Writing    477
1124     Writing    433

[1125 rows x 2 columns]

In [43]:
pivoted.reset_index()

SAT Section,School Name,Math,Reading,Writing
0,A. Philip Randolph Campus High School,459,453,447
1,ACORN Community High School,379,395,385
2,Abraham Lincoln High School,441,422,422
3,Academy for Careers in Television and Film,444,458,444
4,Academy for College Preparation and Career Exp...,386,397,393
...,...,...,...,...
370,World Journalism Preparatory (College Board),484,491,487
371,York Early College Academy,496,481,473
372,Young Women's Leadership School,478,465,472
373,Young Women's Leadership School in Astoria,483,464,477
374,Young Women's Leadership School in Queens,415,420,433

In [44]:
# produse wrong output
pivoted.reset_index().melt()

      SAT Section                                              value
0     School Name              A. Philip Randolph Campus High School
1     School Name                        ACORN Community High School
2     School Name                        Abraham Lincoln High School
3     School Name         Academy for Careers in Television and Film
4     School Name  Academy for College Preparation and Career Exp...
...           ...                                                ...
1495      Writing                                                487
1496      Writing                                                473
1497      Writing                                                472
1498      Writing                                                477
1499      Writing                                                433

[1500 rows x 2 columns]

In [47]:
pivoted.reset_index().melt(id_vars='School Name') 
# we get desire output but score column name become value
# so we need to change that value name to acording to us that we can do easily

                                            School Name SAT Section  value
0                 A. Philip Randolph Campus High School        Math    459
1                           ACORN Community High School        Math    379
2                           Abraham Lincoln High School        Math    441
3            Academy for Careers in Television and Film        Math    444
4     Academy for College Preparation and Career Exp...        Math    386
...                                                 ...         ...    ...
1120       World Journalism Preparatory (College Board)     Writing    487
1121                         York Early College Academy     Writing    473
1122                    Young Women's Leadership School     Writing    472
1123         Young Women's Leadership School in Astoria     Writing    477
1124          Young Women's Leadership School in Queens     Writing    433

[1125 rows x 3 columns]

### 5. What About Aggregates

In [48]:
sat_df.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422

#### What is average Borough score as per Sat section

In [53]:
sat_df.pivot(index='Borough',columns='SAT Section', values='Score') # it shows duplicate index error

ValueError: Index contains duplicate entries, cannot reshape

### 6. The pivot_table()

In [54]:
sat_df.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422

#### What is average Borough score as per Sat section

In [59]:
sat_df.pivot_table(index='Borough', columns='SAT Section', values='Score') # isko duplicates chalta

SAT Section          Math     Reading     Writing
Borough
Bronx          404.357143  402.520408  395.846939
Brooklyn       416.403670  410.761468  403.091743
Manhattan      455.887640  444.932584  439.314607
Queens         462.362319  443.260870  439.855072
Staten Island  486.200000  478.500000  474.300000

In [60]:
sat_df.pivot_table(index='Borough', columns='SAT Section', values='Score', aggfunc='mean') # aggrigate fuction

SAT Section          Math     Reading     Writing
Borough
Bronx          404.357143  402.520408  395.846939
Brooklyn       416.403670  410.761468  403.091743
Manhattan      455.887640  444.932584  439.314607
Queens         462.362319  443.260870  439.855072
Staten Island  486.200000  478.500000  474.300000

In [61]:
sat_df.pivot_table(index='Borough', columns='SAT Section', values='Score', aggfunc=['sum','count']) # aggrigate fuction

                 sum                 count
SAT Section     Math Reading Writing  Math Reading Writing
Borough
Bronx          39627   39447   38793    98      98      98
Brooklyn       45388   44773   43937   109     109     109
Manhattan      40574   39599   39099    89      89      89
Queens         31903   30585   30350    69      69      69
Staten Island   4862    4785    4743    10      10      10

#### What is average Percent Tested for Borough?

In [64]:
sat_df\
    .pivot_table(index='Borough',values='Percent Tested')\
    .sort_values(by='Percent Tested')

               Percent Tested
Borough
Bronx               58.220408
Brooklyn            62.423853
Staten Island       67.390000
Queens              69.036232
Manhattan           71.197753

### 8. Replicating Pivot Tables With GroupBy

In [66]:
sat_df.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422

In [67]:
sat_df.pivot_table(index='Borough', columns='SAT Section', values='Score')

SAT Section          Math     Reading     Writing
Borough
Bronx          404.357143  402.520408  395.846939
Brooklyn       416.403670  410.761468  403.091743
Manhattan      455.887640  444.932584  439.314607
Queens         462.362319  443.260870  439.855072
Staten Island  486.200000  478.500000  474.300000

In [68]:
sat_df.groupby(['Borough','SAT Section']).agg({'Score':'mean'})

                                Score
Borough       SAT Section
Bronx         Math         404.357143
              Reading      402.520408
              Writing      395.846939
Brooklyn      Math         416.403670
              Reading      410.761468
              Writing      403.091743
Manhattan     Math         455.887640
              Reading      444.932584
              Writing      439.314607
Queens        Math         462.362319
              Reading      443.260870
              Writing      439.855072
Staten Island Math         486.200000
              Reading      478.500000
              Writing      474.300000

In [69]:
sat_df.groupby(['Borough','SAT Section']).agg({'Score':'mean'}).unstack(level=1)

                    Score
SAT Section          Math     Reading     Writing
Borough
Bronx          404.357143  402.520408  395.846939
Brooklyn       416.403670  410.761468  403.091743
Manhattan      455.887640  444.932584  439.314607
Queens         462.362319  443.260870  439.855072
Staten Island  486.200000  478.500000  474.300000

### 12. Skill Challenge

#### 1. 
Starting with our main dataframe, create pivot table that summarizes the total student enrollment across all 5 broughts have. 

Which boroughs have the highest and lowest high school student bodies?

In [70]:
sat_df.head()

,School Name,Borough,Student Enrollment,Percent Tested,SAT Section,Score
0,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Math,459
1,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Reading,453
2,A. Philip Randolph Campus High School,Manhattan,1354,74.0,Writing,447
3,Abraham Lincoln High School,Brooklyn,2341,54.9,Math,441
4,Abraham Lincoln High School,Brooklyn,2341,54.9,Reading,422

In [73]:
sat_df\
    .pivot_table(index='Borough', values='Student Enrollment')\
    .sort_values(by='Student Enrollment')

               Student Enrollment
Borough
Bronx                  541.724490
Manhattan              638.089888
Brooklyn               742.550459
Queens                1122.884058
Staten Island         1846.000000

#### 1. 
Starting with our main dataframe, create pivot table that summarizes the total student enrollment across all 5 broughts have. 

Which boroughs have the highest and lowest high school student bodies?