### 11. 2d Indexing

In [49]:
import pandas as pd
import numpy as np
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.head(6)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0

In [50]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

In [51]:
players.club.unique()

array(['Arsenal', 'Bournemouth', 'Brighton+and+Hove', 'Burnley',
       'Chelsea', 'Crystal+Palace', 'Everton', 'Huddersfield',
       'Leicester+City', 'Liverpool', 'Manchester+City',
       'Manchester+United', 'Newcastle+United', 'Southampton',
       'Stoke+City', 'Swansea', 'Tottenham', 'Watford', 'West+Brom',
       'West+Ham'], dtype=object)

In [52]:
# Chelsea players which has age of 23 years or younger
condition_1 = (players.club == 'Chelsea') & (players.age <= 23)
players[condition_1]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
110,Michy Batshuayi,Chelsea,23,CF,1,25.0,1162,8.5,1.60%,48,2,Belgium,0,2,5,1,1
111,Kurt Zouma,Chelsea,22,CB,3,15.0,723,5.5,0.80%,15,2,France,0,2,5,1,0
112,Kenedy,Chelsea,21,LB,3,7.0,566,5.0,0.10%,3,3,Brazil,0,1,5,1,0
115,Tiemoue Bakayoko,Chelsea,22,DM,2,16.0,1011,5.0,1.60%,0,2,France,1,2,5,1,0

In [53]:
coll_arr = ['name', 'club', 'age', 'position', 'market_value']
players.loc[condition_1, coll_arr]

                 name     club  age position  market_value
110   Michy Batshuayi  Chelsea   23       CF          25.0
111        Kurt Zouma  Chelsea   22       CB          15.0
112            Kenedy  Chelsea   21       LB           7.0
115  Tiemoue Bakayoko  Chelsea   22       DM          16.0

### 13. Sorting By Index Or Colm

In [54]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

In [55]:
players.sort_values(by=['market_value'], ascending=False)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
96,Eden Hazard,Chelsea,26,LW,1,75.00,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.00,7435,8.0,19.50%,115,2,France,0,2,12,1,1
0,Alexis Sanchez,Arsenal,28,LW,1,65.00,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.00,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.00,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,Joel Castro Pereira,Manchester+United,21,GK,4,0.10,395,4.0,1.00%,6,2,Portugal,0,1,12,1,0
113,Eduardo Carvalho,Chelsea,34,LW,1,0.05,467,5.0,0.10%,0,2,Portugal,0,6,5,1,1
30,Granit Xhaka,Arsenal,24,NaN,2,NaN,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
192,Steve Mounie,Huddersfield,22,CF,1,NaN,56,6.0,0.60%,0,2,Benin,0,2,8,0,0
195,Kasper Schmeichel,Leicester+City,30,GK,4,NaN,1601,5.0,2.40%,109,2,Denmark,0,4,9,0,0

players.set_index('name',inplace=True)

In [56]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [57]:
players.sort_index()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [58]:
players.sort_index(axis=1)

,age,age_cat,big_club,club,club_id,fpl_points,fpl_sel,fpl_value,market_value,name,nationality,new_foreign,new_signing,page_views,position,position_cat,region
0,28,4,1,Arsenal,1,264,17.10%,12.0,65.0,Alexis Sanchez,Chile,0,0,4329,LW,1,3
1,28,4,1,Arsenal,1,167,5.60%,9.5,50.0,Mesut Ozil,Germany,0,0,4395,AM,1,2
2,35,6,1,Arsenal,1,134,5.90%,5.5,7.0,Petr Cech,Czech Republic,0,0,1529,GK,4,2
3,28,4,1,Arsenal,1,122,1.50%,7.5,20.0,Theo Walcott,England,0,0,2393,RW,1,1
4,31,4,1,Arsenal,1,121,0.70%,6.0,22.0,Laurent Koscielny,France,0,0,912,CB,3,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,21,1,0,West+Ham,20,38,0.40%,4.5,5.0,Edimilson Fernandes,Switzerland,0,1,288,CM,2,2
461,23,2,0,West+Ham,20,34,0.20%,4.5,7.0,Arthur Masuaku,Congo DR,0,1,199,LB,3,4
462,23,2,0,West+Ham,20,29,0.30%,4.5,4.5,Sam Byram,England,0,0,198,RB,3,1
463,21,1,0,West+Ham,20,16,5.90%,4.5,1.0,Ashley Fletcher,England,0,1,412,CF,1,1
464,27,3,0,West+Ham,20,12,0.10%,5.5,10.0,Diafra Sakho,Senegal,0,0,214,CF,1,4

In [59]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [60]:
players.reset_index()

,index,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,460,Edimilson Fernandes,West+Ham,21,CM,2,5.0,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,463,Ashley Fletcher,West+Ham,21,CF,1,1.0,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,464,Diafra Sakho,West+Ham,27,CF,1,10.0,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

### 17. Skill Challenge

#### 1. Sort the players datame by age in ascending order. Who is the youngest footballer in the EPL

In [61]:
players.sort_values(by=['age']).head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
237,Ben Woodburn,Liverpool,17,LW,1,1.5,1241,4.5,0.10%,5,1,Wales,0,1,10,1,0
354,Josh Tymon,Stoke+City,18,LB,3,1.0,120,4.5,0.10%,9,1,England,0,1,15,0,0
439,Jonathan Leko,West+Brom,18,RW,1,1.5,169,4.5,0.20%,12,1,England,0,1,19,0,0
235,Trent Alexander-Arnold,Liverpool,18,RB,3,1.5,327,4.5,0.30%,15,2,England,0,1,10,1,0
274,Marcus Rashford,Manchester+United,19,CF,1,18.0,3668,7.5,4.80%,76,1,England,0,1,12,1,0

#### 2. Set the club colm as index of the DF. Then sort the dataframe index in alphabetical order.

In [65]:
# players.set_index('club',inplace=True)
players.set_index('club',inplace=True)

In [66]:
# players.set_index('club',inplace=True)
players.sort_index().head()

,name,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
club,,,,,,,,,,,,,,,,
Arsenal,Alexis Sanchez,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
Arsenal,Mesut Ozil,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
Arsenal,Petr Cech,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
Arsenal,Theo Walcott,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
Arsenal,Laurent Koscielny,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [70]:
players = players.reset_index()

#### 3. Sort the df values by club and market_value where the club is alphabetical and the market value is descending order.

In [72]:
players.sort_values(by=['club','market_value'], ascending=[True,False]).head()

,club,name,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Arsenal,Alexis Sanchez,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Arsenal,Mesut Ozil,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
31,Arsenal,Alexandre Lacazette,26,CF,1,40.0,1183,10.5,26.50%,0,2,France,1,3,1,1,0
10,Arsenal,Granit Xhaka,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0
11,Arsenal,Granit Xhaka,24,DM,2,35.0,1815,5.5,2.00%,85,2,Switzerland,0,2,1,1,0