## 2. Inro to new Data Set

In [2]:
import pandas as pd
import numpy as np
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.head(6)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0

In [3]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

In [4]:
players.info(False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Columns: 17 entries, name to new_signing
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

## 3. Quick Review: Indexing with Boolean Mask

In [5]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [6]:
# Q: What are the players that have market value exceeding the 40M?

In [7]:
players[players.loc[:,'market_value']>40]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
96,Eden Hazard,Chelsea,26,LW,1,75.0,4220,10.5,2.30%,224,2,Belgium,0,3,5,1,0
97,Diego Costa,Chelsea,28,CF,1,50.0,4454,10.0,3.00%,196,2,Spain,0,4,5,1,0
108,N%27Golo Kante,Chelsea,26,DM,2,50.0,4042,5.0,13.80%,83,2,France,0,3,5,1,1
218,Philippe Coutinho,Liverpool,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0
244,Kevin De Bruyne,Manchester+City,26,AM,1,65.0,2252,10.0,17.50%,199,2,Belgium,0,3,11,1,0
245,Sergio Aguero,Manchester+City,29,CF,1,65.0,4046,11.5,9.70%,175,3,Argentina,0,4,11,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
264,Romelu Lukaku,Manchester+United,24,CF,1,50.0,3727,11.5,45.00%,221,2,Belgium,0,2,12,1,0
267,Paul Pogba,Manchester+United,24,CM,2,75.0,7435,8.0,19.50%,115,2,France,0,2,12,1,1
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0
381,Harry Kane,Tottenham,23,CF,1,60.0,4161,12.5,35.10%,224,1,England,0,2,17,1,0

## 4. More Approaches to Boolean Masking

In [8]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [9]:
players.loc[:,'position'].unique()

array(['LW', 'AM', 'GK', 'RW', 'CB', 'RB', 'CF', 'LB', 'DM', 'RM', 'CM',
       nan, 'SS', 'LM'], dtype=object)

In [10]:
# Q: Find all defenders from the player
# Defenders codes: LB, CB, RB

In [11]:
df_bool = players.loc[:,'position']\
                .isin(['LB','CB', 'RB'])
df_bool

0      False
1      False
2      False
3      False
4       True
       ...
460    False
461     True
462     True
463    False
464    False
Name: position, Length: 465, dtype: bool

In [12]:
players[df_bool]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
7,Nacho Monreal,Arsenal,31,LB,3,13.0,555,5.5,4.70%,115,2,Spain,0,4,1,1,0
8,Shkodran Mustafi,Arsenal,25,CB,3,30.0,1877,5.5,4.00%,90,2,Germany,0,3,1,1,1
17,Gabriel Paulista,Arsenal,26,CB,3,13.0,552,5.0,0.10%,45,3,Brazil,0,3,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Aaron Cresswell,West+Ham,27,LB,3,12.0,380,5.0,1.30%,60,1,England,0,3,20,0,0
458,Angelo Ogbonna,West+Ham,29,CB,3,9.0,247,4.5,1.10%,45,2,Italy,0,4,20,0,0
459,Pablo Zabaleta,West+Ham,32,RB,3,7.0,698,5.0,2.70%,45,3,Argentina,0,5,20,0,0
461,Arthur Masuaku,West+Ham,23,LB,3,7.0,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,4.5,198,4.5,0.30%,29,1,England,0,2,20,0,0

In [13]:
players.loc[:,'position'].value_counts()

position
CB    85
CM    63
CF    61
GK    42
DM    37
LW    36
LB    35
RB    34
RW    32
AM    17
LM     8
RM     7
SS     7
Name: count, dtype: int64

In [14]:
# between() method

In [15]:
players.loc[:,'market_value'].between(40,50, inclusive='neither')

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Name: market_value, Length: 465, dtype: bool

In [16]:
players[players.loc[:,'market_value'].between(40,50,inclusive='neither')]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
218,Philippe Coutinho,Liverpool,25,AM,1,45.0,2958,9.0,30.80%,171,3,Brazil,0,3,10,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.0,2074,8.0,3.80%,149,1,England,0,2,11,1,0
380,Dele Alli,Tottenham,21,CM,2,45.0,4626,9.5,38.60%,225,1,England,0,1,17,1,0

## 7. Combining Conditions

In [17]:
# all left backs: LB, who are age of 25 years or younger

In [18]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [19]:
(players.loc[:,'position'] == 'LW') & (players.loc[:,'age']<=25)

0      False
1      False
2      False
3      False
4      False
       ...
460    False
461    False
462    False
463    False
464    False
Length: 465, dtype: bool

In [20]:
players[(players.loc[:,'position'] == 'LW') & (players.loc[:,'age']<=25)]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
9,Alex Iwobi,Arsenal,21,LW,1,10.00,1812,5.5,1.00%,89,4,Nigeria,0,1,1,1,0
39,Ryan Fraser,Bournemouth,23,LW,1,5.00,516,5.5,1.60%,100,2,Scotland,0,2,2,0,0
71,Jiri Skalak,Brighton+and+Hove,25,LW,1,1.50,87,5.0,0.10%,0,2,Czech Republic,0,3,3,0,0
159,Ademola Lookman,Everton,19,LW,1,5.00,1387,5.5,0.30%,16,1,England,0,1,7,0,0
183,Harry Bunn,Huddersfield,24,LW,1,0.50,85,4.5,0.10%,0,1,England,0,2,8,0,0
206,Demarai Gray,Leicester+City,21,LW,1,9.00,593,5.5,1.10%,58,1,England,0,1,9,0,0
219,Sadio Mane,Liverpool,25,LW,1,40.00,3219,9.5,5.30%,156,4,Senegal,0,3,10,1,1
237,Ben Woodburn,Liverpool,17,LW,1,1.50,1241,4.5,0.10%,5,1,Wales,0,1,10,1,0
240,Sheyi Ojo,Liverpool,20,LW,1,2.00,383,5.0,0.10%,0,1,England,0,1,10,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.00,2074,8.0,3.80%,149,1,England,0,2,11,1,0
249,Leroy Sane,Manchester+City,21,LW,1,35.00,2302,8.5,8.80%,105,2,Germany,0,1,11,1,1
277,Jesse Lingard,Manchester+United,24,LW,1,12.00,1939,6.0,0.70%,60,1,England,0,2,12,1,0
305,Rolando Aarons,Newcastle+United,21,LW,1,0.75,170,4.5,0.10%,0,1,England,0,1,13,0,0
346,Ramadan Sobhi,Stoke+City,20,LW,1,5.00,461,5.0,1.10%,36,4,Egypt,0,1,15,0,1
383,Son Heung-min,Tottenham,25,LW,1,30.00,2185,8.0,1.60%,174,4,South Korea,0,3,17,1,0
398,Georges-Kevin N%27Koudou,Tottenham,22,LW,1,7.00,510,5.5,0.10%,8,2,France,0,2,17,1,1
416,Isaac Success,Watford,21,LW,1,4.00,474,5.5,0.10%,28,4,Nigeria,0,1,18,0,1

## 8. Conditions As Variables

In [21]:
all_LW = (players.loc[:,'position'] == 'LW') 
player_age = (players.loc[:,'age']<=25)

In [22]:
players[all_LW & player_age]

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
9,Alex Iwobi,Arsenal,21,LW,1,10.00,1812,5.5,1.00%,89,4,Nigeria,0,1,1,1,0
39,Ryan Fraser,Bournemouth,23,LW,1,5.00,516,5.5,1.60%,100,2,Scotland,0,2,2,0,0
71,Jiri Skalak,Brighton+and+Hove,25,LW,1,1.50,87,5.0,0.10%,0,2,Czech Republic,0,3,3,0,0
159,Ademola Lookman,Everton,19,LW,1,5.00,1387,5.5,0.30%,16,1,England,0,1,7,0,0
183,Harry Bunn,Huddersfield,24,LW,1,0.50,85,4.5,0.10%,0,1,England,0,2,8,0,0
206,Demarai Gray,Leicester+City,21,LW,1,9.00,593,5.5,1.10%,58,1,England,0,1,9,0,0
219,Sadio Mane,Liverpool,25,LW,1,40.00,3219,9.5,5.30%,156,4,Senegal,0,3,10,1,1
237,Ben Woodburn,Liverpool,17,LW,1,1.50,1241,4.5,0.10%,5,1,Wales,0,1,10,1,0
240,Sheyi Ojo,Liverpool,20,LW,1,2.00,383,5.0,0.10%,0,1,England,0,1,10,1,0
246,Raheem Sterling,Manchester+City,22,LW,1,45.00,2074,8.0,3.80%,149,1,England,0,2,11,1,0
249,Leroy Sane,Manchester+City,21,LW,1,35.00,2302,8.5,8.80%,105,2,Germany,0,1,11,1,1
277,Jesse Lingard,Manchester+United,24,LW,1,12.00,1939,6.0,0.70%,60,1,England,0,2,12,1,0
305,Rolando Aarons,Newcastle+United,21,LW,1,0.75,170,4.5,0.10%,0,1,England,0,1,13,0,0
346,Ramadan Sobhi,Stoke+City,20,LW,1,5.00,461,5.0,1.10%,36,4,Egypt,0,1,15,0,1
383,Son Heung-min,Tottenham,25,LW,1,30.00,2185,8.0,1.60%,174,4,South Korea,0,3,17,1,0
398,Georges-Kevin N%27Koudou,Tottenham,22,LW,1,7.00,510,5.5,0.10%,8,2,France,0,2,17,1,1
416,Isaac Success,Watford,21,LW,1,4.00,474,5.5,0.10%,28,4,Nigeria,0,1,18,0,1

## 9. Skill Challenge

In [32]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [23]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

In [24]:
# Find the players in our dataset that meet thees criteria
    # 1. they're English (nationality), and
    # 2. their market value is more that twice the average market value in the league (market_value), andvv
    # 3. they either have more than 4000 views (page_Views) or are a new signing (new_signing) but not both

### 1.

In [25]:
players.nationality.unique()

array(['Chile', 'Germany', 'Czech Republic', 'England', 'France', 'Spain',
       'Nigeria', 'Switzerland', 'Wales', 'Brazil', 'Egypt', 'Argentina',
       'Colombia', 'Bosnia', 'Norway', 'Poland', 'Scotland', 'Congo DR',
       'Ireland', 'Netherlands', 'Australia', "Cote d'Ivoire", 'Finland',
       'Cameroon', 'Austria', 'Israel', 'Northern Ireland', 'Canada',
       'Belgium', 'Iceland', 'Serbia', 'Portugal', 'Ghana', 'South Korea',
       'Mali', 'Senegal', 'Curacao', 'Denmark', 'Slovenia',
       'Trinidad and Tobago', 'Bermuda', 'Benin', 'Algeria', 'Jamaica',
       'Japan', 'Tunisia', 'Croatia', 'Estonia', 'Ecuador', 'Armenia',
       'Italy', 'Sweden', 'United States', 'Morocco', 'The Gambia',
       'Kenya', 'Greece', 'Uruguay', 'Romania', 'Venezuela',
       'New Zealand'], dtype=object)

In [26]:
 # 1. they're English (nationality)
English_player = players.nationality == 'England'
players[English_player].filter(items=['name','age','nationality'],axis=1)\
    .head()

                       name  age nationality
3              Theo Walcott   28     England
12  Alex Oxlade-Chamberlain   23     England
13  Alex Oxlade-Chamberlain   23     England
14            Jack Wilshere   25     England
18             Kieran Gibbs   27     England

### 2.

In [27]:
avg_value = players.market_value.mean()
bool_avg_value = players.market_value >= (2*avg_value)

In [28]:
 # 2. their market value is more that twice the average market value in the league (market_value)
players[bool_avg_value].filter(items=['name','market_value'], axis = 1)\
    .sort_values(by=['market_value'])\
    .head()

                name  market_value
384      Hugo Lloris          24.0
396      Erik Lamela          25.0
114  Antonio Rudiger          25.0
110  Michy Batshuayi          25.0
200    Islam Slimani          25.0

### 3.

In [31]:
players.new_signing.unique()

array([0, 1])

In [33]:
exor = (players.new_signing == 1) ^ (players.page_views > 4000)
exor

0       True
1       True
2      False
3      False
4      False
       ...
460     True
461     True
462    False
463     True
464    False
Length: 465, dtype: bool

In [35]:
# 3. they either have more than 4000 views (page_Views) or are a new signing (new_signing) but not both 
players[exor].filter(items=['name','new_signing','page_views'], axis=1)

                    name  new_signing  page_views
0         Alexis Sanchez            0        4329
1             Mesut Ozil            0        4395
8       Shkodran Mustafi            1        1877
21           Rob Holding            1         666
24           Lucas Perez            1        2055
..                   ...          ...         ...
448           Andre Ayew            1         845
457     Sofiane Feghouli            1         394
460  Edimilson Fernandes            1         288
461       Arthur Masuaku            1         199
463      Ashley Fletcher            1         412

[72 rows x 3 columns]

### Final solution:

In [37]:
players[English_player & bool_avg_value & exor]\
    .filter(items=['name','nationality','market_value','page_views','new_signing'])

            name nationality  market_value  page_views  new_signing
256  John Stones     England          35.0        1078            1
380    Dele Alli     England          45.0        4626            0
381   Harry Kane     England          60.0        4161            0