In [1]:
import pandas as pd
import numpy as np
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.head(6)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0

### 1. From our players df remove the rows labeled 2, 10, 21 and the martek_value colm. Do not modiffy orifinal df, assign it in df2!

In [16]:
df2 = players.drop(labels=[2, 10, 21], axis=0).drop(columns=['market_value'], axis=1)
df2.info(False)

<class 'pandas.core.frame.DataFrame'>
Index: 462 entries, 0 to 464
Columns: 16 entries, name to new_signing
dtypes: float64(1), int64(10), object(5)
memory usage: 61.4+ KB

### 2. Does the nationality colm in df2 contain any NA values? How many unique are there?

In [18]:
df2.nationality[df2.nationality.isnull()]

Series([], Name: nationality, dtype: object)

In [28]:
df2.nationality.drop_duplicates().size

61

In [30]:
df2.nationality.unique().size

61

### 3. Starting from df2, isolate a dataframe slice of players that contains only the unique age-position combination for each club. Do not include the club column itself !!

In [31]:
df2.drop_duplicates(subset=['age','position','club'])

,name,club,age,position,position_cat,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460,Edimilson Fernandes,West+Ham,21,CM,2,288,4.5,0.40%,38,2,Switzerland,0,1,20,0,1
461,Arthur Masuaku,West+Ham,23,LB,3,199,4.5,0.20%,34,4,Congo DR,0,2,20,0,1
462,Sam Byram,West+Ham,23,RB,3,198,4.5,0.30%,29,1,England,0,2,20,0,0
463,Ashley Fletcher,West+Ham,21,CF,1,412,4.5,5.90%,16,1,England,0,1,20,0,1
464,Diafra Sakho,West+Ham,27,CF,1,214,5.5,0.10%,12,4,Senegal,0,3,20,0,0

In [35]:
df2.shape

(462, 16)

In [36]:
df2.drop_duplicates(subset=['age','position','club']).loc[:,['age','position']]

     age position
0     28       LW
1     28       AM
3     28       RW
4     31       CB
5     22       RB
..   ...      ...
460   21       CM
461   23       LB
462   23       RB
463   21       CF
464   27       CF

[433 rows x 2 columns]