## 30. Calculating Aggregates With agg()

In [2]:
import pandas as pd
import numpy as np
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.head(6)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0
5,Hector Bellerin,Arsenal,22,RB,3,30.0,1675,6.0,13.70%,119,2,Spain,0,2,1,1,0

In [3]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 465 entries, 0 to 464
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   name          465 non-null    object
 1   club          465 non-null    object
 2   age           465 non-null    int64
 3   position      464 non-null    object
 4   position_cat  465 non-null    int64
 5   market_value  462 non-null    float64
 6   page_views    465 non-null    int64
 7   fpl_value     465 non-null    float64
 8   fpl_sel       465 non-null    object
 9   fpl_points    465 non-null    int64
 10  region        465 non-null    int64
 11  nationality   465 non-null    object
 12  new_foreign   465 non-null    int64
 13  age_cat       465 non-null    int64
 14  club_id       465 non-null    int64
 15  big_club      465 non-null    int64
 16  new_signing   465 non-null    int64
dtypes: float64(2), int64(10), object(5)
memory usage: 61.9+ KB

### extract the dtype **int** and **float**, Method - I

In [4]:
players.age.dtypes == 'int64'

True

In [5]:
players.fpl_value.dtypes == 'float64'

True

In [6]:
players.axes[1]
players['name'].dtype == object

True

In [7]:
num_col = []
for i in players.axes[1]:
    num_col.append(True) if (players[i].dtypes == 'int64') or (players[i].dtypes == 'float64') else num_col.append(False)
num_col

[False,
 False,
 True,
 False,
 True,
 True,
 True,
 True,
 False,
 True,
 True,
 False,
 True,
 True,
 True,
 True,
 True]

In [8]:
players.loc[:,num_col].shape

(465, 12)

In [9]:
players.loc[:,num_col].agg('sum')

age              12451.00
position_cat      1013.00
market_value      5140.05
page_views      358769.00
fpl_value         2534.50
fpl_points       26758.00
region             925.00
new_foreign         16.00
age_cat           1486.00
club_id           4768.00
big_club           144.00
new_signing         67.00
dtype: float64

### extract the dtype **int** and **float**, Method - II Easy

In [10]:
np.number

numpy.number

In [11]:
players.select_dtypes(['int','float64']).agg('sum')

age              12451.00
position_cat      1013.00
market_value      5140.05
page_views      358769.00
fpl_value         2534.50
fpl_points       26758.00
region             925.00
new_foreign         16.00
age_cat           1486.00
club_id           4768.00
big_club           144.00
new_signing         67.00
dtype: float64

In [12]:
players.select_dtypes(np.number).agg('sum')

age              12451.00
position_cat      1013.00
market_value      5140.05
page_views      358769.00
fpl_value         2534.50
fpl_points       26758.00
region             925.00
new_foreign         16.00
age_cat           1486.00
club_id           4768.00
big_club           144.00
new_signing         67.00
dtype: float64

In [13]:
players.select_dtypes(np.number).agg(['sum','max','min'])

,age,position_cat,market_value,page_views,fpl_value,fpl_points,region,new_foreign,age_cat,club_id,big_club,new_signing
sum,12451,1013,5140.05,358769,2534.5,26758,925,16,1486,4768,144,67
max,38,4,75.00,7664,12.5,264,4,1,6,20,1,1
min,17,1,0.05,3,4.0,0,1,0,1,1,0,0

## 31. Same-shape Transforms

In [14]:
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

In [16]:
players.iloc[:, [5,7]]

     market_value  fpl_value
0            65.0       12.0
1            50.0        9.5
2             7.0        5.5
3            20.0        7.5
4            22.0        6.0
..            ...        ...
460           5.0        4.5
461           7.0        4.5
462           4.5        4.5
463           1.0        4.5
464          10.0        5.5

[465 rows x 2 columns]

In [18]:
# usd to euro rate ---> 1 usd = 0.87 euro
players.iloc[:, [5,7]].transform(lambda x: x*0.87)

     market_value  fpl_value
0          56.550     10.440
1          43.500      8.265
2           6.090      4.785
3          17.400      6.525
4          19.140      5.220
..            ...        ...
460         4.350      3.915
461         6.090      3.915
462         3.915      3.915
463         0.870      3.915
464         8.700      4.785

[465 rows x 2 columns]

In [19]:
# usd to euro rate ---> 1 usd = 0.87 euro
players.iloc[:, [5,7]]*0.87

     market_value  fpl_value
0          56.550     10.440
1          43.500      8.265
2           6.090      4.785
3          17.400      6.525
4          19.140      5.220
..            ...        ...
460         4.350      3.915
461         6.090      3.915
462         3.915      3.915
463         0.870      3.915
464         8.700      4.785

[465 rows x 2 columns]

## 32. More Flexibility wity apply()

In [39]:
players.select_dtypes(['float']).head()

   market_value  fpl_value
0          65.0       12.0
1          50.0        9.5
2           7.0        5.5
3          20.0        7.5
4          22.0        6.0

In [40]:
def round_off_float(x):
    if x.dtype == 'float64':
        return round(x)
    return x

In [42]:
players.select_dtypes(['float']).apply(round_off_float).head()

   market_value  fpl_value
0          65.0       12.0
1          50.0       10.0
2           7.0        6.0
3          20.0        8.0
4          22.0        6.0

In [47]:
# also can do aggeregated tasks
players.select_dtypes(np.number).apply('mean')

age              26.776344
position_cat      2.178495
market_value     11.125649
page_views      771.546237
fpl_value         5.450538
fpl_points       57.544086
region            1.989247
new_foreign       0.034409
age_cat           3.195699
club_id          10.253763
big_club          0.309677
new_signing       0.144086
dtype: float64

In [48]:
# flipping the axis

In [50]:
# according to indexs
players.select_dtypes(np.number).apply('mean',axis=1)

0      392.333333
1      388.208333
2      143.708333
3      214.875000
4       91.916667
          ...
460     31.875000
461     24.791667
462     23.750000
463     39.875000
464     24.708333
Length: 465, dtype: float64