In [1]:
import pandas as pd
import numpy as np
data_url = 'https://andybek.com/pandas-soccer'
players = pd.read_csv(data_url)
players.head()

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0
1,Mesut Ozil,Arsenal,28,AM,1,50.0,4395,9.5,5.60%,167,2,Germany,0,4,1,1,0
2,Petr Cech,Arsenal,35,GK,4,7.0,1529,5.5,5.90%,134,2,Czech Republic,0,6,1,1,0
3,Theo Walcott,Arsenal,28,RW,1,20.0,2393,7.5,1.50%,122,1,England,0,4,1,1,0
4,Laurent Koscielny,Arsenal,31,CB,3,22.0,912,6.0,0.70%,121,2,France,0,4,1,1,0

### 36. Setting DataFrame Values

In [2]:
players.loc[0,'age'] = 2800
players.head(1)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,2800,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0

In [3]:
players.iloc[0,2] = 28
players.head(1)

,name,club,age,position,position_cat,market_value,page_views,fpl_value,fpl_sel,fpl_points,region,nationality,new_foreign,age_cat,club_id,big_club,new_signing
0,Alexis Sanchez,Arsenal,28,LW,1,65.0,4329,12.0,17.10%,264,3,Chile,0,4,1,1,0

### 39. Adding DataFrame Columns

In [6]:
players.columns

Index(['name', 'club', 'age', 'position', 'position_cat', 'market_value',
       'page_views', 'fpl_value', 'fpl_sel', 'fpl_points', 'region',
       'nationality', 'new_foreign', 'age_cat', 'club_id', 'big_club',
       'new_signing'],
      dtype='object')

In [8]:
players['mv_by_fpl'] =  players.market_value/players.fpl_value
players.loc[:,['market_value','fpl_value','mv_by_fpl',]].head()

   market_value  fpl_value  mv_by_fpl
0          65.0       12.0   5.416667
1          50.0        9.5   5.263158
2           7.0        5.5   1.272727
3          20.0        7.5   2.666667
4          22.0        6.0   3.666667

In [9]:
players.columns

Index(['name', 'club', 'age', 'position', 'position_cat', 'market_value',
       'page_views', 'fpl_value', 'fpl_sel', 'fpl_points', 'region',
       'nationality', 'new_foreign', 'age_cat', 'club_id', 'big_club',
       'new_signing', 'mv_by_fpl'],
      dtype='object')

#### **Easy Way**:

In [11]:
temp = players.iloc[0:5, 1:5]
temp

      club  age position  position_cat
0  Arsenal   28       LW             1
1  Arsenal   28       AM             1
2  Arsenal   35       GK             4
3  Arsenal   28       RW             1
4  Arsenal   31       CB             3

In [15]:
players_name = pd.Series(['R', 'M', 'N', 'H'])
mv_by_fpl =  players.market_value/players.fpl_value

print(type(players_name))
print(type(mv_by_fpl))

<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>

In [27]:
###
temp.insert(0,'name',players_name)
temp

  name     club  age position  position_cat
0    R  Arsenal   28       LW             1
1    M  Arsenal   28       AM             1
2    N  Arsenal   35       GK             4
3    H  Arsenal   28       RW             1
4  NaN  Arsenal   31       CB             3

In [16]:
temp.insert([0,2],['name','mv_by_fpl'],[players_name, mv_by_fpl])
temp

TypeError: unhashable type: 'list'

In [28]:
temp.assign(name2=players_name, mv_by_fpl=mv_by_fpl)

  name     club  age position  position_cat name2  mv_by_fpl
0    R  Arsenal   28       LW             1     R   5.416667
1    M  Arsenal   28       AM             1     M   5.263158
2    N  Arsenal   35       GK             4     N   1.272727
3    H  Arsenal   28       RW             1     H   2.666667
4  NaN  Arsenal   31       CB             3   NaN   3.666667

### 40. Adding Rows To DataFrames (Inefficient and Expensive Operation)

In [29]:
temp

  name     club  age position  position_cat
0    R  Arsenal   28       LW             1
1    M  Arsenal   28       AM             1
2    N  Arsenal   35       GK             4
3    H  Arsenal   28       RW             1
4  NaN  Arsenal   31       CB             3

In [31]:
players.club.unique()

array(['Arsenal', 'Bournemouth', 'Brighton+and+Hove', 'Burnley',
       'Chelsea', 'Crystal+Palace', 'Everton', 'Huddersfield',
       'Leicester+City', 'Liverpool', 'Manchester+City',
       'Manchester+United', 'Newcastle+United', 'Southampton',
       'Stoke+City', 'Swansea', 'Tottenham', 'Watford', 'West+Brom',
       'West+Ham'], dtype=object)

In [35]:
cristiano = pd.Series({
    'name': 'C',
    'club': 'Chelsea',
    'age': 40,
    'position': 'RW',
    'position_cat': 2,
}, name=5)
cristiano

name                  C
club            Chelsea
age                  40
position             RW
position_cat          2
Name: 5, dtype: object

In [36]:
### Removed from old version
temp.append(cristiano)

AttributeError: 'DataFrame' object has no attribute 'append'

In [39]:
###
pd.DataFrame([cristiano])

  name     club  age position  position_cat
5    C  Chelsea   40       RW             2

In [40]:
###
pd.concat([temp, pd.DataFrame([cristiano])])

  name     club  age position  position_cat
0    R  Arsenal   28       LW             1
1    M  Arsenal   28       AM             1
2    N  Arsenal   35       GK             4
3    H  Arsenal   28       RW             1
4  NaN  Arsenal   31       CB             3
5    C  Chelsea   40       RW             2